"""Attractions for 85 East, Southeast & South Asian destinations in RoamGenie (Phase D2)."""
from typing import Dict, List, Tuple

# Format: (name, category, entry_fee_inr, rating)
ASIA_ATTRACTIONS: Dict[Tuple[str, str], List[Tuple[str, str, float, float]]] = {
    # Japan (12)
    ("Tokyo", "Japan"): [
        ("Senso-ji Ancient Buddhist Temple & Nakamise-dori", "temple", 0.00, 4.8),
        ("Tokyo Skytree 634m Observation Tower", "viewpoint", 1800.00, 4.7),
        ("Meiji Jingu Shinto Shrine & Yoyogi Forest", "religious", 0.00, 4.8),
        ("Shibuya Crossing & Hachiko Statue", "cultural", 0.00, 4.7),
        ("teamLab Planets Immersive Digital Art Museum", "museum", 2400.00, 4.9),
        ("Tokyo Tower Observation Deck", "viewpoint", 1200.00, 4.6),
    ],
    ("Kyoto", "Japan"): [
        ("Fushimi Inari Taisha 10,000 Torii Gates Shrine", "religious", 0.00, 5.0),
        ("Kinkaku-ji (Golden Pavilion Temple)", "heritage", 300.00, 4.8),
        ("Arashiyama Bamboo Grove & Monkey Park", "nature", 0.00, 4.8),
        ("Kiyomizu-dera Wooden Stage Temple", "temple", 250.00, 4.9),
        ("Gion Geisha Historic Preservation District", "cultural", 0.00, 4.7),
    ],
    ("Osaka", "Japan"): [
        ("Osaka Castle & Tenshukaku Museum Park", "fort", 350.00, 4.7),
        ("Dotonbori Neon Glico Sign & Street Food", "cultural", 0.00, 4.8),
        ("Universal Studios Japan (USJ) & Super Nintendo World", "park", 5500.00, 4.9),
        ("Umeda Sky Building Floating Garden Observatory", "viewpoint", 900.00, 4.6),
        ("Kuromon Ichiba Seafood Market", "market", 0.00, 4.6),
    ],
    ("Hiroshima", "Japan"): [
        ("Hiroshima Peace Memorial Park & Genbaku Dome", "historical", 0.00, 4.9),
        ("Hiroshima Peace Memorial Museum", "museum", 120.00, 4.9),
        ("Itsukushima Shrine Floating Torii Gate (Miyajima)", "religious", 200.00, 5.0),
        ("Mount Misen Ropeway & Miyajima Primeval Forest", "viewpoint", 1100.00, 4.8),
        ("Hiroshima Castle (Carp Castle)", "fort", 220.00, 4.4),
    ],
    ("Nara", "Japan"): [
        ("Todai-ji Temple (World's Largest Bronze Buddha)", "temple", 350.00, 4.9),
        ("Nara Deer Park (Bow-Trained Free-Roaming Deer)", "wildlife", 0.00, 4.8),
        ("Kasuga Taisha Shrine with 3000 Lanterns", "religious", 300.00, 4.7),
        ("Kofuku-ji 5-Story Pagoda & National Treasure Museum", "heritage", 400.00, 4.6),
        ("Mount Wakakusa Grassland Summit Hike", "viewpoint", 100.00, 4.7),
    ],
    ("Sapporo", "Japan"): [
        ("Sapporo Clock Tower Historic Wooden Landmark", "historical", 120.00, 4.3),
        ("Odori Park & Sapporo TV Tower", "viewpoint", 600.00, 4.5),
        ("Sapporo Beer Museum & Tasting Hall", "museum", 0.00, 4.6),
        ("Shiroi Koibito Chocolate Theme Park", "park", 500.00, 4.5),
        ("Mount Moiwa Ropeway Sapporo Night View", "viewpoint", 1200.00, 4.8),
    ],
    ("Fukuoka", "Japan"): [
        ("Dazaifu Tenmangu Shinto Shrine", "religious", 0.00, 4.8),
        ("Nakasu Yatai Open-Air Ramen Stalls", "cultural", 0.00, 4.8),
        ("Fukuoka Tower 234m Seaside Lookout", "viewpoint", 480.00, 4.5),
        ("Ohori Park & Traditional Japanese Garden", "garden", 150.00, 4.6),
        ("Kushida Shrine (Hakata Gion Yamakasa)", "temple", 0.00, 4.6),
    ],
    ("Nagoya", "Japan"): [
        ("Nagoya Castle & Golden Shachihoko", "fort", 300.00, 4.7),
        ("Toyota Commemorative Museum of Industry and Technology", "museum", 300.00, 4.8),
        ("Atsuta Jingu Sacred Shinto Shrine", "religious", 0.00, 4.6),
        ("SCMAGLEV and Railway Park", "museum", 600.00, 4.8),
        ("Osu Kannon Temple & Vintage Shopping Arcade", "temple", 0.00, 4.6),
    ],
    ("Hakone", "Japan"): [
        ("Lake Ashi Hakone Pirate Sightseeing Cruise", "nature", 1200.00, 4.8),
        ("Hakone Ropeway & Owakudani Volcanic Valley", "viewpoint", 1500.00, 4.8),
        ("Hakone Open-Air Sculptural Museum", "museum", 1000.00, 4.9),
        ("Hakone Shrine (Torii Gate of Peace on Lake)", "religious", 0.00, 4.8),
        ("Hakone Yuryo Natural Forest Onsen", "cultural", 1100.00, 4.7),
    ],
    ("Kanazawa", "Japan"): [
        ("Kenroku-en Landscape Garden (Top 3 in Japan)", "garden", 180.00, 5.0),
        ("Kanazawa Castle Park", "fort", 0.00, 4.6),
        ("Higashi Chaya Historic Geisha Teahouse Quarter", "cultural", 0.00, 4.8),
        ("21st Century Museum of Contemporary Art", "museum", 700.00, 4.7),
        ("Omicho Market (Kanazawa's Kitchen)", "market", 0.00, 4.7),
    ],
    ("Takayama", "Japan"): [
        ("Sanmachi Suji Preserved Edo-Period Timber Town", "historical", 0.00, 4.9),
        ("Hida Folk Village (Hida no Sato Gassho-Zukuri)", "heritage", 420.00, 4.8),
        ("Takayama Jinya (Only Extant Edo Government House)", "historical", 250.00, 4.6),
        ("Miyagawa Morning Riverside Market", "market", 0.00, 4.6),
        ("Shirakawa-go UNESCO Thatched Farmhouse Excursion", "heritage", 1600.00, 5.0),
    ],
    ("Okinawa", "Japan"): [
        ("Okinawa Churaumi Aquarium (Whale Sharks)", "wildlife", 1300.00, 4.9),
        ("Shurijo Castle Ryukyu Kingdom Royal Park", "heritage", 250.00, 4.6),
        ("Manzamo Cape Elephant Trunk Coastal Cliff", "viewpoint", 60.00, 4.6),
        ("Kokusai Dori Street & Makishi Public Market", "cultural", 0.00, 4.5),
        ("Kabira Bay Glass Bottom Boats (Ishigaki)", "nature", 750.00, 4.8),
    ],

    # South Korea (6)
    ("Seoul", "South Korea"): [
        ("Gyeongbokgung Palace & Changing of the Royal Guard", "palace", 200.00, 4.8),
        ("N Seoul Tower & Namsan Cable Car Panoramic Deck", "viewpoint", 1100.00, 4.7),
        ("Bukchon Hanok Traditional Village", "cultural", 0.00, 4.7),
        ("Myeongdong Street Food & Cosmetics Hub", "market", 0.00, 4.6),
        ("Changdeokgung Palace & Secret Biwon Garden", "palace", 500.00, 4.9),
        ("Lotte World Tower Seoul Sky 555m Deck", "viewpoint", 1800.00, 4.7),
    ],
    ("Busan", "South Korea"): [
        ("Gamcheon Culture Village (Machu Picchu of Busan)", "cultural", 0.00, 4.8),
        ("Haeundae Beach & Coastal Walkway", "beach", 0.00, 4.7),
        ("Haedong Yonggungsa Coastal Seaside Temple", "temple", 0.00, 4.8),
        ("Jagalchi Historic Seafood Market", "market", 0.00, 4.6),
        ("Songdo Bay Marine Cable Car & Skywalk", "viewpoint", 1100.00, 4.7),
    ],
    ("Jeju City", "South Korea"): [
        ("Seongsan Ilchulbong (Sunrise Peak Crater)", "viewpoint", 300.00, 4.9),
        ("Manjanggul UNESCO Lava Tube Cave", "nature", 250.00, 4.7),
        ("Hallasan Volcano National Park Peak Hike", "adventure", 0.00, 4.9),
        ("Jeonbang Waterfall Falling into the Ocean", "waterfall", 120.00, 4.7),
        ("Jeju Dongmun Traditional Street Market", "market", 0.00, 4.7),
    ],
    ("Incheon", "South Korea"): [
        ("Incheon Chinatown & Jajangmyeon Museum", "cultural", 0.00, 4.5),
        ("Songdo Central Park & Water Taxi Canal Ride", "park", 250.00, 4.7),
        ("Wolmido Island Theme Park & Sea Promenade", "park", 0.00, 4.4),
        ("Jayu (Freedom) Park & General MacArthur Statue", "viewpoint", 0.00, 4.4),
        ("Jeondeungsa Ancient Ganghwa Island Temple", "temple", 180.00, 4.6),
    ],
    ("Gyeongju", "South Korea"): [
        ("Bulguksa UNESCO Silla Temple Complex", "temple", 350.00, 4.9),
        ("Seokguram Grotto Granite Buddha", "heritage", 350.00, 4.8),
        ("Donggung Palace and Wolji Pond Night Reflections", "palace", 180.00, 4.9),
        ("Cheomseongdae Ancient 7th Century Astronomical Observatory", "historical", 0.00, 4.6),
        ("Daereungwon Ancient Royal Tumuli Tomb Park", "garden", 180.00, 4.7),
    ],
    ("Jeonju", "South Korea"): [
        ("Jeonju Hanok Village (800 Traditional Wooden Houses)", "cultural", 0.00, 4.9),
        ("Gyeonggijeon Shrine & King Taejo Portrait", "historical", 180.00, 4.7),
        ("Jeondong Catholic Cathedral (Romanesque Architecture)", "architecture", 0.00, 4.6),
        ("Nambu Traditional Night Market & Bibimbap Alley", "market", 0.00, 4.8),
        ("Omokdae Hill Historic Sunset Pavilion", "viewpoint", 0.00, 4.6),
    ],

    # China, Hong Kong, Macau & Taiwan (14)
    ("Beijing", "China"): [
        ("Forbidden City (Palace Museum Imperial Complex)", "palace", 700.00, 4.9),
        ("Mutianyu Great Wall Cable Car & Toboggan", "fort", 1200.00, 5.0),
        ("Temple of Heaven (Tiantan)", "religious", 400.00, 4.8),
        ("Summer Palace (Yiheyuan) & Kunming Lake", "palace", 450.00, 4.9),
        ("Tiananmen Square & Chairman Mao Memorial", "monument", 0.00, 4.6),
    ],
    ("Shanghai", "China"): [
        ("The Bund (Waitan) Colonial Waterfront", "viewpoint", 0.00, 4.9),
        ("Yu Garden (Yuyuan) & Classical Ming Pavilions", "garden", 500.00, 4.7),
        ("Shanghai Tower 118th-Floor Top Deck", "viewpoint", 2100.00, 4.8),
        ("Oriental Pearl Radio & TV Tower Glass Floor", "viewpoint", 1800.00, 4.6),
        ("Nanjing Road Pedestrian Shopping Promenade", "cultural", 0.00, 4.7),
    ],
    ("Xi'an", "China"): [
        ("Terracotta Army of Emperor Qin Shi Huang (UNESCO)", "heritage", 1400.00, 5.0),
        ("Xi'an Ancient City Wall Cycling Track", "fort", 600.00, 4.8),
        ("Giant Wild Goose Pagoda & Musical Fountains", "temple", 350.00, 4.7),
        ("Muslim Quarter (Huimin Jie) Food Alley", "market", 0.00, 4.8),
        ("Great Mosque of Xi'an Sino-Islamic Architecture", "religious", 300.00, 4.6),
    ],
    ("Chengdu", "China"): [
        ("Chengdu Giant Panda Breeding Research Base", "wildlife", 650.00, 4.9),
        ("Jinli Ancient Street & Sichuan Snacks", "cultural", 0.00, 4.7),
        ("Leshan Giant Buddha 71m Cliff Carving Excursion", "heritage", 900.00, 4.9),
        ("Wuhou Shrine (Temple of Marquis Wu)", "historical", 600.00, 4.6),
        ("Kuanzhai Alley (Wide and Narrow Alleys)", "cultural", 0.00, 4.7),
    ],
    ("Guilin", "China"): [
        ("Li River Cruise from Guilin to Yangshuo Karsts", "nature", 3200.00, 5.0),
        ("Reed Flute Cave Illuminated Karst Caverns", "nature", 1100.00, 4.7),
        ("Elephant Trunk Hill (Symbol of Guilin)", "viewpoint", 600.00, 4.6),
        ("Longji (Dragon's Backbone) Rice Terraces Excursion", "nature", 950.00, 4.9),
        ("Sun and Moon Twin Pagodas on Shanhu Lake", "architecture", 400.00, 4.6),
    ],
    ("Hangzhou", "China"): [
        ("West Lake (Xi Hu) UNESCO Scenic Boat Cruise", "nature", 0.00, 4.9),
        ("Lingyin Ancient Buddhist Temple & Peak Flying Afar", "temple", 850.00, 4.8),
        ("Longjing (Dragon Well) Imperial Green Tea Village", "garden", 0.00, 4.7),
        ("Leifeng Pagoda Overlooking West Lake", "heritage", 450.00, 4.6),
        ("Qinghefang Ancient Ming & Qing Street", "cultural", 0.00, 4.6),
    ],
    ("Guangzhou", "China"): [
        ("Canton Tower 600m Rainbow Observation Deck", "viewpoint", 1800.00, 4.7),
        ("Chen Clan Ancestral Hall & Folk Art Museum", "heritage", 120.00, 4.8),
        ("Shamian Island Colonial French Architecture", "cultural", 0.00, 4.6),
        ("Yuexiu Mountain Park & Five Rams Statue", "park", 0.00, 4.5),
        ("Pearl River Night Skyline Light Cruise", "nature", 1200.00, 4.7),
    ],
    ("Lijiang", "China"): [
        ("Old Town of Lijiang (Dayan UNESCO Naxi Town)", "heritage", 0.00, 5.0),
        ("Jade Dragon Snow Mountain (Glacier Park 4506m Cable Car)", "adventure", 2200.00, 5.0),
        ("Blue Moon Valley Turquoise Glacial Waters", "nature", 0.00, 4.9),
        ("Black Dragon Pool & Moon Embracing Pavilion", "nature", 300.00, 4.7),
        ("Mu Palace (Residence of the Naxi Chieftains)", "palace", 400.00, 4.7),
    ],
    ("Hong Kong", "Hong Kong"): [
        ("Victoria Peak & Historic Peak Tram Sky Terrace 428", "viewpoint", 1600.00, 4.9),
        ("Tian Tan Big Buddha & Po Lin Monastery (Lantau)", "religious", 0.00, 4.8),
        ("Victoria Harbour Star Ferry Traditional Crossing", "nature", 50.00, 4.9),
        ("Hong Kong Disneyland Resort", "park", 6800.00, 4.8),
        ("Temple Street Night Market & Temple of Tin Hau", "market", 0.00, 4.6),
    ],
    ("Macau", "Macau"): [
        ("Ruins of Saint Paul's (Ruínas de São Paulo)", "heritage", 0.00, 4.9),
        ("Senado Square (Largo do Senado) Portuguese Tiles", "cultural", 0.00, 4.7),
        ("Macau Tower Convention & Skywalk Bungy", "viewpoint", 1800.00, 4.7),
        ("A-Ma Ancient 15th Century Sea Goddess Temple", "temple", 0.00, 4.6),
        ("Venetian Macao Resort & Indoor Grand Canals", "cultural", 0.00, 4.8),
    ],
    ("Taipei", "Taiwan"): [
        ("Taipei 101 Observatory (World's Fastest Elevator)", "viewpoint", 1600.00, 4.8),
        ("National Palace Museum Imperial Collections", "museum", 900.00, 4.9),
        ("Shilin Night Market Street Food Stalls", "market", 0.00, 4.8),
        ("Longshan Temple (Oldest Temple in Taipei)", "temple", 0.00, 4.8),
        ("Jiufen Old Street & Teahouses Excursion", "cultural", 0.00, 4.9),
    ],
    ("Kaohsiung", "Taiwan"): [
        ("Lotus Pond Dragon & Tiger Pagodas", "temple", 0.00, 4.7),
        ("Fo Guang Shan Buddha Museum (Massive Bronze Buddha)", "religious", 0.00, 4.9),
        ("Pier-2 Art Center Maritime Warehouses", "cultural", 0.00, 4.7),
        ("Cijin Island Seafood Street & Lighthouse Walk", "beach", 80.00, 4.6),
        ("Liuhe Tourist Night Market", "market", 0.00, 4.6),
    ],
    ("Taichung", "Taiwan"): [
        ("Sun Moon Lake Scenic Cycling & Boat Cruise", "nature", 400.00, 4.9),
        ("Rainbow Village Vibrant Folk Murals", "cultural", 0.00, 4.6),
        ("Gaomei Wetlands Windmill Boardwalk Sunset", "viewpoint", 0.00, 4.8),
        ("National Taichung Theater (Toyo Ito Architecture)", "architecture", 0.00, 4.7),
        ("Fengjia Night Market (Taiwan's Largest Night Market)", "market", 0.00, 4.8),
    ],
    ("Tainan", "Taiwan"): [
        ("Chihkan Tower (Fort Provintia)", "fort", 150.00, 4.6),
        ("Anping Old Fort (Fort Zeelandia)", "fort", 150.00, 4.6),
        ("Anping Tree House (Banyan Tree Engulfed Warehouse)", "nature", 150.00, 4.7),
        ("Tainan Confucius Temple (First Academy in Taiwan)", "temple", 60.00, 4.6),
        ("Garden Night Market (Huayuan)", "market", 0.00, 4.7),
    ],

    # Thailand (8)
    ("Bangkok", "Thailand"): [
        ("Grand Palace & Wat Phra Kaew (Emerald Buddha)", "palace", 1200.00, 4.8),
        ("Wat Arun (Temple of Dawn) Chao Phraya Pier", "temple", 250.00, 4.8),
        ("Wat Pho (Temple of the Reclining Buddha)", "temple", 500.00, 4.8),
        ("Chatuchak Weekend Market (15,000 Stalls)", "market", 0.00, 4.7),
        ("Chao Phraya River Dinner Cruise & Night Skyline", "nature", 1800.00, 4.8),
    ],
    ("Chiang Mai", "Thailand"): [
        ("Wat Phra That Doi Suthep Golden Mountain Temple", "temple", 120.00, 4.9),
        ("Elephant Nature Park Ethical Sanctuary", "wildlife", 6000.00, 5.0),
        ("Chiang Mai Sunday Walking Street Night Market", "market", 0.00, 4.8),
        ("Wat Chedi Luang Ancient Stupa Ruins", "temple", 120.00, 4.7),
        ("Doi Inthanon National Park (Thailand's Highest Peak)", "nature", 750.00, 4.9),
    ],
    ("Phuket", "Thailand"): [
        ("Phi Phi Islands & Maya Bay Speedboat Tour", "adventure", 4500.00, 4.9),
        ("Big Buddha Phuket 45m White Marble Statue", "monument", 0.00, 4.8),
        ("Phuket Old Town Sino-Portuguese Heritage Walk", "cultural", 0.00, 4.7),
        ("Patong Beach & Bangla Road Nightlife", "beach", 0.00, 4.4),
        ("Wat Chalong (Most Revered Monastery)", "temple", 0.00, 4.7),
    ],
    ("Pattaya", "Thailand"): [
        ("Sanctuary of Truth (All-Wood Carved Castle)", "architecture", 1200.00, 4.8),
        ("Nong Nooch Tropical Botanical Garden & Cultural Shows", "garden", 1500.00, 4.7),
        ("Coral Island (Koh Larn) Speedboat & Parasailing", "beach", 1000.00, 4.6),
        ("Pattaya Floating Market", "market", 500.00, 4.3),
        ("Big Buddha Temple (Wat Phra Yai Pattaya)", "temple", 0.00, 4.5),
    ],
    ("Krabi", "Thailand"): [
        ("Railay Beach & Phra Nang Cave Beach Rock Climbing", "beach", 0.00, 5.0),
        ("Four Islands Longtail Boat Tour (Koh Poda & Tup)", "adventure", 2000.00, 4.8),
        ("Tiger Cave Temple (Wat Tham Suea) 1260-Step Climb", "viewpoint", 0.00, 4.7),
        ("Emerald Pool (Sa Morakot) & Blue Lagoon Hot Springs", "nature", 500.00, 4.7),
        ("Hong Islands Lagoon Kayaking", "nature", 3000.00, 4.9),
    ],
    ("Koh Samui", "Thailand"): [
        ("Ang Thong National Marine Park 42-Island Tour", "nature", 4500.00, 4.9),
        ("Big Buddha Temple (Wat Phra Yai Samui)", "temple", 0.00, 4.6),
        ("Wat Plai Laem 18-Armed Guanyin Floating Temple", "temple", 0.00, 4.7),
        ("Chaweng Beach & Fisherman's Village Bophut", "beach", 0.00, 4.6),
        ("Na Muang Twin Waterfalls Trek", "waterfall", 0.00, 4.4),
    ],
    ("Ayutthaya", "Thailand"): [
        ("Wat Mahathat Buddha Head in Banyan Tree Roots", "heritage", 120.00, 4.8),
        ("Wat Phra Si Sanphet (Grand Three Pagodas)", "heritage", 120.00, 4.8),
        ("Wat Chaiwatthanaram Khmer-Style River Temple", "heritage", 120.00, 4.9),
        ("Wat Yai Chai Mongkhon Giant Reclining Buddha", "temple", 50.00, 4.7),
        ("Ayutthaya Historical Park Bicycle Tour", "cultural", 250.00, 4.8),
    ],
    ("Hua Hin", "Thailand"): [
        ("Hua Hin Historic Royal Railway Station", "historical", 0.00, 4.5),
        ("Phraya Nakhon Cave with Royal Gold Pavilion", "nature", 500.00, 5.0),
        ("Cicada Market Art & Handcrafted Crafts", "market", 0.00, 4.7),
        ("Khao Takiab (Monkey Mountain) & Golden Buddha Beach", "viewpoint", 0.00, 4.4),
        ("Maruekhathaiyawan Teakwood Seaside Palace", "palace", 150.00, 4.6),
    ],

    # Vietnam (8)
    ("Hanoi", "Vietnam"): [
        ("Hoan Kiem Lake & Ngoc Son Red Bridge Temple", "nature", 100.00, 4.8),
        ("Hanoi Old Quarter 36 Guild Streets & Street Food", "cultural", 0.00, 4.8),
        ("Temple of Literature (First National University)", "heritage", 100.00, 4.7),
        ("Ho Chi Minh Mausoleum & Ba Dinh Square", "monument", 0.00, 4.7),
        ("Imperial Citadel of Thang Long UNESCO", "heritage", 100.00, 4.6),
    ],
    ("Ho Chi Minh City", "Vietnam"): [
        ("War Remnants Museum", "museum", 140.00, 4.8),
        ("Cu Chi Tunnels Guerrilla Underground Network", "historical", 400.00, 4.8),
        ("Notre-Dame Cathedral Basilica of Saigon & Post Office", "architecture", 0.00, 4.6),
        ("Ben Thanh Market Traditional Souvenirs & Dining", "market", 0.00, 4.5),
        ("Bitexco Financial Tower Saigon Skydeck", "viewpoint", 750.00, 4.6),
    ],
    ("Da Nang", "Vietnam"): [
        ("Golden Bridge Giant Hands at Ba Na Hills", "viewpoint", 3000.00, 4.9),
        ("Marble Mountains (Ngu Hanh Son) Buddhist Caves", "temple", 150.00, 4.7),
        ("Dragon Bridge Weekend Fire & Water Show", "monument", 0.00, 4.8),
        ("My Khe Beach Golden Sand Coast", "beach", 0.00, 4.7),
        ("Lady Buddha (Chua Linh Ung) Son Tra Peninsula", "monument", 0.00, 4.8),
    ],
    ("Hoi An", "Vietnam"): [
        ("Hoi An Ancient Town UNESCO Lantern-Lit Streets", "heritage", 400.00, 5.0),
        ("Japanese Covered Bridge (Chùa Cầu)", "monument", 0.00, 4.7),
        ("An Bang White Sand Beach", "beach", 0.00, 4.7),
        ("My Son Sanctuary Champa Hindu Ruins Excursion", "heritage", 500.00, 4.8),
        ("Thu Bon River Evening Lantern Boat Cruise", "cultural", 300.00, 4.9),
    ],
    ("Ha Long", "Vietnam"): [
        ("Ha Long Bay UNESCO Limestone Karsts Overnight Cruise", "nature", 6500.00, 5.0),
        ("Sung Sot Cave (Surprise Cave Stalactites)", "nature", 0.00, 4.8),
        ("Ti Top Island Panoramic Summit & Sandy Beach", "viewpoint", 0.00, 4.7),
        ("Luon Cave Kayaking & Sea Monkeys", "adventure", 200.00, 4.7),
        ("Sun World Ha Long Complex & Cable Car", "park", 1200.00, 4.6),
    ],
    ("Nha Trang", "Vietnam"): [
        ("VinWonders Nha Trang Hon Tre Island Theme Park", "park", 3000.00, 4.8),
        ("Po Nagar Cham 8th Century Hindu Towers", "temple", 100.00, 4.7),
        ("Nha Trang Long Beach Promenade", "beach", 0.00, 4.6),
        ("Long Son Pagoda & Giant White Buddha", "temple", 0.00, 4.6),
        ("Hon Mun Marine Protected Coral Snorkeling", "adventure", 1800.00, 4.8),
    ],
    ("Hue", "Vietnam"): [
        ("Imperial City of Hue (Forbidden Purple City)", "palace", 700.00, 4.9),
        ("Thien Mu Pagoda Overlooking Perfume River", "religious", 0.00, 4.7),
        ("Mausoleum of Emperor Khai Dinh (Mosaic Art)", "heritage", 500.00, 4.9),
        ("Tomb of Emperor Tu Duc Pine Forest Complex", "heritage", 500.00, 4.7),
        ("Perfume River Dragon Boat Sunset Cruise", "nature", 400.00, 4.6),
    ],
    ("Sapa", "Vietnam"): [
        ("Fansipan Peak (Roof of Indochina 3143m Cable Car)", "viewpoint", 2800.00, 5.0),
        ("Muong Hoa Valley Stepped Rice Terraces Trek", "nature", 0.00, 4.9),
        ("Cat Cat Hmong Ethnic Cultural Village", "cultural", 300.00, 4.6),
        ("Silver Waterfall (Thac Bac) & Love Waterfall", "waterfall", 250.00, 4.6),
        ("Sapa Stone Church & Central Square", "architecture", 0.00, 4.5),
    ],

    # Indonesia (7)
    ("Bali", "Indonesia"): [
        ("Tanah Lot Sea Temple at Ocean Sunset", "temple", 350.00, 4.9),
        ("Uluwatu Clifftop Temple & Kecak Fire Dance", "cultural", 650.00, 4.9),
        ("Ulun Danu Beratan Floating Lake Temple", "temple", 400.00, 4.8),
        ("Mount Batur Sunrise Volcano Trekking", "adventure", 2200.00, 4.9),
        ("Seminyak Beach & Ocean Beach Clubs", "beach", 0.00, 4.7),
    ],
    ("Ubud", "Indonesia"): [
        ("Sacred Monkey Forest Sanctuary Ubud", "wildlife", 450.00, 4.8),
        ("Tegallalang Stepped Rice Terraces & Jungle Swings", "nature", 250.00, 4.8),
        ("Ubud Royal Palace (Puri Saren Agung)", "palace", 0.00, 4.6),
        ("Campuhan Ridge Walk Scenic Valley Trail", "nature", 0.00, 4.7),
        ("Tegenungan Waterfall Jungle Oasis", "waterfall", 150.00, 4.5),
    ],
    ("Jakarta", "Indonesia"): [
        ("National Monument (Monas) & Observation Deck", "monument", 120.00, 4.6),
        ("Istiqlal Mosque (Southeast Asia's Largest)", "religious", 0.00, 4.8),
        ("Kota Tua (Jakarta Old Town Batavia Square)", "historical", 0.00, 4.5),
        ("Taman Mini Indonesia Indah Cultural Park", "cultural", 250.00, 4.7),
        ("Jakarta Cathedral Neo-Gothic Marvel", "architecture", 0.00, 4.6),
    ],
    ("Yogyakarta", "Indonesia"): [
        ("Borobudur UNESCO 9th-Century Buddhist Temple", "heritage", 2200.00, 5.0),
        ("Prambanan UNESCO Hindu Temple Compound", "heritage", 2200.00, 4.9),
        ("Kraton Ngayogyakarta Hadiningrat (Sultan's Palace)", "palace", 150.00, 4.6),
        ("Taman Sari Royal Water Castle", "heritage", 120.00, 4.6),
        ("Malioboro Street Night Culture & Batik Stalls", "market", 0.00, 4.7),
    ],
    ("Lombok", "Indonesia"): [
        ("Gili Islands (Gili Trawangan Snorkeling & Turtles)", "adventure", 1500.00, 5.0),
        ("Mount Rinjani Active Volcano National Park Trek", "adventure", 4500.00, 5.0),
        ("Sendang Gile & Tiu Kelep Waterfalls", "waterfall", 200.00, 4.8),
        ("Kuta Lombok & Tanjung Aan Beach", "beach", 0.00, 4.8),
        ("Sade Traditional Sasak Tribal Village", "cultural", 100.00, 4.6),
    ],
    ("Labuan Bajo", "Indonesia"): [
        ("Komodo National Park Giant Dragon Ranger Trek", "wildlife", 2500.00, 5.0),
        ("Padar Island Iconic Three-Color Bays Viewpoint", "viewpoint", 0.00, 5.0),
        ("Pink Beach (Pantai Merah) Coral Snorkeling", "beach", 0.00, 4.9),
        ("Manta Point Swimming with Giant Manta Rays", "adventure", 3500.00, 5.0),
        ("Rangko Cave Underground Saltwater Pool", "nature", 300.00, 4.7),
    ],
    ("Bandung", "Indonesia"): [
        ("Tangkuban Perahu Active Volcano Crater", "nature", 1200.00, 4.7),
        ("Kawah Putih (White Crater) Turquoise Acid Lake", "nature", 500.00, 4.8),
        ("Saung Angklung Udjo Bamboo Music Theatre", "cultural", 450.00, 4.9),
        ("Dago Dream Park Forest Recreation", "park", 250.00, 4.5),
        ("Jalan Braga Heritage Dutch Architecture", "cultural", 0.00, 4.6),
    ],

    # Malaysia & Singapore (7)
    ("Kuala Lumpur", "Malaysia"): [
        ("Petronas Twin Towers Skybridge & 86th Floor Deck", "viewpoint", 1600.00, 4.8),
        ("Batu Caves 272 Colored Steps & Murugan Statue", "temple", 0.00, 4.8),
        ("KLCC Park & Lake Symphony Musical Fountains", "park", 0.00, 4.7),
        ("Bukit Bintang & Jalan Alor Night Street Food", "market", 0.00, 4.7),
        ("Thean Hou Multi-Tier Chinese Goddess Temple", "temple", 0.00, 4.8),
    ],
    ("George Town", "Malaysia"): [
        ("George Town UNESCO Street Art & Shophouse Walk", "cultural", 0.00, 4.9),
        ("Kek Lok Si (Temple of Supreme Bliss) Pagoda", "temple", 50.00, 4.8),
        ("Penang Hill Funicular Railway & Habitat Rainforest", "viewpoint", 1100.00, 4.8),
        ("Cheong Fatt Tze (The Blue Mansion)", "heritage", 450.00, 4.7),
        ("Gurney Drive Hawker Food Stalls", "market", 0.00, 4.7),
    ],
    ("Langkawi", "Malaysia"): [
        ("Langkawi Sky Bridge & SkyCab Cable Car", "viewpoint", 1500.00, 4.9),
        ("Kilim Geoforest Mangrove & Bat Cave Boat Tour", "nature", 1800.00, 4.8),
        ("Pantai Cenang Beach & Water Sports", "beach", 0.00, 4.6),
        ("Telaga Tujuh (Seven Wells) Waterfalls", "waterfall", 0.00, 4.6),
        ("Eagle Square (Dataran Lang) Giant Sea Eagle Statue", "monument", 0.00, 4.5),
    ],
    ("Melaka", "Malaysia"): [
        ("A Famosa 16th Century Portuguese Fortress", "fort", 0.00, 4.6),
        ("Stadthuys & Red Dutch Square", "heritage", 180.00, 4.6),
        ("Jonker Street Night Market & Peranakan Antiques", "market", 0.00, 4.8),
        ("Melaka Straits Floating Mosque (Masjid Selat)", "religious", 0.00, 4.7),
        ("Melaka River Scenic Heritage Cruise", "nature", 600.00, 4.7),
    ],
    ("Kota Kinabalu", "Malaysia"): [
        ("Mount Kinabalu UNESCO National Park (4095m Peak)", "adventure", 500.00, 5.0),
        ("Tunku Abdul Rahman Marine Park Island Hopping", "adventure", 1200.00, 4.8),
        ("Kota Kinabalu City Floating Mosque", "religious", 100.00, 4.6),
        ("Kokol Hill Sunset Panoramic Lookout", "viewpoint", 200.00, 4.7),
        ("Mari Mari Cultural Indigenous Longhouse Village", "cultural", 1800.00, 4.8),
    ],
    ("Kuching", "Malaysia"): [
        ("Bako National Park Proboscis Monkeys & Sea Stacks", "wildlife", 400.00, 4.9),
        ("Semenggoh Wildlife Rehabilitation Centre (Orangutans)", "wildlife", 200.00, 4.9),
        ("Kuching Waterfront & Darul Hana S-Bridge", "viewpoint", 0.00, 4.7),
        ("Sarawak Cultural Living Museum", "cultural", 1500.00, 4.8),
        ("Fort Margherita & Brooke Heritage Gallery", "fort", 350.00, 4.5),
    ],
    ("Singapore", "Singapore"): [
        ("Gardens by the Bay (Supertrees & Cloud Forest)", "garden", 2400.00, 5.0),
        ("Marina Bay Sands SkyPark Observation Deck", "viewpoint", 2000.00, 4.8),
        ("Jewel Changi Airport Rain Vortex Indoor Waterfall", "architecture", 0.00, 4.9),
        ("Singapore Zoo & Night Safari Tram", "wildlife", 3200.00, 4.9),
        ("Sentosa Island & Universal Studios Singapore", "park", 5200.00, 4.8),
        ("Chinatown & Buddha Tooth Relic Temple", "religious", 0.00, 4.7),
    ],

    # Philippines (6)
    ("Manila", "Philippines"): [
        ("Intramuros Walled Spanish City & Fort Santiago", "fort", 120.00, 4.7),
        ("San Agustin Church UNESCO Stone Church", "religious", 300.00, 4.8),
        ("Rizal Park (Luneta) National Monument", "monument", 0.00, 4.6),
        ("National Museum of Fine Arts Manila", "museum", 0.00, 4.8),
        ("Manila Bay Boardwalk Golden Sunset", "viewpoint", 0.00, 4.5),
    ],
    ("Cebu City", "Philippines"): [
        ("Basilica Minore del Santo Niño (Oldest Church)", "religious", 0.00, 4.8),
        ("Magellan's Cross Historic 1521 Landmark", "historical", 0.00, 4.5),
        ("Fort San Pedro Spanish Triangle Fortress", "fort", 80.00, 4.5),
        ("Temple of Leah Roman-Style Monument Viewpoint", "architecture", 180.00, 4.6),
        ("Sirao Flower Garden (Little Amsterdam of Cebu)", "garden", 150.00, 4.6),
    ],
    ("Boracay", "Philippines"): [
        ("White Beach Fine Powder Sand Coast", "beach", 0.00, 5.0),
        ("Willy's Rock Volcanic Formation & Shrine", "viewpoint", 0.00, 4.6),
        ("Puka Shell Beach Tranquil Waters", "beach", 0.00, 4.7),
        ("Bulabog Beach Kite Surfing & Wind Sports", "adventure", 1500.00, 4.7),
        ("Paraw Sailing Sunset Traditional Catamaran", "adventure", 1200.00, 4.9),
    ],
    ("El Nido", "Philippines"): [
        ("Big Lagoon & Small Lagoon Bacuit Bay Kayaking", "nature", 2400.00, 5.0),
        ("Secret Lagoon Hidden Limestone Chasm Swim", "nature", 0.00, 4.9),
        ("Seven Commandos Beach Coconut Palms", "beach", 0.00, 4.8),
        ("Nacpan 4km Twin Golden Beach", "beach", 80.00, 4.8),
        ("Taraw Cliff Canopy Walk & Viewdeck", "adventure", 650.00, 4.7),
    ],
    ("Coron", "Philippines"): [
        ("Kayangan Lake Cleanest Mountain Waters in Asia", "nature", 500.00, 5.0),
        ("Twin Lagoon Hidden Swimming Passage", "nature", 500.00, 4.9),
        ("Barracuda Lake Thermocline Scuba Diving", "adventure", 3500.00, 5.0),
        ("Mount Tapyas 724-Step Sunset Cross Lookout", "viewpoint", 0.00, 4.8),
        ("Maquinit Natural Saltwater Hot Springs", "nature", 300.00, 4.7),
    ],
    ("Siargao", "Philippines"): [
        ("Cloud 9 Boardwalk Famous Surfing Break", "adventure", 80.00, 4.9),
        ("Sugba Lagoon Turquoise Paddle Boarding", "nature", 1500.00, 4.9),
        ("Magpupungko Natural Tidal Rock Pools", "nature", 80.00, 4.7),
        ("Coconut Trees Viewpoint Overlook & Palm Forest", "viewpoint", 0.00, 4.8),
        ("Guyam, Daku & Naked Island Three-Island Tour", "beach", 2000.00, 4.9),
    ],

    # Cambodia, Laos & Myanmar (6)
    ("Siem Reap", "Cambodia"): [
        ("Angkor Wat 12th Century Khmer Monument", "heritage", 3100.00, 5.0),
        ("Bayon Temple Smiling Giant Stone Faces", "temple", 0.00, 5.0),
        ("Ta Prohm Jungle Temple (Tomb Raider Banyan Trees)", "temple", 0.00, 5.0),
        ("Tonle Sap Lake Floating Stilt Villages", "cultural", 1500.00, 4.6),
        ("Pub Street & Siem Reap Night Market", "market", 0.00, 4.6),
    ],
    ("Phnom Penh", "Cambodia"): [
        ("Royal Palace of Cambodia & Silver Pagoda", "palace", 850.00, 4.7),
        ("Tuol Sleng Genocide Museum (S-21 Prison)", "historical", 450.00, 4.8),
        ("Choeung Ek Genocidal Center (Killing Fields)", "historical", 500.00, 4.8),
        ("Wat Phnom Hilltop Buddhist Sanctuary", "temple", 100.00, 4.5),
        ("Phnom Penh Riverside Sisowath Quay", "viewpoint", 0.00, 4.5),
    ],
    ("Luang Prabang", "Laos"): [
        ("Kuang Si Three-Tier Turquoise Waterfalls", "waterfall", 200.00, 5.0),
        ("Mount Phousi 360-Degree Sunset Overlook", "viewpoint", 160.00, 4.8),
        ("Wat Xieng Thong Sweeping Roof Temple", "temple", 160.00, 4.8),
        ("Daily Morning Alms Giving Sacred Buddhist Ceremony", "religious", 0.00, 4.9),
        ("Pak Ou Sacred Caves with Thousands of Buddha Statues", "heritage", 600.00, 4.6),
    ],
    ("Vang Vieng", "Laos"): [
        ("Nam Song River Kayaking & River Tubing", "adventure", 650.00, 4.8),
        ("Tham Phu Kham Cave & Blue Lagoon 1", "nature", 150.00, 4.7),
        ("Nam Xay Viewpoint Cliffside Motorcycle Peak", "viewpoint", 150.00, 4.9),
        ("Vang Vieng Hot Air Balloon Flight Over Karsts", "adventure", 8500.00, 4.9),
        ("Tham Chang (Elephant Cave) Spring Oasis", "nature", 150.00, 4.6),
    ],
    ("Yangon", "Myanmar"): [
        ("Shwedagon Pagoda 99m Golden Mon Stupa", "religious", 650.00, 5.0),
        ("Sule Pagoda Historic Downtown Roundabout", "temple", 250.00, 4.6),
        ("Bogyoke Aung San (Scott) Handicraft Market", "market", 0.00, 4.6),
        ("Kandawgyi Royal Lake & Karaweik Barge", "nature", 150.00, 4.5),
        ("Chaukhtatgyi Giant 65m Reclining Buddha", "temple", 400.00, 4.7),
    ],
    ("Bagan", "Myanmar"): [
        ("Bagan Archaeological Zone 2,000 Ancient Temples", "heritage", 1800.00, 5.0),
        ("Ananda Temple (Westminster Abbey of Burma)", "temple", 0.00, 4.9),
        ("Dhammayangyi Temple (Largest Brick Temple in Bagan)", "temple", 0.00, 4.8),
        ("Shwesandaw Pagoda Sunset Platform", "viewpoint", 0.00, 4.9),
        ("Hot Air Balloon Flight Over Misty Bagan Stupas", "adventure", 24000.00, 5.0),
    ],

    # Sri Lanka, Maldives, Nepal & Bhutan (11)
    ("Colombo", "Sri Lanka"): [
        ("Gangaramaya Buddhist Temple on Beira Lake", "temple", 150.00, 4.8),
        ("Galle Face Green Waterfront Promenade", "viewpoint", 0.00, 4.6),
        ("National Museum of Colombo", "museum", 300.00, 4.6),
        ("Red Mosque (Jami Ul-Alfar Mosque Pettah)", "religious", 0.00, 4.8),
        ("Independence Memorial Hall & Arcade", "monument", 0.00, 4.5),
    ],
    ("Kandy", "Sri Lanka"): [
        ("Temple of the Sacred Tooth Relic (Sri Dalada Maligawa)", "religious", 500.00, 4.9),
        ("Royal Botanic Gardens Peradeniya (4000 Plant Species)", "garden", 550.00, 4.8),
        ("Kandy Lake Scenic Walk & Viewpoint", "nature", 0.00, 4.6),
        ("Bahirawakanda Vihara Buddha Statue Mountain", "viewpoint", 100.00, 4.6),
        ("Kandy Cultural Dance & Fire Walking Show", "cultural", 600.00, 4.7),
    ],
    ("Galle", "Sri Lanka"): [
        ("Galle Fort UNESCO Dutch 17th Century Ramparts", "fort", 0.00, 4.9),
        ("Galle Lighthouse on Point Utrecht Bastion", "monument", 0.00, 4.8),
        ("Unawatuna Beach & Coral Reef Snorkeling", "beach", 0.00, 4.7),
        ("Jungle Beach & Japanese Peace Pagoda", "beach", 0.00, 4.7),
        ("National Maritime Museum Galle", "museum", 200.00, 4.4),
    ],
    ("Ella", "Sri Lanka"): [
        ("Nine Arches Demodara Colonial Railway Bridge", "monument", 0.00, 5.0),
        ("Little Adam's Peak Panoramic Sunrise Hike", "viewpoint", 0.00, 4.9),
        ("Ella Rock Challenging Cliff Trek", "adventure", 0.00, 4.9),
        ("Ravana Falls Cascade & Natural Pool", "waterfall", 0.00, 4.6),
        ("Kandy to Ella Scenic Mountain Blue Train Ride", "adventure", 250.00, 5.0),
    ],
    ("Sigiriya", "Sri Lanka"): [
        ("Sigiriya Ancient Lion Rock Citadel (UNESCO)", "heritage", 2600.00, 5.0),
        ("Pidurangala Rock Sunrise View of Sigiriya", "viewpoint", 300.00, 5.0),
        ("Sigiriya Water & Boulder Pleasure Gardens", "garden", 0.00, 4.8),
        ("Dambulla UNESCO Royal Golden Cave Temples Excursion", "temple", 600.00, 4.9),
        ("Minneriya National Park Elephant Gathering Safari", "wildlife", 2500.00, 4.9),
    ],
    ("Nuwara Eliya", "Sri Lanka"): [
        ("Pedro Tea Estate & Factory Tour (Ceylon Tea)", "garden", 150.00, 4.7),
        ("Gregory Lake Swan Boating & Waterfront Park", "nature", 100.00, 4.5),
        ("Horton Plains National Park & World's End Precipice", "nature", 3000.00, 4.9),
        ("Victoria Park Nuwara Eliya", "park", 120.00, 4.4),
        ("Lover's Leap Waterfall", "waterfall", 0.00, 4.4),
    ],
    ("Male", "Maldives"): [
        ("Grand Friday Mosque & Islamic Centre Golden Dome", "religious", 0.00, 4.7),
        ("Malé Old Friday Mosque (Hukuru Miskiy Coral Stone)", "heritage", 0.00, 4.8),
        ("Malé Local Fish and Vegetable Market", "market", 0.00, 4.6),
        ("National Museum of Maldives (Sultan's Park)", "museum", 300.00, 4.5),
        ("Artificial Beach Male City Promenade", "beach", 0.00, 4.4),
    ],
    ("Maafushi", "Maldives"): [
        ("Maafushi Bikini Beach Turquoise Waters", "beach", 0.00, 4.8),
        ("Nurse Shark & Stingray Snorkeling Safari", "adventure", 3500.00, 5.0),
        ("Sandbank Picnic & Dolphin Watching Excursion", "nature", 2500.00, 4.9),
        ("Maafushi Coral Reef Scuba Diving", "adventure", 4500.00, 4.9),
        ("Water Sports Center Jet Ski & Parasailing", "adventure", 3000.00, 4.7),
    ],
    ("Kathmandu", "Nepal"): [
        ("Swayambhunath Stupa (Monkey Temple)", "religious", 150.00, 4.9),
        ("Pashupatinath Sacred Hindu Temple on Bagmati", "temple", 650.00, 4.9),
        ("Boudhanath Stupa (Massive Tibetan Mandala Stupa)", "religious", 250.00, 4.9),
        ("Kathmandu Durbar Square Historic Malla Palaces", "heritage", 650.00, 4.7),
        ("Thamel Tourist & Trekking Equipment Hub", "cultural", 0.00, 4.6),
    ],
    ("Pokhara", "Nepal"): [
        ("Phewa Lake Boat Cruise & Tal Barahi Island Temple", "nature", 350.00, 4.9),
        ("Sarangkot Sunrise Annapurna Range Lookout", "viewpoint", 100.00, 5.0),
        ("World Peace Pagoda (Shanti Stupa) Ridge", "viewpoint", 0.00, 4.8),
        ("Davis Falls (Patale Chhango Waterfall)", "waterfall", 60.00, 4.4),
        ("Sarangkot Tandem Paragliding Over Pokhara", "adventure", 5500.00, 5.0),
    ],
    ("Paro", "Bhutan"): [
        ("Tiger's Nest Monastery (Paro Taktsang Clifftop)", "heritage", 2000.00, 5.0),
        ("Rinpung Dzong (Paro Dzong Fortress & Wooden Bridge)", "fort", 0.00, 4.9),
        ("National Museum of Bhutan (Ta Dzong Watchtower)", "museum", 500.00, 4.8),
        ("Kyichu Lhakhang (7th Century Sacred Temple)", "temple", 0.00, 4.8),
        ("Chele La Pass (Highest Motor Road in Bhutan 3988m)", "viewpoint", 0.00, 4.9),
    ],
}
