"""Attractions for 105 European destinations in RoamGenie (Phase D2)."""
from typing import Dict, List, Tuple

# Format: (name, category, entry_fee_inr, rating)
EUROPE_ATTRACTIONS: Dict[Tuple[str, str], List[Tuple[str, str, float, float]]] = {
    # United Kingdom & Ireland (9)
    ("London", "United Kingdom"): [
        ("Tower of London & Crown Jewels", "heritage", 2800.00, 4.8),
        ("British Museum", "museum", 0.00, 4.9),
        ("Big Ben & Palace of Westminster", "monument", 0.00, 4.8),
        ("London Eye Observation Wheel", "viewpoint", 3200.00, 4.6),
        ("Westminster Abbey", "religious", 2400.00, 4.8),
        ("Buckingham Palace & Changing of the Guard", "palace", 2600.00, 4.6),
    ],
    ("Edinburgh", "United Kingdom"): [
        ("Edinburgh Castle", "fort", 2000.00, 4.8),
        ("Royal Mile Historic Street", "cultural", 0.00, 4.7),
        ("Arthur's Seat Volcanic Peak Trek", "viewpoint", 0.00, 4.8),
        ("Palace of Holyroodhouse", "palace", 1800.00, 4.6),
        ("National Museum of Scotland", "museum", 0.00, 4.8),
    ],
    ("Oxford", "United Kingdom"): [
        ("Bodleian Library & Radcliffe Camera", "heritage", 1200.00, 4.8),
        ("Christ Church College & Cathedral", "architecture", 1600.00, 4.7),
        ("Ashmolean Museum of Art and Archaeology", "museum", 0.00, 4.7),
        ("Oxford Botanic Garden", "garden", 600.00, 4.5),
        ("Punting on River Cherwell", "adventure", 2000.00, 4.7),
    ],
    ("Cambridge", "United Kingdom"): [
        ("King's College Chapel", "architecture", 1200.00, 4.8),
        ("Punting on the River Cam (The Backs)", "adventure", 2200.00, 4.9),
        ("Trinity College & Wren Library", "heritage", 800.00, 4.7),
        ("Fitzwilliam Museum", "museum", 0.00, 4.7),
        ("Mathematical Bridge Queens' College", "monument", 600.00, 4.5),
    ],
    ("Manchester", "United Kingdom"): [
        ("Old Trafford Football Stadium Tour", "cultural", 2500.00, 4.8),
        ("John Rylands Neo-Gothic Library", "heritage", 0.00, 4.8),
        ("Science and Industry Museum", "museum", 0.00, 4.6),
        ("National Football Museum", "museum", 1200.00, 4.5),
        ("Manchester Art Gallery", "museum", 0.00, 4.6),
    ],
    ("Belfast", "United Kingdom"): [
        ("Titanic Belfast Maritime Experience", "museum", 2200.00, 4.8),
        ("Belfast City Hall & Titanic Memorial Garden", "architecture", 0.00, 4.6),
        ("Ulster Museum & Botanic Gardens", "museum", 0.00, 4.7),
        ("Crumlin Road Gaol Historic Prison", "historical", 1400.00, 4.6),
        ("Black Cab Political Peace Walls Tour", "cultural", 3000.00, 4.9),
    ],
    ("Bath", "United Kingdom"): [
        ("Roman Baths & Pump Room", "heritage", 2200.00, 4.8),
        ("The Royal Crescent Georgian Architecture", "architecture", 0.00, 4.7),
        ("Bath Abbey & Tower Tour", "religious", 750.00, 4.7),
        ("Thermae Bath Spa Natural Thermal Rooftop", "nature", 3500.00, 4.7),
        ("Pulteney Bridge & River Avon Weir", "monument", 0.00, 4.6),
    ],
    ("Dublin", "Ireland"): [
        ("Guinness Storehouse Gravity Bar Experience", "cultural", 2400.00, 4.8),
        ("Trinity College Library & Book of Kells", "heritage", 1800.00, 4.8),
        ("Kilmainham Gaol Historic Museum", "historical", 800.00, 4.8),
        ("St. Patrick's Cathedral Dublin", "religious", 900.00, 4.6),
        ("Temple Bar Cultural Quarter & Live Folk Music", "cultural", 0.00, 4.6),
    ],
    ("Galway", "Ireland"): [
        ("Cliffs of Moher Day Excursion (Wild Atlantic Way)", "nature", 1200.00, 4.9),
        ("Quay Street Latin Quarter Buskers & Pubs", "cultural", 0.00, 4.8),
        ("Eyre Square (John F. Kennedy Memorial Park)", "park", 0.00, 4.4),
        ("Galway Cathedral (Our Lady Assumed into Heaven)", "religious", 0.00, 4.6),
        ("Spanish Arch & Long Walk Prom", "historical", 0.00, 4.5),
    ],

    # France (10)
    ("Paris", "France"): [
        ("Eiffel Tower Summit & Trocadero", "monument", 2600.00, 4.8),
        ("Louvre Museum & Mona Lisa", "museum", 2000.00, 4.9),
        ("Notre-Dame Cathedral & Île de la Cité", "religious", 0.00, 4.8),
        ("Arc de Triomphe & Champs-Élysées", "monument", 1400.00, 4.7),
        ("Musée d'Orsay Impressionist Art", "museum", 1600.00, 4.8),
        ("Sacre-Coeur Basilica & Montmartre Artists", "viewpoint", 0.00, 4.7),
    ],
    ("Nice", "France"): [
        ("Promenade des Anglais Mediterranean Walk", "beach", 0.00, 4.8),
        ("Colline du Château (Castle Hill) Viewpoint", "viewpoint", 0.00, 4.8),
        ("Vieille Ville (Old Town Nice) & Cours Saleya Market", "cultural", 0.00, 4.7),
        ("Musée Marc Chagall", "museum", 900.00, 4.6),
        ("Monaco & Monte Carlo Casino Day Excursion", "heritage", 1800.00, 4.8),
    ],
    ("Lyon", "France"): [
        ("Basilica of Notre-Dame de Fourvière", "religious", 0.00, 4.8),
        ("Vieux Lyon & Secret Renaissance Traboules", "historical", 0.00, 4.8),
        ("Ancient Theatre of Fourvière (Roman Theatres)", "heritage", 0.00, 4.6),
        ("Parc de la Tête d'Or Botanical Park & Lake", "garden", 0.00, 4.7),
        ("Musée des Confluences Science & Anthropology", "museum", 900.00, 4.6),
    ],
    ("Marseille", "France"): [
        ("Basilique Notre-Dame de la Garde", "religious", 0.00, 4.8),
        ("Calanques National Park Coastal Fjord Boat Tour", "nature", 2500.00, 4.9),
        ("Vieux-Port (Old Port of Marseille)", "viewpoint", 0.00, 4.6),
        ("MuCEM (Museum of European and Mediterranean Civilisations)", "museum", 1000.00, 4.6),
        ("Château d'If Historic Island Fortress", "fort", 700.00, 4.5),
    ],
    ("Bordeaux", "France"): [
        ("Place de la Bourse & Miroir d'Eau", "monument", 0.00, 4.8),
        ("La Cité du Vin Wine Museum", "museum", 2000.00, 4.7),
        ("Saint-Émilion Medieval Wine Village Excursion", "heritage", 1500.00, 4.9),
        ("Cathédrale Saint-André & Pey-Berland Tower", "religious", 600.00, 4.6),
        ("Grand Théâtre de Bordeaux Opera House", "architecture", 800.00, 4.7),
    ],
    ("Strasbourg", "France"): [
        ("Strasbourg Cathedral & Astronomical Clock", "religious", 700.00, 4.9),
        ("La Petite France Timbered Canals", "heritage", 0.00, 4.9),
        ("Palais Rohan & Museums", "museum", 700.00, 4.6),
        ("European Parliament Strasbourg Hemicycle", "cultural", 0.00, 4.6),
        ("Barrage Vauban Panoramic Roof Terrace", "viewpoint", 0.00, 4.7),
    ],
    ("Annecy", "France"): [
        ("Lake Annecy Pedal Boating & Swimming", "nature", 1200.00, 4.9),
        ("Palais de l'Île 12th-Century Canal Prison", "historical", 400.00, 4.6),
        ("Château d'Annecy Castle Museum", "fort", 550.00, 4.5),
        ("Pont des Amours (Lover's Bridge)", "monument", 0.00, 4.7),
        ("Gorges du Fier Suspended Footbridge", "adventure", 600.00, 4.7),
    ],
    ("Avignon", "France"): [
        ("Palais des Papes (Papal Palace UNESCO)", "palace", 1200.00, 4.8),
        ("Pont Saint-Bénézet (Pont d'Avignon)", "monument", 500.00, 4.6),
        ("Rocher des Doms Hilltop Gardens", "garden", 0.00, 4.6),
        ("Musée du Petit Palais Renaissance Art", "museum", 0.00, 4.5),
        ("Pont du Gard Ancient Roman Aqueduct Excursion", "heritage", 850.00, 4.9),
    ],
    ("Colmar", "France"): [
        ("La Petite Venise (Little Venice Canals)", "heritage", 600.00, 4.9),
        ("Unterlinden Museum & Isenheim Altarpiece", "museum", 1200.00, 4.8),
        ("Maison des Têtes (House of Heads)", "architecture", 0.00, 4.5),
        ("Pfister House (16th-Century Wooden Mansion)", "historical", 0.00, 4.6),
        ("Château du Haut-Kœnigsbourg Medieval Fortress Excursion", "fort", 900.00, 4.8),
    ],
    ("Cannes", "France"): [
        ("Boulevard de la Croisette & Film Festival Red Carpet", "cultural", 0.00, 4.7),
        ("Le Suquet (Old Town Cannes & Viewpoint)", "viewpoint", 0.00, 4.6),
        ("Îles de Lérins (Sainte-Marguerite Island Fortress)", "nature", 1500.00, 4.7),
        ("Plage de la Croisette Golden Beach", "beach", 0.00, 4.5),
        ("Musée des Explorations du Monde (Castre Museum)", "museum", 600.00, 4.4),
    ],

    # Italy (11)
    ("Rome", "Italy"): [
        ("Colosseum Ancient Roman Amphitheatre", "monument", 2200.00, 4.9),
        ("Roman Forum & Palatine Hill", "historical", 1800.00, 4.8),
        ("Pantheon of Agrippa", "architecture", 500.00, 4.8),
        ("Vatican Museums & Sistine Chapel", "museum", 2500.00, 4.9),
        ("Trevi Fountain (Fontana di Trevi)", "monument", 0.00, 4.8),
        ("Piazza Navona Bernini Fountains", "cultural", 0.00, 4.7),
    ],
    ("Florence", "Italy"): [
        ("Florence Cathedral (Duomo di Santa Maria del Fiore)", "religious", 0.00, 4.9),
        ("Uffizi Gallery Renaissance Masterpieces", "museum", 2400.00, 4.9),
        ("Ponte Vecchio Historic Goldsmiths Bridge", "monument", 0.00, 4.7),
        ("Galleria dell'Accademia (Michelangelo's David)", "museum", 1600.00, 4.9),
        ("Piazzale Michelangelo Panoramic Sunset View", "viewpoint", 0.00, 4.9),
    ],
    ("Venice", "Italy"): [
        ("Saint Mark's Basilica & Campanile", "religious", 400.00, 4.9),
        ("Doge's Palace (Palazzo Ducale)", "palace", 2500.00, 4.8),
        ("Grand Canal Gondola Traditional Cruise", "adventure", 7000.00, 4.8),
        ("Rialto Bridge & Historic Fish Market", "monument", 0.00, 4.7),
        ("Burano Island Colorful Fishermen Houses", "cultural", 800.00, 4.8),
    ],
    ("Milan", "Italy"): [
        ("Duomo di Milano & Rooftop Terraces", "architecture", 1600.00, 4.9),
        ("Galleria Vittorio Emanuele II Luxury Arcade", "cultural", 0.00, 4.7),
        ("Santa Maria delle Grazie (The Last Supper)", "museum", 1400.00, 4.9),
        ("Sforza Castle (Castello Sforzesco) & Museums", "fort", 400.00, 4.6),
        ("Teatro alla Scala Historic Opera House", "cultural", 1100.00, 4.7),
    ],
    ("Naples", "Italy"): [
        ("Pompeii Archaeological Park Roman Ruins Excursion", "historical", 1800.00, 4.9),
        ("Naples Underground (Napoli Sotterranea)", "adventure", 900.00, 4.7),
        ("National Archaeological Museum of Naples (MANN)", "museum", 1500.00, 4.8),
        ("Castel dell'Ovo on Gulf of Naples", "fort", 0.00, 4.6),
        ("Spaccanapoli Historic Street & Pizza Quarter", "cultural", 0.00, 4.8),
    ],
    ("Bologna", "Italy"): [
        ("Two Towers of Bologna (Asinelli Tower Climb)", "viewpoint", 500.00, 4.7),
        ("Piazza Maggiore & Neptune Fountain", "cultural", 0.00, 4.8),
        ("Sanctuary of the Madonna di San Luca (Longest Portico)", "religious", 0.00, 4.8),
        ("Archiginnasio Anatomical Theatre", "museum", 300.00, 4.6),
        ("Quadrilatero Ancient Food Market", "market", 0.00, 4.9),
    ],
    ("Amalfi", "Italy"): [
        ("Amalfi Cathedral of St. Andrew (Duomo di Amalfi)", "religious", 300.00, 4.8),
        ("Positano Cliffside Pastel Village Ferry", "viewpoint", 1200.00, 4.9),
        ("Ravello Villa Rufolo Gardens & Infinity Terrace", "garden", 700.00, 4.9),
        ("Emerald Grotto (Grotta dello Smeraldo)", "nature", 600.00, 4.6),
        ("Path of the Gods (Sentiero degli Dei) Cliff Trek", "adventure", 0.00, 5.0),
    ],
    ("Verona", "Italy"): [
        ("Verona Arena Roman Amphitheatre", "monument", 900.00, 4.8),
        ("Juliet's House (Casa di Giulietta) & Balcony", "historical", 600.00, 4.5),
        ("Piazza delle Erbe & Torre dei Lamberti", "viewpoint", 600.00, 4.7),
        ("Castelvecchio Bridge & Museum", "fort", 600.00, 4.7),
        ("Castel San Pietro Hilltop Funicular View", "viewpoint", 250.00, 4.8),
    ],
    ("Palermo", "Italy"): [
        ("Palermo Cathedral & Royal Tombs", "religious", 500.00, 4.7),
        ("Norman Palace & Cappella Palatina Gold Mosaics", "palace", 1500.00, 4.9),
        ("Ballarò & Vucciria Street Food Markets", "market", 0.00, 4.8),
        ("Teatro Massimo Opera House", "architecture", 800.00, 4.7),
        ("Mondello White Sand Beach", "beach", 0.00, 4.6),
    ],
    ("Siena", "Italy"): [
        ("Piazza del Campo (Palio Venue)", "cultural", 0.00, 4.9),
        ("Siena Cathedral (Duomo di Siena) Marble Floor", "religious", 800.00, 4.9),
        ("Torre del Mangia Panoramic Bell Tower", "viewpoint", 900.00, 4.8),
        ("Palazzo Pubblico & Civic Museum", "museum", 800.00, 4.7),
        ("Santa Maria della Scala Museum Complex", "historical", 700.00, 4.6),
    ],
    ("Lucca", "Italy"): [
        ("Lucca Renaissance Defensive Walls Park", "park", 0.00, 4.9),
        ("Guinigi Tower with Rooftop Oak Trees", "viewpoint", 500.00, 4.8),
        ("Piazza dell'Anfiteatro Oval Roman Square", "cultural", 0.00, 4.8),
        ("Lucca Cathedral (Duomo di San Martino)", "religious", 300.00, 4.6),
        ("Puccini Birthplace Museum", "museum", 800.00, 4.5),
    ],

    # Spain (11)
    ("Madrid", "Spain"): [
        ("Prado Museum (Museo del Prado)", "museum", 1400.00, 4.9),
        ("Royal Palace of Madrid (Palacio Real)", "palace", 1300.00, 4.8),
        ("El Retiro Park & Crystal Palace", "garden", 0.00, 4.8),
        ("Plaza Mayor & Mercado de San Miguel", "market", 0.00, 4.7),
        ("Reina Sofía Modern Art Museum (Guernica)", "museum", 1100.00, 4.7),
    ],
    ("Barcelona", "Spain"): [
        ("Basilica of the Sagrada Família", "architecture", 2400.00, 4.9),
        ("Park Güell Gaudi Mosaic Sculptures", "garden", 1000.00, 4.8),
        ("Casa Batlló Modernist Landmark", "architecture", 2900.00, 4.8),
        ("Gothic Quarter (Barri Gòtic) & Cathedral", "heritage", 0.00, 4.7),
        ("Barceloneta Beach & Mediterranean Promenade", "beach", 0.00, 4.5),
        ("La Boqueria Food Market", "market", 0.00, 4.7),
    ],
    ("Seville", "Spain"): [
        ("Royal Alcázar of Seville UNESCO Palace", "palace", 1300.00, 4.9),
        ("Seville Cathedral & Giralda Tower", "religious", 1100.00, 4.8),
        ("Plaza de España & Maria Luisa Park", "monument", 0.00, 4.9),
        ("Barrio Santa Cruz Jewish Quarter", "cultural", 0.00, 4.7),
        ("Triana Quarter Traditional Flamenco Show", "cultural", 1800.00, 4.8),
    ],
    ("Valencia", "Spain"): [
        ("City of Arts and Sciences (Ciudad de las Artes)", "architecture", 1200.00, 4.8),
        ("Oceanogràfic Aquarium (Europe's Largest)", "wildlife", 3000.00, 4.7),
        ("Valencia Cathedral & Holy Grail Chapel", "religious", 700.00, 4.6),
        ("Central Market of Valencia (Mercado Central)", "market", 0.00, 4.8),
        ("La Malvarrosa Beach & Paella Promenade", "beach", 0.00, 4.6),
    ],
    ("Granada", "Spain"): [
        ("Alhambra Palace & Generalife Gardens", "heritage", 1800.00, 5.0),
        ("Albaicín Moorish Quarter & Mirador de San Nicolás", "viewpoint", 0.00, 4.9),
        ("Granada Cathedral & Royal Chapel", "religious", 500.00, 4.6),
        ("Sacromonte Cave Houses & Flamenco", "cultural", 1500.00, 4.7),
        ("Carmen de los Mártires Gardens", "garden", 0.00, 4.7),
    ],
    ("Malaga", "Spain"): [
        ("Alcazaba of Malaga Moorish Fortress", "fort", 350.00, 4.7),
        ("Picasso Museum Malaga", "museum", 900.00, 4.6),
        ("Gibralfaro Castle Panoramic Lookout", "viewpoint", 350.00, 4.7),
        ("Malaga Cathedral (La Manquita)", "religious", 600.00, 4.6),
        ("La Malagueta Beach & Chiringuitos", "beach", 0.00, 4.5),
    ],
    ("San Sebastian", "Spain"): [
        ("La Concha Beach Crescent Promenade", "beach", 0.00, 4.9),
        ("Parte Vieja (Old Town Pintxos Trail)", "cultural", 0.00, 4.9),
        ("Monte Igueldo Funicular & Theme Park", "viewpoint", 400.00, 4.7),
        ("San Telmo Basque Culture Museum", "museum", 600.00, 4.5),
        ("Peine del Viento (Wind Comb) Sculptures", "monument", 0.00, 4.7),
    ],
    ("Bilbao", "Spain"): [
        ("Guggenheim Museum Bilbao (Frank Gehry)", "museum", 1400.00, 4.8),
        ("Casco Viejo (Old Town Seven Streets)", "cultural", 0.00, 4.6),
        ("Funicular de Artxanda Viewpoint", "viewpoint", 350.00, 4.7),
        ("Bilbao Fine Arts Museum (Museo de Bellas Artes)", "museum", 900.00, 4.6),
        ("Zubizuri Bridge (Calatrava Bridge)", "architecture", 0.00, 4.5),
    ],
    ("Cordoba", "Spain"): [
        ("Mosque-Cathedral of Córdoba (Mezquita)", "heritage", 1100.00, 5.0),
        ("Alcázar de los Reyes Cristianos Gardens", "palace", 500.00, 4.7),
        ("Roman Bridge of Córdoba & Calahorra Tower", "monument", 0.00, 4.7),
        ("Calleja de las Flores Flower Alley", "cultural", 0.00, 4.6),
        ("Judería (Historic Jewish Quarter)", "historical", 0.00, 4.8),
    ],
    ("Toledo", "Spain"): [
        ("Toledo Cathedral (Primate Cathedral of Saint Mary)", "religious", 900.00, 4.9),
        ("Alcázar of Toledo Military Fortress Museum", "fort", 500.00, 4.6),
        ("Mirador del Valle Panoramic Tagus Gorge Lookout", "viewpoint", 0.00, 5.0),
        ("Synagogue of Santa María la Blanca", "heritage", 300.00, 4.6),
        ("El Greco Museum", "museum", 300.00, 4.5),
    ],
    ("Palma de Mallorca", "Spain"): [
        ("La Seu (Cathedral of Santa Maria of Palma)", "religious", 800.00, 4.8),
        ("Bellver Castle Circular Fortress & Forest", "fort", 400.00, 4.6),
        ("Royal Palace of La Almudaina", "palace", 700.00, 4.5),
        ("Plaça Major & Palma Old Town Courtyards", "cultural", 0.00, 4.6),
        ("Platja de Palma & Yacht Marina", "beach", 0.00, 4.5),
    ],

    # Portugal (5)
    ("Lisbon", "Portugal"): [
        ("Belém Tower (Torre de Belém)", "fort", 600.00, 4.8),
        ("Jerónimos Monastery (Mosteiro dos Jerónimos)", "heritage", 1000.00, 4.9),
        ("Castelo de São Jorge & Alfama Walk", "fort", 1200.00, 4.7),
        ("Tram 28 Scenic Route & Miradouro de Santa Luzia", "viewpoint", 300.00, 4.7),
        ("Time Out Market Lisboa Gourmet Hub", "market", 0.00, 4.8),
    ],
    ("Porto", "Portugal"): [
        ("Dom Luís I Double-Deck Metal Bridge", "monument", 0.00, 4.9),
        ("Livraria Lello Fairytale Neo-Gothic Bookstore", "heritage", 700.00, 4.6),
        ("Clérigos Tower & Baroque Church", "viewpoint", 600.00, 4.7),
        ("Ribeira Historic Waterfront Promenade", "cultural", 0.00, 4.8),
        ("Port Wine Cellars Vila Nova de Gaia Tour", "cultural", 1600.00, 4.8),
    ],
    ("Sintra", "Portugal"): [
        ("Pena National Palace & Romantic Park", "palace", 1400.00, 4.9),
        ("Quinta da Regaleira & Initiation Well", "heritage", 1100.00, 4.9),
        ("Castle of the Moors (Castelo dos Mouros)", "fort", 800.00, 4.7),
        ("Monserrate Palace Exotic Botanical Gardens", "palace", 800.00, 4.7),
        ("Cabo da Roca (Westernmost Point of Mainland Europe)", "viewpoint", 0.00, 4.8),
    ],
    ("Faro", "Portugal"): [
        ("Faro Old Town (Cidade Velha) & Arco da Vila", "heritage", 0.00, 4.6),
        ("Ria Formosa Lagoon Natural Park Boat Tour", "nature", 2000.00, 4.8),
        ("Carmo Church & Chapel of Bones (Capela dos Ossos)", "historical", 200.00, 4.5),
        ("Ilha de Faro Sand Spit Beach", "beach", 0.00, 4.5),
        ("Municipal Museum of Faro", "museum", 200.00, 4.3),
    ],
    ("Funchal", "Portugal"): [
        ("Funchal Cable Car to Monte & Botanical Gardens", "viewpoint", 1600.00, 4.8),
        ("Monte Toboggan Traditional Wicker Sledge Ride", "adventure", 2500.00, 4.8),
        ("Cabo Girão Skywalk Glass Cliff Lookout", "viewpoint", 200.00, 4.7),
        ("Mercado dos Lavradores Tropical Fruit Market", "market", 0.00, 4.6),
        ("Levada das 25 Fontes Waterfall Walk", "nature", 0.00, 4.9),
    ],

    # Germany (8)
    ("Berlin", "Germany"): [
        ("Brandenburg Gate & Pariser Platz", "monument", 0.00, 4.9),
        ("Reichstag Building & Glass Dome Tour", "architecture", 0.00, 4.8),
        ("East Side Gallery (Berlin Wall Murals)", "historical", 0.00, 4.7),
        ("Museum Island (Pergamon & Neues Museum)", "museum", 1800.00, 4.9),
        ("Checkpoint Charlie Museum & Cold War Memorial", "historical", 1200.00, 4.4),
    ],
    ("Munich", "Germany"): [
        ("Marienplatz & Neues Rathaus Glockenspiel", "cultural", 0.00, 4.8),
        ("Nymphenburg Palace & Royal Gardens", "palace", 800.00, 4.7),
        ("English Garden & Eisbachwelle Surfing", "park", 0.00, 4.8),
        ("Deutsches Museum (World's Largest Science Museum)", "museum", 1500.00, 4.8),
        ("Hofbräuhaus Historic Royal Beer Hall", "cultural", 0.00, 4.7),
    ],
    ("Hamburg", "Germany"): [
        ("Elbphilharmonie Concert Hall Plaza", "architecture", 250.00, 4.8),
        ("Miniatur Wunderland (World's Largest Model Railway)", "museum", 1800.00, 4.9),
        ("Speicherstadt UNESCO Red-Brick Warehouse District", "heritage", 0.00, 4.8),
        ("St. Michael's Church (Michel) Tower View", "viewpoint", 500.00, 4.7),
        ("Port of Hamburg Historic Harbor Boat Tour", "nature", 1500.00, 4.7),
    ],
    ("Frankfurt", "Germany"): [
        ("Römerberg Historic Medieval Square", "cultural", 0.00, 4.7),
        ("Main Tower 200m Observation Deck", "viewpoint", 800.00, 4.7),
        ("Städel Museum Art Gallery", "museum", 1400.00, 4.8),
        ("Palmengarten Tropical Botanical Garden", "garden", 650.00, 4.6),
        ("Goethe House and Museum", "museum", 800.00, 4.5),
    ],
    ("Cologne", "Germany"): [
        ("Cologne Cathedral (Kölner Dom)", "religious", 0.00, 5.0),
        ("Hohenzollern Bridge Love Locks Promenade", "monument", 0.00, 4.7),
        ("Cologne Chocolate Museum (Schokoladenmuseum)", "museum", 1300.00, 4.6),
        ("Museum Ludwig Modern Art & Picasso Collection", "museum", 1100.00, 4.7),
        ("Old Town Cologne (Altstadt) & Kölsch Breweries", "cultural", 0.00, 4.6),
    ],
    ("Dresden", "Germany"): [
        ("Dresden Frauenkirche Reconstructed Baroque Church", "religious", 0.00, 4.9),
        ("Zwinger Palace & Old Masters Picture Gallery", "palace", 1200.00, 4.8),
        ("Semperoper Dresden Opera House", "architecture", 1000.00, 4.7),
        ("Dresden Castle (Residenzschloss) & Green Vault", "museum", 1400.00, 4.8),
        ("Brühl's Terrace (Balcony of Europe on Elbe)", "viewpoint", 0.00, 4.8),
    ],
    ("Heidelberg", "Germany"): [
        ("Heidelberg Castle & Great Vat of Wine", "fort", 800.00, 4.8),
        ("Philosophers' Walk (Philosophenweg) River Trail", "viewpoint", 0.00, 4.8),
        ("Old Bridge (Karl Theodor Bridge) & Monkey Bronze", "monument", 0.00, 4.7),
        ("Heidelberg University Historic Old Hall & Student Prison", "heritage", 450.00, 4.6),
        ("Hauptstraße Longest Pedestrian Street", "cultural", 0.00, 4.6),
    ],
    ("Nuremberg", "Germany"): [
        ("Nuremberg Imperial Castle (Kaiserburg)", "fort", 700.00, 4.7),
        ("Documentation Center Nazi Party Rally Grounds", "historical", 500.00, 4.7),
        ("Albrecht Dürer's House", "museum", 500.00, 4.5),
        ("Nuremberg Christmas Market Square (Hauptmarkt)", "market", 0.00, 4.8),
        ("Germanisches Nationalmuseum", "museum", 700.00, 4.7),
    ],

    # Switzerland (7)
    ("Zurich", "Switzerland"): [
        ("Grossmünster & Fraumünster Chagall Windows", "religious", 450.00, 4.7),
        ("Bahnhofstrasse Luxury Boulevard", "cultural", 0.00, 4.6),
        ("Lake Zurich Promenade & Steamboat Cruise", "nature", 1500.00, 4.8),
        ("Swiss National Museum (Landesmuseum)", "museum", 900.00, 4.7),
        ("Uetliberg Mountain Observation Tower", "viewpoint", 0.00, 4.8),
    ],
    ("Geneva", "Switzerland"): [
        ("Jet d'Eau 140m Water Fountain", "monument", 0.00, 4.7),
        ("Palais des Nations (UN European Headquarters)", "cultural", 1400.00, 4.6),
        ("St. Pierre Cathedral & Archaeological Site", "religious", 650.00, 4.6),
        ("Patek Philippe Horology Museum", "museum", 900.00, 4.8),
        ("L'Horloge Fleurie (Jardin Anglais Flower Clock)", "garden", 0.00, 4.5),
    ],
    ("Lucerne", "Switzerland"): [
        ("Chapel Bridge (Kapellbrücke) & Water Tower", "heritage", 0.00, 4.9),
        ("Mount Pilatus Golden Round Trip Cable Car", "adventure", 6500.00, 5.0),
        ("Lion Monument (Dying Lion of Lucerne)", "monument", 0.00, 4.7),
        ("Lake Lucerne Historic Paddle Steamer Cruise", "nature", 2500.00, 4.9),
        ("Swiss Museum of Transport (Verkehrshaus)", "museum", 2800.00, 4.8),
    ],
    ("Interlaken", "Switzerland"): [
        ("Jungfraujoch Top of Europe High Alpine Station", "adventure", 16000.00, 5.0),
        ("Harder Kulm Two Lakes Panoramic Bridge", "viewpoint", 3000.00, 4.8),
        ("Lake Brienz Turquoise Water Cruise & Giessbach Falls", "waterfall", 2800.00, 4.9),
        ("Schilthorn Piz Gloria (James Bond 007 Viewpoint)", "viewpoint", 8500.00, 4.9),
        ("Lauterbrunnen Valley of 72 Waterfalls Excursion", "nature", 0.00, 5.0),
    ],
    ("Zermatt", "Switzerland"): [
        ("Gornergrat Mountain Railway Matterhorn Lookout", "viewpoint", 8500.00, 5.0),
        ("Matterhorn Glacier Paradise (3883m Ice Palace)", "adventure", 9000.00, 4.9),
        ("Five Lakes Trail (5-Seenweg) Alpine Hike", "adventure", 0.00, 5.0),
        ("Zermatt Car-Free Village & Alpine Chalets", "cultural", 0.00, 4.8),
        ("Matterhorn Museum (Zermatlantis)", "museum", 900.00, 4.6),
    ],
    ("St. Moritz", "Switzerland"): [
        ("Lake St. Moritz Frozen Winter Polo Promenade", "nature", 0.00, 4.9),
        ("Corviglia & Piz Nair Alpine Ski Slopes", "adventure", 7500.00, 4.9),
        ("Muottas Muragl Funicular & Bernina Panoramic View", "viewpoint", 3200.00, 4.9),
        ("Segantini Art Museum", "museum", 1100.00, 4.6),
        ("Glacier Express World Heritage Train Route", "adventure", 12000.00, 5.0),
    ],
    ("Basel", "Switzerland"): [
        ("Basel Minster (Basler Münster) & Rhine View", "religious", 500.00, 4.8),
        ("Kunstmuseum Basel (Oldest Public Art Collection)", "museum", 1500.00, 4.8),
        ("Rhine River Ferry (Traditional Wooden Fähri)", "nature", 150.00, 4.7),
        ("Rathaus (Bright Red Renaissance Town Hall)", "architecture", 0.00, 4.6),
        ("Foundation Beyeler Modern Art Pavilion", "museum", 2200.00, 4.9),
    ],

    # Austria (5)
    ("Vienna", "Austria"): [
        ("Schönbrunn Imperial Palace & Baroque Gardens", "palace", 2000.00, 4.9),
        ("St. Stephen's Cathedral (Stephansdom)", "religious", 500.00, 4.8),
        ("The Hofburg Imperial Palace Complex", "palace", 1500.00, 4.8),
        ("Belvedere Palace & Gustav Klimt's The Kiss", "museum", 1600.00, 4.9),
        ("Vienna State Opera (Wiener Staatsoper)", "cultural", 1200.00, 4.8),
    ],
    ("Salzburg", "Austria"): [
        ("Hohensalzburg Fortress & Cable Funicular", "fort", 1200.00, 4.8),
        ("Mirabell Palace and Baroque Gardens", "garden", 0.00, 4.7),
        ("Mozart's Birthplace (Mozarts Geburtshaus)", "museum", 1000.00, 4.6),
        ("Salzburg Cathedral & DomQuartier", "religious", 1100.00, 4.7),
        ("Hellbrunn Palace Trick Fountains", "palace", 1200.00, 4.8),
    ],
    ("Innsbruck", "Austria"): [
        ("Golden Roof (Goldenes Dachl) Innsbruck", "monument", 450.00, 4.6),
        ("Nordkette Cable Car from City to Alpine Peak", "adventure", 3800.00, 4.9),
        ("Ambras Castle Renaissance Armoury & Portrait Gallery", "fort", 1000.00, 4.7),
        ("Hofkirche Court Church & Bronze Statues", "religious", 700.00, 4.6),
        ("Bergisel Ski Jump Stadium & Panoramic Cafe", "viewpoint", 900.00, 4.7),
    ],
    ("Hallstatt", "Austria"): [
        ("Hallstatt Skywalk World Heritage View", "viewpoint", 1800.00, 5.0),
        ("Salzwelten Hallstatt (7000-Year Salt Mine)", "historical", 3200.00, 4.9),
        ("Hallstatt Lake Promenade & Wooden Boathouses", "nature", 0.00, 5.0),
        ("Beinhaus (Hallstatt Charnel Bone House)", "historical", 200.00, 4.5),
        ("Dachstein Giant Ice Cave Excursion", "adventure", 3500.00, 4.9),
    ],
    ("Graz", "Austria"): [
        ("Schlossberg Clock Tower & Hilltop Fortress", "viewpoint", 0.00, 4.8),
        ("Kunsthaus Graz (The Friendly Alien Museum)", "museum", 850.00, 4.6),
        ("Eggenberg Palace UNESCO Stately Rooms", "palace", 1100.00, 4.8),
        ("Murinsel Floating Artificial Island on Mur", "architecture", 0.00, 4.5),
        ("Landeszeughaus (World's Largest Historic Armoury)", "museum", 850.00, 4.8),
    ],

    # Netherlands & Belgium (7)
    ("Amsterdam", "Netherlands"): [
        ("Rijksmuseum & Rembrandt's Night Watch", "museum", 2000.00, 4.9),
        ("Van Gogh Museum", "museum", 1900.00, 4.9),
        ("Anne Frank House & Secret Annex", "historical", 1400.00, 4.9),
        ("Amsterdam UNESCO Canal Ring Boat Cruise", "nature", 1500.00, 4.8),
        ("Vondelpark Cycling & Green Meadows", "park", 0.00, 4.7),
    ],
    ("Rotterdam", "Netherlands"): [
        ("Cube Houses (Kubuswoningen)", "architecture", 250.00, 4.6),
        ("Markthal Rotterdam Ceiling Art & Food Stalls", "market", 0.00, 4.7),
        ("Erasmus Bridge (The Swan)", "monument", 0.00, 4.7),
        ("Euromast 185m Tower Rotating Glass Lift", "viewpoint", 1100.00, 4.6),
        ("Kinderdijk Historic UNESCO Windmills Excursion", "heritage", 1400.00, 4.8),
    ],
    ("Utrecht", "Netherlands"): [
        ("Dom Tower (Domtoren) Highest Church Tower", "viewpoint", 1100.00, 4.8),
        ("Oudegracht Split-Level Canals & Wharf Cellars", "cultural", 0.00, 4.8),
        ("Rietveld Schröder House Modernist UNESCO", "architecture", 1500.00, 4.6),
        ("Centraal Museum & Miffy Museum", "museum", 1200.00, 4.5),
        ("Kasteel de Haar (Largest Castle in Netherlands)", "fort", 1600.00, 4.9),
    ],
    ("Brussels", "Belgium"): [
        ("Grand Place (Grote Markt) Guildhalls", "cultural", 0.00, 5.0),
        ("Atomium Giant Iron Crystal Structure", "monument", 1400.00, 4.6),
        ("Manneken Pis & Comic Book Street Murals", "monument", 0.00, 4.3),
        ("Royal Museums of Fine Arts of Belgium", "museum", 900.00, 4.7),
        ("Cinquantenaire Park & Triumphal Arch", "park", 0.00, 4.6),
    ],
    ("Bruges", "Belgium"): [
        ("Belfry of Bruges & Market Square", "viewpoint", 1200.00, 4.9),
        ("Bruges Medieval Canal Boat Tour", "nature", 1000.00, 4.9),
        ("Basilica of the Holy Blood", "religious", 250.00, 4.7),
        ("Church of Our Lady (Michelangelo's Madonna)", "religious", 600.00, 4.8),
        ("Begijnhof Historic Beguinage & White Cottages", "heritage", 0.00, 4.8),
    ],
    ("Ghent", "Belgium"): [
        ("Gravensteen (Castle of the Counts)", "fort", 1100.00, 4.8),
        ("Saint Bavo's Cathedral (Ghent Altarpiece)", "religious", 1100.00, 4.9),
        ("Graslei and Korenlei Medieval Harbor Quays", "cultural", 0.00, 4.9),
        ("Belfry of Ghent Dragon Tower", "viewpoint", 800.00, 4.7),
        ("Museum of Fine Arts Ghent (MSK)", "museum", 1000.00, 4.6),
    ],
    ("Antwerp", "Belgium"): [
        ("Antwerp Central Station (Railway Cathedral)", "architecture", 0.00, 4.9),
        ("Cathedral of Our Lady (Onze-Lieve-Vrouwekathedraal)", "religious", 1000.00, 4.8),
        ("MAS (Museum aan de Stroom) Rooftop Panorama", "viewpoint", 0.00, 4.7),
        ("Rubenshuis (Peter Paul Rubens Historic Studio)", "museum", 1000.00, 4.6),
        ("Grote Markt Antwerp & Brabo Fountain", "cultural", 0.00, 4.7),
    ],

    # Nordics & Scandinavia (9)
    ("Copenhagen", "Denmark"): [
        ("Nyhavn Colorful Waterfront & Wooden Ships", "cultural", 0.00, 4.9),
        ("Tivoli Gardens Historic Amusement Theme Park", "park", 1800.00, 4.8),
        ("The Little Mermaid (Den Lille Havfrue) Bronze", "monument", 0.00, 4.3),
        ("Amalienborg Palace & Royal Guard", "palace", 1100.00, 4.6),
        ("Rosenborg Castle & Royal Crown Jewels", "fort", 1200.00, 4.8),
    ],
    ("Stockholm", "Sweden"): [
        ("Vasa Maritime Museum (1628 Warship)", "museum", 1500.00, 5.0),
        ("Gamla Stan (Stockholm Medieval Old Town)", "cultural", 0.00, 4.8),
        ("Stockholm Royal Palace (Kungliga Slottet)", "palace", 1400.00, 4.7),
        ("Skansen Open-Air Museum & Nordic Wildlife", "cultural", 1600.00, 4.7),
        ("ABBA The Museum", "museum", 2100.00, 4.7),
    ],
    ("Oslo", "Norway"): [
        ("Oslo Opera House Walkable Marble Roof", "architecture", 0.00, 4.8),
        ("Vigeland Park Monolith Sculpture Park", "park", 0.00, 4.9),
        ("Munch Museum (Edvard Munch's The Scream)", "museum", 1300.00, 4.7),
        ("Akershus Fortress & Harbor Lookout", "fort", 0.00, 4.6),
        ("Fram Polar Exploration Ship Museum", "museum", 1100.00, 4.8),
    ],
    ("Bergen", "Norway"): [
        ("Bryggen UNESCO Hanseatic Wooden Wharf", "heritage", 0.00, 4.8),
        ("Fløibanen Funicular to Mount Fløyen Viewpoint", "viewpoint", 1200.00, 4.9),
        ("Bergen Fish Market (Fisketorget)", "market", 0.00, 4.4),
        ("Troldhaugen (Edvard Grieg Museum & Villa)", "museum", 1000.00, 4.7),
        ("Norway in a Nutshell Fjord Excursion", "adventure", 14000.00, 5.0),
    ],
    ("Stavanger", "Norway"): [
        ("Preikestolen (Pulpit Rock) Lysefjord Cliff Hike", "adventure", 0.00, 5.0),
        ("Gamle Stavanger (Preserved White Wooden Old Town)", "cultural", 0.00, 4.7),
        ("Swords in Rock (Sverd i fjell) Monument", "monument", 0.00, 4.7),
        ("Norwegian Petroleum Museum", "museum", 1200.00, 4.7),
        ("Lysefjord Sightseeing Boat Cruise", "nature", 4500.00, 4.9),
    ],
    ("Helsinki", "Finland"): [
        ("Helsinki Neoclassical White Cathedral", "religious", 0.00, 4.7),
        ("Suomenlinna Sea Fortress (UNESCO Islands)", "fort", 600.00, 4.8),
        ("Temppeliaukio Church (Rock Church)", "architecture", 650.00, 4.6),
        ("Old Market Hall (Vanha Kauppahalli) on Harbor", "market", 0.00, 4.6),
        ("Löyly Traditional Finnish Waterfront Sauna", "cultural", 1800.00, 4.8),
    ],
    ("Reykjavik", "Iceland"): [
        ("Hallgrímskirkja Church & Tower View", "viewpoint", 850.00, 4.8),
        ("Blue Lagoon Geothermal Mineral Spa Excursion", "nature", 7500.00, 4.8),
        ("Golden Circle (Gullfoss, Geysir & Thingvellir)", "nature", 6500.00, 5.0),
        ("Harpa Concert Hall & Glass Facade", "architecture", 0.00, 4.7),
        ("Perlan Glass Dome & Northern Lights Planetarium", "museum", 2800.00, 4.7),
    ],
    ("Tromso", "Norway"): [
        ("Northern Lights (Aurora Borealis) Wilderness Tour", "adventure", 8500.00, 5.0),
        ("Arctic Cathedral (Ishavskatedralen)", "architecture", 550.00, 4.6),
        ("Fjellheisen Cable Car to Mount Storsteinen", "viewpoint", 2200.00, 4.9),
        ("Polar Museum (Polarmuseet)", "museum", 800.00, 4.6),
        ("Husky Dog Sledding Arctic Safari", "adventure", 12000.00, 5.0),
    ],
    ("Rovaniemi", "Finland"): [
        ("Santa Claus Village on Arctic Circle", "cultural", 0.00, 4.8),
        ("Arktikum Science Museum & Glass Tunnel", "museum", 1400.00, 4.8),
        ("Reindeer Sleigh Ride in Snow Woods", "adventure", 3500.00, 4.9),
        ("SantaPark Underground Cavern Theme Park", "park", 3200.00, 4.5),
        ("Ounasvaara Winter Ski Resort & Viewpoint", "adventure", 2000.00, 4.6),
    ],

    # Central & Eastern Europe (11)
    ("Prague", "Czech Republic"): [
        ("Charles Bridge (Karlův Most) & Statues", "monument", 0.00, 4.9),
        ("Prague Castle Complex & St. Vitus Cathedral", "fort", 950.00, 4.9),
        ("Old Town Square & Astronomical Clock (Orloj)", "cultural", 0.00, 4.8),
        ("Petřín Lookout Tower & Funicular", "viewpoint", 600.00, 4.6),
        ("Jewish Quarter (Josefov) Historic Synagogues", "historical", 1200.00, 4.7),
    ],
    ("Budapest", "Hungary"): [
        ("Hungarian Parliament Building on Danube", "architecture", 2400.00, 4.9),
        ("Fisherman's Bastion & Matthias Church", "viewpoint", 300.00, 4.9),
        ("Széchenyi Thermal Bath & Outdoor Pools", "nature", 2400.00, 4.8),
        ("Buda Castle & National Gallery", "palace", 750.00, 4.7),
        ("Szimpla Kert Historic Ruin Bar", "cultural", 0.00, 4.8),
    ],
    ("Krakow", "Poland"): [
        ("Main Market Square (Rynek Główny) & Cloth Hall", "cultural", 0.00, 4.9),
        ("Wawel Royal Castle & Dragon's Den", "palace", 800.00, 4.8),
        ("Wieliczka UNESCO Underground Salt Mine Excursion", "heritage", 2200.00, 4.9),
        ("Kazimierz Historic Jewish Quarter", "historical", 0.00, 4.8),
        ("St. Mary's Basilica & Trumpet Call", "religious", 300.00, 4.8),
    ],
    ("Gdansk", "Poland"): [
        ("Long Market (Długi Targ) & Neptune Fountain", "cultural", 0.00, 4.9),
        ("Museum of the Second World War", "museum", 600.00, 4.9),
        ("St. Mary's Church (Largest Brick Church)", "religious", 300.00, 4.7),
        ("European Solidarity Centre", "museum", 600.00, 4.8),
        ("Sopot Pier (Molo) Baltic Sea Excursion", "viewpoint", 200.00, 4.7),
    ],
    ("Warsaw", "Poland"): [
        ("Royal Castle in Warsaw (Zamek Królewski)", "palace", 1000.00, 4.8),
        ("Warsaw Old Town Market Place (Stare Miasto)", "heritage", 0.00, 4.8),
        ("POLIN Museum of the History of Polish Jews", "museum", 900.00, 4.9),
        ("Łazienki Park & Palace on the Isle", "garden", 800.00, 4.9),
        ("Palace of Culture and Science 30th Floor Terrace", "viewpoint", 500.00, 4.6),
    ],
    ("Bratislava", "Slovakia"): [
        ("Bratislava Castle (Bratislavský hrad) Panorama", "fort", 900.00, 4.7),
        ("Michael's Gate (Michalská brána)", "historical", 500.00, 4.5),
        ("Blue Church (Church of St. Elizabeth)", "architecture", 0.00, 4.7),
        ("UFO Tower & Bridge Observation Deck", "viewpoint", 850.00, 4.6),
        ("Devin Castle Ruins on Danube Cliff Excursion", "fort", 600.00, 4.8),
    ],
    ("Bucharest", "Romania"): [
        ("Palace of the Parliament (World's Heaviest Building)", "architecture", 1000.00, 4.7),
        ("Old Town Lipscani Cobblestone Entertainment", "cultural", 0.00, 4.6),
        ("Dimitrie Gusti National Village Open-Air Museum", "museum", 400.00, 4.8),
        ("Romanian Athenaeum Historic Concert Hall", "architecture", 200.00, 4.8),
        ("Herăstrău Park (King Michael I Park) & Lake", "park", 0.00, 4.7),
    ],
    ("Dubrovnik", "Croatia"): [
        ("Dubrovnik Medieval City Walls Walk", "fort", 2800.00, 5.0),
        ("Stradun (Placa) Polished Limestone Street", "cultural", 0.00, 4.8),
        ("Mount Srđ Cable Car Dubrovnik Panorama", "viewpoint", 2200.00, 4.8),
        ("Lovrijenac Fortress (Red Keep)", "fort", 800.00, 4.7),
        ("Lokrum Island Nature Reserve & Iron Throne", "nature", 1800.00, 4.8),
    ],
    ("Split", "Croatia"): [
        ("Diocletian's Palace 4th-Century Roman Ruins", "heritage", 0.00, 4.9),
        ("Saint Domnius Cathedral & Bell Tower", "religious", 600.00, 4.7),
        ("Marjan Hill Forest Park & Sunset Lookout", "viewpoint", 0.00, 4.8),
        ("Riva Seafront Palm Promenade", "cultural", 0.00, 4.7),
        ("Hvar Island & Blue Cave Speedboat Excursion", "adventure", 8500.00, 5.0),
    ],
    ("Zagreb", "Croatia"): [
        ("St. Mark's Church Colorful Tiled Roof", "religious", 0.00, 4.7),
        ("Zagreb Cathedral & Upper Town (Gornji Grad)", "heritage", 0.00, 4.7),
        ("Museum of Broken Relationships", "museum", 600.00, 4.7),
        ("Lotrščak Tower Cannon & Funicular", "viewpoint", 200.00, 4.6),
        ("Dolac Open-Air Farmers' Market (Red Umbrellas)", "market", 0.00, 4.7),
    ],
    ("Ljubljana", "Slovenia"): [
        ("Ljubljana Castle & Funicular Railway", "fort", 1100.00, 4.8),
        ("Triple Bridge (Tromostovje) & Dragon Bridge", "monument", 0.00, 4.8),
        ("Ljubljanica River Eco Boat Cruise", "nature", 1000.00, 4.7),
        ("Tivoli City Park & Promenade", "park", 0.00, 4.6),
        ("Metelkova Mesto Alternative Cultural Center", "cultural", 0.00, 4.5),
    ],

    # Baltic & Balkans (6)
    ("Bled", "Slovenia"): [
        ("Lake Bled Pletna Wooden Boat to Island Church", "adventure", 1600.00, 5.0),
        ("Bled Castle (Blejski grad) Cliff Fortress", "fort", 1300.00, 4.8),
        ("Vintgar Gorge Wooden Walkways & Waterfalls", "nature", 850.00, 4.9),
        ("Ojstrica & Mala Osojnica Viewpoint Hike", "viewpoint", 0.00, 5.0),
        ("Straža Bled Toboggan Track", "adventure", 800.00, 4.6),
    ],
    ("Tallinn", "Estonia"): [
        ("Tallinn Medieval Old Town (Vanalinn UNESCO)", "heritage", 0.00, 4.9),
        ("Toompea Castle & Alexander Nevsky Cathedral", "religious", 0.00, 4.8),
        ("Kohtuotsa Viewing Platform (The Times We Had)", "viewpoint", 0.00, 4.9),
        ("Kadriorg Baroque Palace & Park", "palace", 800.00, 4.7),
        ("Seaplane Harbour (Lennusadam) Maritime Museum", "museum", 1300.00, 4.8),
    ],
    ("Riga", "Latvia"): [
        ("Riga Art Nouveau District (Alberta Iela)", "architecture", 0.00, 4.8),
        ("House of the Blackheads (Melngalvju Nams)", "heritage", 600.00, 4.8),
        ("St. Peter's Church 123m Tower View", "viewpoint", 800.00, 4.7),
        ("Riga Central Market (Former Zeppelin Hangars)", "market", 0.00, 4.6),
        ("Dome Cathedral (Rīgas Doms) & Organ", "religious", 500.00, 4.6),
    ],
    ("Vilnius", "Lithuania"): [
        ("Gediminas Tower & Upper Castle Hill", "fort", 500.00, 4.8),
        ("Užupis Bohemian Independent Republic", "cultural", 0.00, 4.8),
        ("St. Anne's Flamboyant Gothic Church", "religious", 0.00, 4.8),
        ("Vilnius Cathedral & Bell Tower Plaza", "architecture", 0.00, 4.7),
        ("Trakai Island Castle Excursion", "fort", 1000.00, 4.9),
    ],
    ("Sofia", "Bulgaria"): [
        ("St. Alexander Nevsky Cathedral Golden Dome", "religious", 0.00, 4.9),
        ("Boyana Church UNESCO Medieval Frescoes", "heritage", 450.00, 4.7),
        ("Vitosha Mountain National Park Hike", "nature", 0.00, 4.8),
        ("Rotunda of Saint George (4th-Century Roman)", "historical", 0.00, 4.6),
        ("Central Mineral Baths & Sofia History Museum", "museum", 300.00, 4.5),
    ],
    ("Belgrade", "Serbia"): [
        ("Belgrade Fortress & Kalemegdan Park", "fort", 0.00, 4.9),
        ("Church of Saint Sava (Hram Svetog Save)", "religious", 0.00, 4.9),
        ("Knez Mihailova Pedestrian Shopping Boulevard", "cultural", 0.00, 4.7),
        ("Skadarlija Bohemian Vintage Quarter", "cultural", 0.00, 4.7),
        ("Nikola Tesla Museum & Inventions", "museum", 700.00, 4.8),
    ],

    # Greece (6)
    ("Athens", "Greece"): [
        ("Acropolis of Athens & Parthenon", "heritage", 1800.00, 5.0),
        ("Acropolis Museum", "museum", 1300.00, 4.9),
        ("Plaka Historic Cobblestone Neighborhood", "cultural", 0.00, 4.8),
        ("Temple of Olympian Zeus", "historical", 700.00, 4.5),
        ("Mount Lycabettus Funicular Sunset Lookout", "viewpoint", 850.00, 4.8),
    ],
    ("Santorini", "Greece"): [
        ("Oia Village Caldera Sunset Point", "viewpoint", 0.00, 5.0),
        ("Fira to Oia Clifftop Scenic Trek", "adventure", 0.00, 4.9),
        ("Red Beach (Kokkini Paralia) Volcanic Cliffs", "beach", 0.00, 4.6),
        ("Ancient Akrotiri Minoan Bronze Age Ruins", "historical", 1100.00, 4.8),
        ("Santorini Volcanic Caldera & Hot Springs Cruise", "nature", 3500.00, 4.9),
    ],
    ("Mykonos", "Greece"): [
        ("Mykonos 16th-Century Windmills (Kato Mili)", "monument", 0.00, 4.8),
        ("Little Venice Waterfront Seaside Balconies", "cultural", 0.00, 4.8),
        ("Panagia Paraportiani Whitewashed Church", "architecture", 0.00, 4.6),
        ("Delos Island Sacred Archaeological Sanctuary", "heritage", 1800.00, 4.9),
        ("Paradise Beach & Beach Clubs", "beach", 0.00, 4.5),
    ],
    ("Crete", "Greece"): [
        ("Palace of Knossos Minoan Labyrinth", "heritage", 1400.00, 4.8),
        ("Samaria Gorge 16km National Park Hike", "adventure", 500.00, 4.9),
        ("Elafonissi Pink Sand Beach & Lagoon", "beach", 0.00, 4.9),
        ("Chania Venetian Old Harbour & Lighthouse", "cultural", 0.00, 4.8),
        ("Balos Lagoon & Gramvousa Island Boat Tour", "nature", 2500.00, 5.0),
    ],
    ("Rhodes", "Greece"): [
        ("Medieval City of Rhodes UNESCO Walled Town", "fort", 0.00, 4.9),
        ("Palace of the Grand Master of the Knights", "palace", 750.00, 4.8),
        ("Acropolis of Lindos Clifftop Sanctuary", "heritage", 1100.00, 4.9),
        ("Valley of the Butterflies (Petaloudes)", "nature", 450.00, 4.5),
        ("Mandraki Harbour (Colossus of Rhodes Site)", "viewpoint", 0.00, 4.6),
    ],
    ("Thessaloniki", "Greece"): [
        ("White Tower of Thessaloniki & Waterfront Promenade", "monument", 600.00, 4.8),
        ("Rotunda & Arch of Galerius (Kamara)", "historical", 450.00, 4.7),
        ("Church of Saint Demetrius (Agios Dimitrios Crypt)", "religious", 0.00, 4.8),
        ("Ano Poli (Upper Old Town Fortress & Castles)", "viewpoint", 0.00, 4.8),
        ("Archaeological Museum of Thessaloniki", "museum", 700.00, 4.7),
    ],
}
