"""Attractions for 144 Indian destinations in RoamGenie (Phase D2)."""
from typing import Dict, List, Tuple

# Format: (name, category, entry_fee_inr, rating)
INDIA_ATTRACTIONS: Dict[Tuple[str, str], List[Tuple[str, str, float, float]]] = {
    # Existing Mysuru (IDs 1, 2, 3 already exist in DB): adding remaining to reach 5
    ("Mysuru", "India"): [
        ("Mysuru Palace", "heritage", 100.00, 4.9),  # existing ID 1
        ("Chamundi Hill & Temple", "temple", 0.00, 4.6),  # existing ID 2
        ("Brindavan Gardens", "nature", 50.00, 4.2),  # existing ID 3
        ("St. Philomena's Cathedral", "heritage", 0.00, 4.5),
        ("Mysuru Zoo (Sri Chamarajendra Zoological Gardens)", "wildlife", 100.00, 4.7),
    ],
    ("Kochi", "India"): [
        ("Fort Kochi Beach & Chinese Fishing Nets", "nature", 0.00, 4.5),
        ("Mattancherry Dutch Palace", "heritage", 25.00, 4.3),
        ("Jewish Synagogue & Jew Town", "historical", 20.00, 4.4),
        ("Santa Cruz Cathedral Basilica", "architecture", 0.00, 4.6),
        ("Kerala Kathakali Centre", "cultural", 400.00, 4.8),
    ],
    ("Jaipur", "India"): [
        ("Amber Palace & Fort", "heritage", 200.00, 4.8),
        ("Hawa Mahal (Palace of Winds)", "heritage", 50.00, 4.6),
        ("City Palace Jaipur", "palace", 300.00, 4.7),
        ("Jantar Mantar Astronomical Observatory", "historical", 200.00, 4.6),
        ("Nahargarh Fort Sunset Point", "viewpoint", 100.00, 4.7),
        ("Jal Mahal (Water Palace)", "nature", 0.00, 4.4),
    ],
    ("Udaipur", "India"): [
        ("City Palace Udaipur", "palace", 300.00, 4.9),
        ("Lake Pichola Boat Ride", "nature", 400.00, 4.8),
        ("Saheliyon-ki-Bari (Courtyard of Maidens)", "garden", 50.00, 4.4),
        ("Jag Mandir Island Palace", "heritage", 350.00, 4.7),
        ("Bagore Ki Haveli & Folk Dance", "cultural", 100.00, 4.7),
        ("Monsoon Palace (Sajjangarh Fort)", "viewpoint", 100.00, 4.5),
    ],
    ("Goa", "India"): [
        ("Aguada Fort & Lighthouse", "fort", 50.00, 4.5),
        ("Basilica of Bom Jesus", "heritage", 0.00, 4.8),
        ("Dudhsagar Waterfalls", "waterfall", 400.00, 4.7),
        ("Anjuna Beach & Flea Market", "beach", 0.00, 4.4),
        ("Chapora Fort", "fort", 0.00, 4.4),
        ("Palolem Beach", "beach", 0.00, 4.7),
    ],
    ("Agra", "India"): [
        ("Taj Mahal", "monument", 250.00, 4.9),
        ("Agra Fort", "heritage", 50.00, 4.7),
        ("Fatehpur Sikri Royal Complex", "historical", 50.00, 4.6),
        ("Mehtab Bagh Riverfront Gardens", "garden", 50.00, 4.5),
        ("Tomb of I'timad-ud-Daulah (Baby Taj)", "heritage", 50.00, 4.5),
    ],
    ("Varanasi", "India"): [
        ("Dashashwamedh Ghat Ganga Aarti", "religious", 0.00, 4.9),
        ("Kashi Vishwanath Jyotirlinga Temple", "temple", 0.00, 4.8),
        ("Assi Ghat Morning Subah-e-Banaras", "cultural", 0.00, 4.7),
        ("Sarnath Buddhist Monastic Complex", "historical", 25.00, 4.6),
        ("Manikarnika Ghat & Heritage Walk", "cultural", 0.00, 4.5),
    ],
    ("Bengaluru", "India"): [
        ("Lalbagh Botanical Garden & Glass House", "garden", 30.00, 4.6),
        ("Cubbon Park", "nature", 0.00, 4.5),
        ("Bengaluru Palace", "palace", 250.00, 4.3),
        ("Bannerghatta National Park & Safari", "wildlife", 350.00, 4.4),
        ("National Gallery of Modern Art (NGMA)", "museum", 50.00, 4.6),
    ],
    ("Mumbai", "India"): [
        ("Gateway of India & Apollo Bunder", "monument", 0.00, 4.7),
        ("Elephanta Caves Island", "heritage", 250.00, 4.6),
        ("Marine Drive Queen's Necklace", "viewpoint", 0.00, 4.8),
        ("Chhatrapati Shivaji Maharaj Vastu Sangrahalaya (CSMVS Museum)", "museum", 150.00, 4.7),
        ("Sanjay Gandhi National Park & Kanheri Caves", "nature", 100.00, 4.5),
        ("Bandra Bandstand & Fort Promenade", "viewpoint", 0.00, 4.4),
    ],
    ("Delhi", "India"): [
        ("Qutub Minar & Mehrauli Archaeological Park", "monument", 50.00, 4.7),
        ("Red Fort (Lal Qila)", "fort", 50.00, 4.6),
        ("Humayun's Tomb", "heritage", 50.00, 4.8),
        ("India Gate & Kartavya Path", "monument", 0.00, 4.7),
        ("Swaminarayan Akshardham Temple", "temple", 0.00, 4.8),
        ("Lotus Temple (Bahai House of Worship)", "architecture", 0.00, 4.6),
    ],
    ("Kolkata", "India"): [
        ("Victoria Memorial Hall & Gardens", "monument", 50.00, 4.8),
        ("Howrah Bridge", "monument", 0.00, 4.7),
        ("Dakshineswar Kali Temple", "temple", 0.00, 4.8),
        ("Indian Museum Kolkata", "museum", 50.00, 4.5),
        ("Park Street Cultural & Dining Promenade", "cultural", 0.00, 4.6),
    ],
    ("Chennai", "India"): [
        ("Kapaleeshwarar Temple Mylapore", "temple", 0.00, 4.8),
        ("Marina Beach Promenade", "beach", 0.00, 4.5),
        ("Fort St. George & Museum", "historical", 25.00, 4.3),
        ("San Thome Cathedral Basilica", "heritage", 0.00, 4.6),
        ("Government Museum Egmore", "museum", 50.00, 4.4),
    ],
    ("Hyderabad", "India"): [
        ("Charminar Monument & Laad Bazaar", "monument", 25.00, 4.6),
        ("Golconda Fort & Sound-Light Show", "fort", 50.00, 4.7),
        ("Salar Jung Museum", "museum", 50.00, 4.7),
        ("Chowmahalla Palace", "palace", 100.00, 4.7),
        ("Hussain Sagar Lake & Buddha Statue", "nature", 100.00, 4.4),
    ],
    ("Amritsar", "India"): [
        ("Sri Harmandir Sahib (Golden Temple)", "religious", 0.00, 5.0),
        ("Jallianwala Bagh Memorial", "historical", 0.00, 4.6),
        ("Wagah Border Beating Retreat Ceremony", "cultural", 0.00, 4.9),
        ("Partition Museum Town Hall", "museum", 10.00, 4.7),
        ("Gobindgarh Fort", "fort", 150.00, 4.5),
    ],
    ("Rishikesh", "India"): [
        ("Lakshman Jhula & Ram Jhula", "viewpoint", 0.00, 4.6),
        ("Triveni Ghat Maha Aarti", "religious", 0.00, 4.8),
        ("The Beatles Ashram (Chaurasi Kutia)", "heritage", 150.00, 4.5),
        ("Shivpuri White Water River Rafting", "adventure", 800.00, 4.9),
        ("Neer Garh Waterfall Trek", "waterfall", 30.00, 4.4),
    ],
    ("Haridwar", "India"): [
        ("Har Ki Pauri Evening Ganga Aarti", "religious", 0.00, 4.9),
        ("Mansa Devi Temple Ropeway", "temple", 150.00, 4.5),
        ("Chandi Devi Temple", "temple", 150.00, 4.5),
        ("Maya Devi Temple", "temple", 0.00, 4.4),
        ("Rajaji National Park Chilla Range", "wildlife", 300.00, 4.6),
    ],
    ("Shimla", "India"): [
        ("The Ridge & Mall Road", "viewpoint", 0.00, 4.6),
        ("Jakhoo Hill & Hanuman Temple", "temple", 0.00, 4.5),
        ("Viceregal Lodge (IIAS)", "heritage", 100.00, 4.7),
        ("Kalka-Shimla Toy Train Heritage Ride", "adventure", 300.00, 4.8),
        ("Kufri Snow Point & Nature Park", "nature", 50.00, 4.2),
    ],
    ("Manali", "India"): [
        ("Solang Valley Adventure & Snow Park", "adventure", 0.00, 4.7),
        ("Hadimba Devi Ancient Wooden Temple", "temple", 30.00, 4.6),
        ("Rohtang Pass Snow Viewpoint", "viewpoint", 500.00, 4.8),
        ("Old Manali Village & Cafes", "cultural", 0.00, 4.5),
        ("Jogini Waterfall Trek", "waterfall", 0.00, 4.7),
    ],
    ("Dharamshala", "India"): [
        ("Tsuglagkhang Complex (Dalai Lama Temple)", "religious", 0.00, 4.8),
        ("Triund Hill Trek", "adventure", 0.00, 4.9),
        ("Bhagsunag Waterfall & Temple", "waterfall", 0.00, 4.4),
        ("Namgyal Monastery", "cultural", 0.00, 4.7),
        ("Norbulingka Tibetan Cultural Institute", "cultural", 100.00, 4.8),
    ],
    ("Leh", "India"): [
        ("Pangong Tso High Altitude Lake", "nature", 0.00, 5.0),
        ("Nubra Valley & Hunder Sand Dunes", "nature", 0.00, 4.9),
        ("Thiksey Monastery", "religious", 50.00, 4.8),
        ("Shanti Stupa Sunrise Point", "viewpoint", 0.00, 4.7),
        ("Leh Royal Palace", "palace", 50.00, 4.4),
    ],
    ("Srinagar", "India"): [
        ("Dal Lake Shikara Cruise & Floating Market", "nature", 500.00, 4.9),
        ("Mughal Gardens (Nishat & Shalimar Bagh)", "garden", 50.00, 4.7),
        ("Shankaracharya Hill Temple", "temple", 0.00, 4.6),
        ("Hazratbal Shrine", "religious", 0.00, 4.7),
        ("Pari Mahal (Palace of Fairies)", "viewpoint", 50.00, 4.6),
    ],
    ("Gulmarg", "India"): [
        ("Gulmarg Gondola Phase 1 & 2", "adventure", 1800.00, 4.9),
        ("Apharwat Peak Snowfield", "viewpoint", 0.00, 4.8),
        ("Gulmarg Golf Course Meadows", "nature", 0.00, 4.5),
        ("St. Mary's Historic Church", "heritage", 0.00, 4.3),
        ("Strawberry Valley", "nature", 0.00, 4.4),
    ],
    ("Pahalgam", "India"): [
        ("Betaab Valley Pine Meadows", "nature", 100.00, 4.8),
        ("Aru Valley Trekking Base", "adventure", 50.00, 4.7),
        ("Baisaran Meadow (Mini Switzerland)", "nature", 0.00, 4.6),
        ("Lidder River White Water Rafting", "adventure", 600.00, 4.7),
        ("Chandanwari Amarnath Base", "nature", 0.00, 4.5),
    ],
    ("Jodhpur", "India"): [
        ("Mehrangarh Fort & Museum", "fort", 200.00, 4.9),
        ("Jaswant Thada Marble Cenotaph", "heritage", 50.00, 4.6),
        ("Umaid Bhawan Palace & Museum", "palace", 100.00, 4.6),
        ("Mandore Gardens & Royal Cenotaphs", "garden", 0.00, 4.4),
        ("Blue City Navchokiya Walking Tour", "cultural", 0.00, 4.7),
    ],
    ("Jaisalmer", "India"): [
        ("Jaisalmer Golden Sandstone Fort (Sonar Qila)", "fort", 50.00, 4.8),
        ("Sam Sand Dunes Camel Safari & Sunset", "adventure", 400.00, 4.8),
        ("Patwon Ki Haveli", "heritage", 100.00, 4.6),
        ("Gadisar Lake Boating & Cenotaphs", "nature", 50.00, 4.5),
        ("Kuldhara Abandoned Ghost Village", "historical", 50.00, 4.4),
    ],
    ("Pushkar", "India"): [
        ("Brahma Temple Pushkar", "temple", 0.00, 4.7),
        ("Pushkar Sacred Lake & 52 Ghats", "religious", 0.00, 4.6),
        ("Savitri Devi Hilltop Temple Ropeway", "viewpoint", 150.00, 4.6),
        ("Pushkar Desert Camel Safari", "adventure", 350.00, 4.5),
        ("Varaha Ancient Temple", "temple", 0.00, 4.4),
    ],
    ("Bikaner", "India"): [
        ("Junagarh Fort & Museum", "fort", 100.00, 4.7),
        ("Karni Mata Temple Deshnoke (Rat Temple)", "temple", 0.00, 4.5),
        ("National Research Centre on Camel", "wildlife", 50.00, 4.4),
        ("Lalgarh Palace", "palace", 50.00, 4.3),
        ("Rampuria Havelis Street Walk", "architecture", 0.00, 4.6),
    ],
    ("Mount Abu", "India"): [
        ("Dilwara Jain Marble Temples", "temple", 0.00, 4.9),
        ("Nakki Lake Boating & Toad Rock", "nature", 100.00, 4.5),
        ("Guru Shikhar Highest Peak", "viewpoint", 0.00, 4.6),
        ("Sunset Point Mount Abu", "viewpoint", 0.00, 4.3),
        ("Achalgarh Fort & Temple", "fort", 0.00, 4.4),
    ],
    ("Kumbhalgarh", "India"): [
        ("Kumbhalgarh Fort Great Wall", "fort", 40.00, 4.9),
        ("Badal Mahal (Cloud Palace)", "palace", 0.00, 4.7),
        ("Kumbhalgarh Wildlife Sanctuary", "wildlife", 150.00, 4.5),
        ("Neelkanth Mahadev Temple", "temple", 0.00, 4.6),
        ("Mammadev Temple & Kund", "heritage", 0.00, 4.4),
    ],
    ("Mandu", "India"): [
        ("Jahaz Mahal (Ship Palace)", "palace", 25.00, 4.7),
        ("Rani Roopmati Pavilion & Narmada View", "viewpoint", 25.00, 4.8),
        ("Baz Bahadur's Palace", "palace", 25.00, 4.5),
        ("Hindola Mahal (Swinging Palace)", "architecture", 25.00, 4.4),
        ("Hoshang Shah's Marble Tomb", "monument", 25.00, 4.5),
    ],
    ("Hampi", "India"): [
        ("Virupaksha Ancient Temple", "temple", 25.00, 4.9),
        ("Vijaya Vittala Temple & Stone Chariot", "heritage", 40.00, 5.0),
        ("Lotus Mahal & Elephant Stables", "palace", 40.00, 4.7),
        ("Matanga Hill Sunrise Trek", "viewpoint", 0.00, 4.9),
        ("Hemakuta Hill Boulder Temples", "heritage", 0.00, 4.8),
    ],
    ("Badami", "India"): [
        ("Badami Rock-Cut Cave Temples", "heritage", 40.00, 4.8),
        ("Agastya Lake & Bhootnath Temples", "heritage", 0.00, 4.8),
        ("Badami North Fort & Cannon Point", "fort", 25.00, 4.6),
        ("Archaeological Museum Badami", "museum", 20.00, 4.3),
        ("Pattadakal UNESCO Temple Complex", "heritage", 40.00, 4.9),
    ],
    ("Belur", "India"): [
        ("Chennakeshava Temple Belur", "temple", 0.00, 4.9),
        ("Kappe Chennigaraya Temple", "temple", 0.00, 4.6),
        ("Halebidu Hoysaleshwara Temple", "heritage", 40.00, 4.9),
        ("Yagachi Dam & Water Sports", "nature", 50.00, 4.3),
        ("Belur Temple Heritage Courtyard", "cultural", 0.00, 4.5),
    ],
    ("Murudeshwar", "India"): [
        ("Murudeshwar Shiva Statue & Gopuram Lift", "temple", 50.00, 4.8),
        ("Murudeshwar Beach & Arabian Sea", "beach", 0.00, 4.5),
        ("Murudeshwar Sea Fortress Ruins", "fort", 0.00, 4.2),
        ("Netrani Island Scuba Diving", "adventure", 2500.00, 4.9),
        ("Bhatkal Historic Light House", "viewpoint", 20.00, 4.4),
    ],
    ("Gokarna", "India"): [
        ("Om Beach & Coastal Cliff Trail", "beach", 0.00, 4.8),
        ("Mahabaleshwar Shiva Temple", "temple", 0.00, 4.7),
        ("Kudle Beach Sunset Point", "beach", 0.00, 4.7),
        ("Half Moon Beach & Paradise Beach Trek", "adventure", 0.00, 4.8),
        ("Yana Rocks Geological Caves", "nature", 30.00, 4.6),
    ],
    ("Coorg", "India"): [
        ("Abbey Falls & Coffee Estate Walk", "waterfall", 50.00, 4.6),
        ("Namdroling Monastery (Golden Temple Bylakuppe)", "religious", 0.00, 4.8),
        ("Raja's Seat Sunset Garden", "viewpoint", 25.00, 4.5),
        ("Tadiandamol Peak Trek", "adventure", 0.00, 4.8),
        ("Dubare Elephant Camp & River Rafting", "wildlife", 150.00, 4.4),
    ],
    ("Chikmagalur", "India"): [
        ("Mullayanagiri Highest Peak Trek", "adventure", 0.00, 4.9),
        ("Baba Budangiri & Dattatreya Peetha", "heritage", 0.00, 4.6),
        ("Hebbe Falls & Jeep Safari", "waterfall", 400.00, 4.7),
        ("Coffee Museum Chikmagalur", "museum", 30.00, 4.3),
        ("Z Point Kemmanagundi", "viewpoint", 0.00, 4.6),
    ],
    ("Kabini", "India"): [
        ("Nagarhole National Park Boat Safari", "wildlife", 750.00, 4.9),
        ("Kabini River Coracle Ride", "nature", 300.00, 4.7),
        ("Jungle Tiger Jeep Safari", "wildlife", 1200.00, 4.9),
        ("Kabini Dam Viewpoint", "viewpoint", 0.00, 4.3),
        ("Kuruva Island Bamboo Rafting", "nature", 150.00, 4.5),
    ],
    ("Bandipur", "India"): [
        ("Bandipur Tiger Reserve Safari", "wildlife", 500.00, 4.8),
        ("Himavad Gopalaswamy Betta Peak", "temple", 100.00, 4.7),
        ("Mudumalai Sanctuary Border Trail", "wildlife", 300.00, 4.6),
        ("Bandipur Elephant Camp", "wildlife", 50.00, 4.4),
        ("Moyar River Gorge Viewpoint", "viewpoint", 0.00, 4.5),
    ],
    ("Munnar", "India"): [
        ("Eravikulam National Park (Nilgiri Tahr)", "wildlife", 200.00, 4.8),
        ("Tata Tea Museum & Factory Tour", "museum", 125.00, 4.5),
        ("Mattupetty Dam & Speedboating", "nature", 50.00, 4.4),
        ("Top Station Valley Viewpoint", "viewpoint", 25.00, 4.6),
        ("Anamudi Peak Base & Echo Point", "nature", 30.00, 4.3),
    ],
    ("Alleppey", "India"): [
        ("Vembanad Lake Backwater Houseboat Cruise", "nature", 1500.00, 4.9),
        ("Alappuzha Lighthouse & Museum", "viewpoint", 40.00, 4.4),
        ("Marari Beach & Coconut Palms", "beach", 0.00, 4.7),
        ("Pathiramanal Bird Island", "nature", 0.00, 4.5),
        ("Revi Karunakaran Memorial Museum", "museum", 150.00, 4.3),
    ],
    ("Wayanad", "India"): [
        ("Edakkal Prehistoric Rock Caves", "historical", 50.00, 4.7),
        ("Banasura Sagar Earth Dam & Boating", "nature", 50.00, 4.6),
        ("Chembra Peak Heart-Shaped Lake Trek", "adventure", 750.00, 4.8),
        ("Soochipara Waterfalls", "waterfall", 80.00, 4.5),
        ("Muthanga Wildlife Sanctuary Safari", "wildlife", 300.00, 4.5),
    ],
    ("Varkala", "India"): [
        ("Varkala North Cliff & Arabian Sea Beach", "beach", 0.00, 4.9),
        ("Janardhana Swami 2000-Year Temple", "temple", 0.00, 4.7),
        ("Kappil Beach & Edava Nadayara Backwaters", "nature", 0.00, 4.6),
        ("Anjengo (Anchuthengu) Fort & Lighthouse", "fort", 20.00, 4.4),
        ("Sivagiri Mutt Spiritual Hermitage", "religious", 0.00, 4.5),
    ],
    ("Kovalam", "India"): [
        ("Lighthouse Beach Kovalam", "beach", 0.00, 4.7),
        ("Vizhinjam Marine Aquarium & Rock Cave", "wildlife", 30.00, 4.3),
        ("Hawa Beach & Samudra Beach", "beach", 0.00, 4.5),
        ("Halcyon Castle (Kovalam Palace)", "heritage", 50.00, 4.2),
        ("Kovalam Ayurvedic Healing Center", "cultural", 500.00, 4.6),
    ],
    ("Thekkady", "India"): [
        ("Periyar Lake Wildlife Boat Safari", "wildlife", 250.00, 4.8),
        ("Periyar Tiger Trail Bamboo Rafting", "adventure", 1500.00, 4.9),
        ("Abraham's Spice Garden Tour", "nature", 100.00, 4.6),
        ("Kadathanadan Kalari Centre (Martial Arts)", "cultural", 300.00, 4.8),
        ("Chellarkovil Eco Viewpoint", "viewpoint", 30.00, 4.4),
    ],
    ("Kumarakom", "India"): [
        ("Kumarakom Bird Sanctuary", "wildlife", 50.00, 4.6),
        ("Vembanad Lake Sunset Cruise", "nature", 400.00, 4.8),
        ("Bay Island Driftwood Museum", "museum", 50.00, 4.4),
        ("Aruvikkuzhi Waterfalls", "waterfall", 0.00, 4.3),
        ("Thazhathangady Juma Masjid (1000-Year Mosque)", "heritage", 0.00, 4.6),
    ],
    ("Ooty", "India"): [
        ("Ooty Botanical Gardens", "garden", 50.00, 4.6),
        ("Doddabetta Peak Highest Viewpoint", "viewpoint", 20.00, 4.7),
        ("Nilgiri Mountain Railway (Toy Train)", "adventure", 200.00, 4.9),
        ("Pykara Lake & Waterfalls Boating", "nature", 150.00, 4.5),
        ("Ooty Rose Garden", "garden", 40.00, 4.4),
    ],
    ("Kodaikanal", "India"): [
        ("Kodaikanal Star Lake & Cycling", "nature", 50.00, 4.7),
        ("Coaker's Walk Misty Promenade", "viewpoint", 30.00, 4.6),
        ("Pillar Rocks Valley View", "viewpoint", 20.00, 4.5),
        ("Bryant Park Botanical Garden", "garden", 30.00, 4.3),
        ("Silver Cascade Waterfall", "waterfall", 0.00, 4.2),
    ],
    ("Madurai", "India"): [
        ("Meenakshi Amman Grand Temple", "temple", 0.00, 5.0),
        ("Thirumalai Nayakkar Palace", "palace", 50.00, 4.6),
        ("Gandhi Memorial Museum Madurai", "museum", 0.00, 4.5),
        ("Vandiyur Mariamman Teppakulam", "religious", 0.00, 4.4),
        ("Alagar Kovil Hill Temple", "temple", 0.00, 4.6),
    ],
    ("Rameswaram", "India"): [
        ("Ramanathaswamy Temple Corridors & 22 Theerthams", "temple", 0.00, 4.9),
        ("Pamban Sea Bridge & Railway Viewpoint", "monument", 0.00, 4.9),
        ("Dr. A.P.J. Abdul Kalam National Memorial", "museum", 0.00, 4.8),
        ("Agnitheertham Sacred Beach", "religious", 0.00, 4.5),
        ("Gandhamadhana Parvatham Viewpoint", "viewpoint", 0.00, 4.4),
    ],
    ("Dhanushkodi", "India"): [
        ("Dhanushkodi Ghost Town Ruins & Church", "historical", 0.00, 4.8),
        ("Arichal Munai (Land's End Ram Setu Point)", "viewpoint", 0.00, 4.9),
        ("Dhanushkodi Beach Confluence", "beach", 0.00, 4.7),
        ("Kothandaramaswamy Temple", "temple", 0.00, 4.5),
        ("Ram Setu (Adam's Bridge) Ocean Reefs", "nature", 0.00, 4.8),
    ],
    ("Kanyakumari", "India"): [
        ("Vivekananda Rock Memorial Ferry", "monument", 100.00, 4.9),
        ("Thiruvalluvar 133-Ft Statue", "monument", 0.00, 4.8),
        ("Sunset & Sunrise Triveni Sangam Point", "viewpoint", 0.00, 4.8),
        ("Our Lady of Ransom Church", "architecture", 0.00, 4.5),
        ("Padmanabhapuram Wooden Palace", "palace", 50.00, 4.7),
    ],
    ("Pondicherry", "India"): [
        ("Promenade Beach & French War Memorial", "beach", 0.00, 4.7),
        ("Sri Aurobindo Ashram", "religious", 0.00, 4.8),
        ("Auroville Matrimandir Dome & Gardens", "cultural", 0.00, 4.9),
        ("French Quarter (White Town) Heritage Walk", "architecture", 0.00, 4.7),
        ("Paradise Beach & Chunnambar Boat House", "beach", 250.00, 4.5),
    ],
    ("Thanjavur", "India"): [
        ("Brihadisvara Temple (Big Temple)", "temple", 0.00, 5.0),
        ("Thanjavur Royal Palace & Art Gallery", "palace", 50.00, 4.6),
        ("Saraswathi Mahal Ancient Manuscript Library", "museum", 30.00, 4.7),
        ("Schwartz Church", "historical", 0.00, 4.3),
        ("Siva Ganga Garden & Tank", "garden", 10.00, 4.2),
    ],
    ("Mahabalipuram", "India"): [
        ("Shore Temple on Coromandel Coast", "heritage", 40.00, 4.9),
        ("Pancha Rathas (Five Chariots)", "heritage", 40.00, 4.8),
        ("Arjuna's Penance Rock Relief", "heritage", 0.00, 4.7),
        ("Krishna's Butterball Balanced Rock", "nature", 0.00, 4.6),
        ("Mahabalipuram Lighthouse & Maritime Museum", "viewpoint", 20.00, 4.5),
    ],
    ("Coimbatore", "India"): [
        ("Adiyogi Shiva 112-Ft Statue & Isha Centre", "monument", 0.00, 4.9),
        ("Marudhamalai Hill Temple", "temple", 0.00, 4.7),
        ("Gass Forest Museum", "museum", 20.00, 4.3),
        ("Siruvani Waterfalls & Dam", "waterfall", 50.00, 4.6),
        ("Perur Pateeswarar Ancient Temple", "temple", 0.00, 4.6),
    ],
    ("Pune", "India"): [
        ("Shaniwar Wada Peshwa Palace Fort", "fort", 25.00, 4.5),
        ("Aga Khan Palace & Gandhi Memorial", "heritage", 25.00, 4.7),
        ("Sinhagad Hill Fort Trek", "fort", 50.00, 4.8),
        ("Dagdusheth Halwai Ganpati Temple", "temple", 0.00, 4.9),
        ("Raja Dinkar Kelkar Museum", "museum", 50.00, 4.6),
    ],
    ("Lonavala", "India"): [
        ("Tiger's Point (Tiger's Leap) Cliff", "viewpoint", 0.00, 4.7),
        ("Karla & Bhaja Rock-Cut Buddhist Caves", "heritage", 25.00, 4.6),
        ("Bhushi Dam Waterfall Cascades", "waterfall", 0.00, 4.2),
        ("Lohagad Hill Fort Trek", "fort", 20.00, 4.8),
        ("Pawna Lake Camping & Boating", "nature", 300.00, 4.7),
    ],
    ("Mahabaleshwar", "India"): [
        ("Arthur's Seat Queen of Points", "viewpoint", 0.00, 4.8),
        ("Venna Lake Boating & Horse Riding", "nature", 150.00, 4.5),
        ("Mapro Garden Strawberry Experience", "garden", 0.00, 4.6),
        ("Pratapgad Chhatrapati Shivaji Fort", "fort", 0.00, 4.8),
        ("Old Mahabaleshwar Temple & Panchganga", "temple", 0.00, 4.6),
    ],
    ("Alibaug", "India"): [
        ("Kolaba Sea Fort & Low Tide Walk", "fort", 20.00, 4.6),
        ("Nagaon Beach & Water Sports", "beach", 0.00, 4.5),
        ("Kashid White Sand Beach", "beach", 0.00, 4.7),
        ("Murud Janjira Unconquered Sea Fort", "fort", 50.00, 4.8),
        ("Kanakeshwar Hill Forest Temple Trek", "nature", 0.00, 4.4),
    ],
    ("Nashik", "India"): [
        ("Sula Vineyards Winery Tour & Tasting", "cultural", 400.00, 4.8),
        ("Trimbakeshwar Jyotirlinga Temple", "temple", 0.00, 4.8),
        ("Panchavati Ghats & Sita Gufa", "religious", 0.00, 4.6),
        ("Pandavleni Rock-Cut Buddhist Caves", "heritage", 25.00, 4.5),
        ("Anjaneri Hill (Birthplace of Hanuman) Trek", "adventure", 0.00, 4.7),
    ],
    ("Aurangabad", "India"): [
        ("Ellora Caves Kailasa Monolithic Temple", "heritage", 40.00, 5.0),
        ("Ajanta Caves Ancient Buddhist Murals", "heritage", 40.00, 5.0),
        ("Bibi Ka Maqbara (Taj of Deccan)", "monument", 25.00, 4.6),
        ("Daulatabad Fort & Chand Minar", "fort", 25.00, 4.7),
        ("Aurangabad Rock Caves & Viewpoint", "heritage", 25.00, 4.3),
    ],
    ("Nagpur", "India"): [
        ("Deekshabhoomi Sacred Stupa", "monument", 0.00, 4.8),
        ("Futala Lake Musical Fountains", "nature", 0.00, 4.4),
        ("Sitabuldi Fort", "fort", 0.00, 4.3),
        ("Zero Mile Stone Historic Marker", "historical", 0.00, 4.2),
        ("Krazy Castle Aqua Park", "park", 350.00, 4.3),
    ],
    ("Tadoba", "India"): [
        ("Tadoba-Andhari Tiger Reserve Safari", "wildlife", 600.00, 4.9),
        ("Tadoba Lake Crocodile Viewpoint", "wildlife", 0.00, 4.6),
        ("Moharli Forest Gate Nature Walk", "nature", 100.00, 4.4),
        ("Erai Dam Scenic Water Reservoir", "nature", 0.00, 4.3),
        ("Kolsa Range Jungle Trail", "wildlife", 500.00, 4.7),
    ],
    ("Shirdi", "India"): [
        ("Sai Baba Samadhi Temple Complex", "religious", 0.00, 4.9),
        ("Dwarkamai Sacred Mosque", "religious", 0.00, 4.8),
        ("Chavadi Historic Hall", "religious", 0.00, 4.6),
        ("Sai Heritage Village Theme Park", "cultural", 150.00, 4.4),
        ("Shani Shingnapur Holy Village", "temple", 0.00, 4.7),
    ],
    ("Darjeeling", "India"): [
        ("Tiger Hill Kanchenjunga Sunrise", "viewpoint", 50.00, 4.9),
        ("Batasia Loop & Gorkha War Memorial", "viewpoint", 20.00, 4.7),
        ("Darjeeling Himalayan Railway Heritage Ride", "adventure", 400.00, 4.9),
        ("Happy Valley Tea Estate Tour", "garden", 100.00, 4.6),
        ("Padmaja Naidu Himalayan Zoological Park", "wildlife", 110.00, 4.7),
    ],
    ("Kalimpong", "India"): [
        ("Zang Dhok Palri Phodang Monastery", "religious", 0.00, 4.7),
        ("Deolo Hill Panoramic Park", "viewpoint", 20.00, 4.8),
        ("Morgan House Colonial Heritage Estate", "heritage", 0.00, 4.5),
        ("Pine View Cactus Nursery", "garden", 20.00, 4.4),
        ("Crockety Historic Bungalow", "architecture", 0.00, 4.3),
    ],
    ("Sundarbans", "India"): [
        ("Sundarbans Mangrove Boat Safari", "wildlife", 500.00, 4.8),
        ("Sajnekhali Watch Tower & Museum", "wildlife", 50.00, 4.6),
        ("Dobanki Canopy Walkway", "nature", 50.00, 4.7),
        ("Burir Dabri Mudflat Trail", "nature", 50.00, 4.5),
        ("Sudhanyakhali Tiger Watch Tower", "wildlife", 50.00, 4.7),
    ],
    ("Shantiniketan", "India"): [
        ("Visva-Bharati University Campus & Ashrama", "cultural", 0.00, 4.8),
        ("Rabindra Bhavana Tagore Museum", "museum", 50.00, 4.7),
        ("Kala Bhavana Art Studio & Murals", "cultural", 0.00, 4.6),
        ("Khowai Sonajhuri Haat Saturday Market", "market", 0.00, 4.9),
        ("Deer Park Ballavpur Sanctuary", "wildlife", 20.00, 4.3),
    ],
    ("Siliguri", "India"): [
        ("Coronation Bridge over Teesta River", "viewpoint", 0.00, 4.6),
        ("Mahananda Wildlife Sanctuary", "wildlife", 100.00, 4.5),
        ("ISCON Siliguri Sri Sri Radha Madhav Sundar Mandir", "temple", 0.00, 4.6),
        ("Salugara Buddhist Monastery", "religious", 0.00, 4.4),
        ("Bengal Safari Park", "wildlife", 300.00, 4.5),
    ],
    ("Gangtok", "India"): [
        ("Rumtek Monastery (Dharma Chakra Centre)", "religious", 20.00, 4.8),
        ("Tsomgo (Changu) Glacial Lake", "nature", 0.00, 4.9),
        ("Nathula Indo-China Mountain Pass", "viewpoint", 200.00, 4.9),
        ("Enchey 200-Year Buddhist Monastery", "temple", 0.00, 4.6),
        ("MG Marg Pedestrian Promenade", "cultural", 0.00, 4.7),
    ],
    ("Pelling", "India"): [
        ("Pelling Skywalk & Chenrezig Statue", "viewpoint", 50.00, 4.8),
        ("Pemayangtse Ancient Monastery", "religious", 20.00, 4.7),
        ("Rabdentse Ruins Historic Capital", "historical", 20.00, 4.6),
        ("Kanchenjunga Falls & Rimbi River", "waterfall", 20.00, 4.5),
        ("Khecheopalri Sacred Wishing Lake", "religious", 0.00, 4.7),
    ],
    ("Lachung", "India"): [
        ("Yumthang Valley of Flowers", "nature", 0.00, 4.9),
        ("Zero Point (Yumesamdong) Snowfields", "viewpoint", 0.00, 5.0),
        ("Lachung Monastery", "religious", 0.00, 4.6),
        ("Cottage Industry Handicraft Centre", "cultural", 0.00, 4.3),
        ("Singba Rhododendron Sanctuary", "nature", 0.00, 4.7),
    ],
    ("Guwahati", "India"): [
        ("Kamakhya Devi Tantric Temple", "temple", 0.00, 4.9),
        ("Umananda Peacock Island Shiva Temple", "temple", 20.00, 4.6),
        ("Brahmaputra River Sunset Cruise", "nature", 400.00, 4.7),
        ("Assam State Museum", "museum", 20.00, 4.4),
        ("Srimanta Sankaradeva Kalakshetra", "cultural", 50.00, 4.7),
    ],
    ("Kaziranga", "India"): [
        ("Kaziranga National Park Rhino Elephant Safari", "wildlife", 750.00, 5.0),
        ("Kaziranga Central Range Jeep Safari", "wildlife", 600.00, 4.9),
        ("Kaziranga National Orchid & Biodiversity Park", "garden", 100.00, 4.6),
        ("Kakochang Waterfalls Trek", "waterfall", 0.00, 4.4),
        ("Hathikuli Tea Estate Walk", "nature", 0.00, 4.5),
    ],
    ("Manas", "India"): [
        ("Manas National Park Jungle Jeep Safari", "wildlife", 500.00, 4.8),
        ("Manas River Boat Safari", "wildlife", 600.00, 4.7),
        ("Bansbari Grassland Wildlife Viewpoint", "nature", 0.00, 4.6),
        ("Mathanguri Royal Forest Rest House Trail", "viewpoint", 0.00, 4.8),
        ("Bodo Tribal Cultural Village Tour", "cultural", 200.00, 4.6),
    ],
    ("Majuli", "India"): [
        ("Kamalabari Satra Vaishnavite Monastery", "cultural", 0.00, 4.8),
        ("Samaguri Satra Traditional Mask Making", "cultural", 0.00, 4.9),
        ("Auniati Satra & Museum of Relics", "museum", 0.00, 4.7),
        ("Brahmaputra River Sandbar Sunset", "nature", 0.00, 4.7),
        ("Mishing Indigenous Tribal Village", "cultural", 0.00, 4.6),
    ],
    ("Shillong", "India"): [
        ("Elephant Falls Three-Tier Cascades", "waterfall", 20.00, 4.6),
        ("Umiam Lake Boating & Water Sports", "nature", 100.00, 4.7),
        ("Don Bosco Museum of Indigenous Cultures", "museum", 100.00, 4.8),
        ("Shillong Peak Glass Viewpoint", "viewpoint", 30.00, 4.5),
        ("Laitlum Canyons Gorge Panorama", "viewpoint", 0.00, 4.9),
    ],
    ("Cherrapunji", "India"): [
        ("Nongriat Double Decker Living Root Bridge", "nature", 0.00, 5.0),
        ("Nohkalikai Falls (India's Tallest Plunge)", "waterfall", 20.00, 4.9),
        ("Mawsmai Limestone Caves", "adventure", 20.00, 4.6),
        ("Seven Sisters Falls (Nohsngithiang)", "waterfall", 0.00, 4.7),
        ("Dainthlen Falls & Legend Gorge", "nature", 0.00, 4.5),
    ],
    ("Dawki", "India"): [
        ("Umngot River Crystal Clear Boat Ride", "nature", 500.00, 4.9),
        ("Jaflong Zero Point Border View", "viewpoint", 0.00, 4.4),
        ("Dawki Suspension Bridge (1932)", "monument", 0.00, 4.5),
        ("Shnongpdeng Riverside Camping & Kayaking", "adventure", 200.00, 4.8),
        ("Bophill Falls", "waterfall", 0.00, 4.3),
    ],
    ("Tawang", "India"): [
        ("Tawang Monastery (Galden Namgey Lhatse)", "religious", 20.00, 5.0),
        ("Sela Pass & Sela Lake (13,700 ft)", "viewpoint", 0.00, 5.0),
        ("Madhuri Lake (Sangetsar Tso)", "nature", 0.00, 4.9),
        ("Nuranang (Jang) Waterfall", "waterfall", 0.00, 4.8),
        ("Tawang War Memorial", "monument", 0.00, 4.7),
    ],
    ("Ziro", "India"): [
        ("Ziro Valley Paddy & Fish Cultivation Fields", "nature", 0.00, 4.9),
        ("Hong Apatani Tribal Village", "cultural", 0.00, 4.8),
        ("Talle Valley Wildlife Sanctuary Trek", "wildlife", 50.00, 4.7),
        ("Meghna Cave Temple", "temple", 0.00, 4.4),
        ("Kardo Shiva Lingam Monolith", "religious", 0.00, 4.5),
    ],
    ("Kohima", "India"): [
        ("Kohima War Cemetery WWII Memorial", "monument", 0.00, 4.8),
        ("Kisama Naga Heritage Village (Hornbill Venue)", "cultural", 50.00, 4.9),
        ("Dzukou Valley Trek & Flower Meadows", "adventure", 100.00, 5.0),
        ("Kohima Cathedral of Reconciliation", "architecture", 0.00, 4.7),
        ("Nagaland State Museum", "museum", 20.00, 4.4),
    ],
    ("Imphal", "India"): [
        ("Kangla Fort & Royal Palace Complex", "fort", 20.00, 4.7),
        ("Loktak Lake Floating Phumdis & Boating", "nature", 200.00, 4.9),
        ("Keibul Lamjao National Park (Sangai Deer)", "wildlife", 50.00, 4.8),
        ("Ima Keithel (Mothers' All-Women Market)", "market", 0.00, 4.8),
        ("INA Memorial & Museum Moirang", "historical", 10.00, 4.6),
    ],
    ("Aizawl", "India"): [
        ("Solomon's Temple Aizawl", "religious", 0.00, 4.7),
        ("Durtlang Hills Skyline Viewpoint", "viewpoint", 0.00, 4.6),
        ("Mizoram State Museum", "museum", 20.00, 4.4),
        ("Reiek Heritage Village & Mountain Peak Trek", "adventure", 0.00, 4.8),
        ("Bara Bazar Traditional Mizo Market", "market", 0.00, 4.5),
    ],
    ("Agartala", "India"): [
        ("Ujjayanta Palace & State Museum", "palace", 20.00, 4.8),
        ("Neermahal Water Palace on Rudrasagar Lake", "palace", 50.00, 4.7),
        ("Tripura Sundari Temple Udaipur (Matabari)", "temple", 0.00, 4.8),
        ("Unakoti Ancient Rock Carvings", "heritage", 0.00, 4.9),
        ("Sepahijala Wildlife Sanctuary", "wildlife", 30.00, 4.5),
    ],
    ("Puri", "India"): [
        ("Shree Jagannath Temple", "temple", 0.00, 4.9),
        ("Golden Beach Puri (Blue Flag Beach)", "beach", 20.00, 4.7),
        ("Swargadwar Beach Market", "market", 0.00, 4.4),
        ("Raghurajpur Heritage Craft Village", "cultural", 0.00, 4.8),
        ("Gundicha Temple", "temple", 0.00, 4.5),
    ],
    ("Bhubaneswar", "India"): [
        ("Lingaraj Ancient 11th-Century Temple", "temple", 0.00, 4.9),
        ("Udayagiri & Khandagiri Rock-Cut Caves", "historical", 25.00, 4.6),
        ("Mukteshwar Temple (Gem of Odishan Architecture)", "architecture", 0.00, 4.8),
        ("Nandankanan Zoological Park & White Tigers", "wildlife", 50.00, 4.7),
        ("Odisha State Museum", "museum", 20.00, 4.4),
    ],
    ("Konark", "India"): [
        ("Konark Sun Temple UNESCO Chariot", "heritage", 40.00, 5.0),
        ("Chandrabhaga Beach Sunset", "beach", 0.00, 4.6),
        ("Konark Archaeological Museum", "museum", 10.00, 4.4),
        ("Kuruma Buddhist Archaeological Site", "historical", 0.00, 4.2),
        ("Ramchandi Temple & River Confluence", "nature", 0.00, 4.5),
    ],
    ("Chilika", "India"): [
        ("Satapada Irrawaddy Dolphin Boat Cruise", "wildlife", 600.00, 4.8),
        ("Nalabana Island Bird Sanctuary", "wildlife", 0.00, 4.7),
        ("Kalijai Temple Island in Lagoon", "temple", 100.00, 4.6),
        ("Barkul Boating Centre", "nature", 150.00, 4.4),
        ("Mangalajodi Eco-Tourism Birding Wetland", "wildlife", 400.00, 4.9),
    ],
    ("Ahmedabad", "India"): [
        ("Sabarmati Gandhi Ashram", "historical", 0.00, 4.9),
        ("Adalaj Stepwell (Vav)", "architecture", 0.00, 4.8),
        ("Sidi Saiyyed Mosque Jali Screen", "heritage", 0.00, 4.7),
        ("Kankaria Lake & Entertainment Hub", "nature", 25.00, 4.5),
        ("Calico Museum of Textiles", "museum", 0.00, 4.8),
    ],
    ("Kutch", "India"): [
        ("Great Rann of Kutch White Salt Desert", "nature", 100.00, 5.0),
        ("Kala Dungar (Black Hill) Highest Point", "viewpoint", 0.00, 4.7),
        ("Kutch Desert Wildlife Sanctuary & Flamingos", "wildlife", 100.00, 4.6),
        ("Dholavira Harappan Indus Valley City", "historical", 40.00, 4.9),
        ("Hodka Artisans Craft Village", "cultural", 0.00, 4.6),
    ],
    ("Bhuj", "India"): [
        ("Aina Mahal (Mirror Palace)", "palace", 30.00, 4.6),
        ("Prag Mahal Clock Tower & Durbar Hall", "palace", 40.00, 4.6),
        ("Kutch Museum (Oldest Museum in Gujarat)", "museum", 10.00, 4.4),
        ("Bhujodi Handloom Weaving Village", "cultural", 0.00, 4.8),
        ("Shree Swaminarayan Temple Bhuj", "temple", 0.00, 4.8),
    ],
    ("Gir", "India"): [
        ("Gir National Park Asiatic Lion Safari", "wildlife", 800.00, 4.9),
        ("Devalia Gir Safari Park (Interpretation Zone)", "wildlife", 250.00, 4.7),
        ("Kamleshwar Dam Crocodile Viewpoint", "wildlife", 0.00, 4.4),
        ("Kankai Mata Temple inside Forest", "religious", 0.00, 4.5),
        ("Jamjir Waterfalls", "waterfall", 0.00, 4.3),
    ],
    ("Dwarka", "India"): [
        ("Dwarkadhish Temple (Jagat Mandir)", "temple", 0.00, 4.9),
        ("Bet Dwarka Island Boat Excursion", "religious", 50.00, 4.7),
        ("Rukmini Devi Temple", "temple", 0.00, 4.5),
        ("Dwarka Lighthouse & Arabian Sunset", "viewpoint", 20.00, 4.5),
        ("Sudama Setu Suspension Bridge & Beach", "viewpoint", 20.00, 4.6),
    ],
    ("Somnath", "India"): [
        ("Somnath Temple & Arabian Sea Promenade", "temple", 0.00, 5.0),
        ("Bhalka Tirtha Sacred Site", "religious", 0.00, 4.6),
        ("Triveni Sangam Somnath", "religious", 0.00, 4.5),
        ("Somnath Sound & Light Evening Show", "cultural", 30.00, 4.7),
        ("Prabhas Patan Museum", "museum", 10.00, 4.3),
    ],
    ("Vadodara", "India"): [
        ("Laxmi Vilas Palace & Darbar Hall", "palace", 250.00, 4.9),
        ("Sayaji Baug (Kamati Baug) & Planetarium", "garden", 20.00, 4.6),
        ("Baroda Museum & Picture Gallery", "museum", 20.00, 4.5),
        ("Champaner-Pavagadh UNESCO Archaeological Park", "heritage", 40.00, 4.9),
        ("Kirti Mandir Vadodara", "monument", 0.00, 4.4),
    ],
    ("Surat", "India"): [
        ("Surat Castle (Old Fort on Tapi River)", "fort", 20.00, 4.4),
        ("Dumas Black Sand Beach", "beach", 0.00, 4.3),
        ("Dutch and Armenian Heritage Cemeteries", "historical", 0.00, 4.2),
        ("Sarthana Nature Park & Zoo", "wildlife", 30.00, 4.3),
        ("Gopi Talav Historic Urban Lake", "nature", 20.00, 4.4),
    ],
    ("Khajuraho", "India"): [
        ("Western Group of Temples (Kandariya Mahadeva)", "heritage", 40.00, 5.0),
        ("Eastern Group of Jain Temples (Parshvanatha)", "heritage", 0.00, 4.7),
        ("Khajuraho Sound and Light Show", "cultural", 250.00, 4.7),
        ("Raneh Falls Canyon & Granite Rock Formations", "waterfall", 100.00, 4.8),
        ("Archaeological Museum Khajuraho", "museum", 10.00, 4.4),
    ],
    ("Gwalior", "India"): [
        ("Gwalior Fort & Man Singh Palace", "fort", 25.00, 4.9),
        ("Jai Vilas Palace & Scindia Museum", "palace", 300.00, 4.7),
        ("Sas Bahu Ancient Twin Temples", "architecture", 25.00, 4.7),
        ("Teli Ka Mandir Dravidian Temple", "temple", 25.00, 4.6),
        ("Tomb of Tansen (Father of Hindustani Music)", "monument", 0.00, 4.5),
    ],
    ("Orchha", "India"): [
        ("Orchha Fort Complex (Raja Mahal & Jahangir Mahal)", "palace", 40.00, 4.9),
        ("Chaturbhuj Temple & Skyline View", "temple", 0.00, 4.8),
        ("Chhatris (Royal Cenotaphs) on Betwa River", "monument", 40.00, 4.8),
        ("Ram Raja Temple", "religious", 0.00, 4.7),
        ("Betwa River Kayaking & Sunset", "adventure", 300.00, 4.7),
    ],
    ("Bhopal", "India"): [
        ("Upper Lake (Bhojtal) Boating & Van Vihar", "nature", 50.00, 4.7),
        ("Taj-ul-Masajid (One of Asia's Largest Mosques)", "religious", 0.00, 4.8),
        ("Sanchi Stupa UNESCO Buddhist Heritage (Excursion)", "heritage", 40.00, 5.0),
        ("Bhimbetka Prehistoric Rock Shelters", "historical", 40.00, 4.9),
        ("National Museum of Mankind (Indira Gandhi Rashtriya Manav Sangrahalaya)", "museum", 50.00, 4.8),
    ],
    ("Indore", "India"): [
        ("Rajwada Palace 7-Story Historic Residence", "palace", 20.00, 4.6),
        ("Lal Bagh Palace & French Gardens", "palace", 20.00, 4.7),
        ("Sarafa Bazaar Midnight Street Food Market", "market", 0.00, 4.9),
        ("Kanch Mandir (Glass Temple)", "temple", 0.00, 4.5),
        ("Patalpani Waterfalls", "waterfall", 0.00, 4.4),
    ],
    ("Ujjain", "India"): [
        ("Mahakaleshwar Jyotirlinga & Bhasma Aarti", "temple", 0.00, 5.0),
        ("Mahakal Lok Grand Heritage Corridor", "cultural", 0.00, 4.9),
        ("Ram Ghat Sacred Kshipra River", "religious", 0.00, 4.7),
        ("Kal Bhairav Temple", "temple", 0.00, 4.6),
        ("Vedh Shala (Jantar Mantar Observatory)", "historical", 20.00, 4.4),
    ],
    ("Kanha", "India"): [
        ("Kanha Tiger Reserve Jungle Safari", "wildlife", 750.00, 5.0),
        ("Bamni Dadar (Sunset Point Kanha)", "viewpoint", 0.00, 4.8),
        ("Kanha Museum & Interpretation Centre", "museum", 50.00, 4.5),
        ("Mukki Zone Wildlife Trail", "wildlife", 600.00, 4.9),
        ("Shravan Tal Historic Wildlife Waterhole", "nature", 0.00, 4.6),
    ],
    ("Bandhavgarh", "India"): [
        ("Bandhavgarh Tiger Reserve Tala Safari", "wildlife", 750.00, 5.0),
        ("Bandhavgarh Ancient Hilltop Fort & Shesh Shaiya", "heritage", 0.00, 4.8),
        ("Magadhi Zone Wildlife Safari", "wildlife", 600.00, 4.8),
        ("Baghel Museum", "museum", 30.00, 4.2),
        ("Climbers Point Panoramic View", "viewpoint", 0.00, 4.5),
    ],
    ("Pench", "India"): [
        ("Pench Tiger Reserve (Mowgli Jungle Safari)", "wildlife", 600.00, 4.9),
        ("Turia Gate Safari Trail", "wildlife", 500.00, 4.8),
        ("Totladoh Dam & Water Reservoir Viewpoint", "nature", 0.00, 4.5),
        ("Kohka Lake Sunset Trail", "nature", 0.00, 4.6),
        ("Potters Village Pachdhar Handcrafted Pottery", "cultural", 0.00, 4.7),
    ],
    ("Lucknow", "India"): [
        ("Bara Imambara & Bhulbhulaiya Maze", "heritage", 50.00, 4.8),
        ("Chhota Imambara (Palace of Lights)", "heritage", 50.00, 4.7),
        ("Rumi Darwaza Turkish Gateway", "monument", 0.00, 4.7),
        ("The British Residency Memorial Ruins", "historical", 25.00, 4.6),
        ("Hazratganj Heritage Shopping Lane", "cultural", 0.00, 4.6),
    ],
    ("Mathura", "India"): [
        ("Shri Krishna Janmabhoomi Temple Complex", "temple", 0.00, 4.9),
        ("Dwarkadhish Historic Temple", "temple", 0.00, 4.7),
        ("Vishram Ghat Yamuna Aarti", "religious", 0.00, 4.6),
        ("Mathura Government Museum", "museum", 25.00, 4.4),
        ("Gita Mandir (Birla Temple)", "temple", 0.00, 4.5),
    ],
    ("Vrindavan", "India"): [
        ("Banke Bihari Temple", "temple", 0.00, 4.9),
        ("Prem Mandir White Marble Complex & Lights", "temple", 0.00, 5.0),
        ("ISKCON Vrindavan (Sri Krishna Balaram Mandir)", "temple", 0.00, 4.8),
        ("Nidhivan Sacred Grove", "religious", 0.00, 4.6),
        ("Radha Raman Ancient Temple", "temple", 0.00, 4.8),
    ],
    ("Ayodhya", "India"): [
        ("Shri Ram Janmabhoomi Mandir", "temple", 0.00, 5.0),
        ("Hanuman Garhi Hill Fortress Temple", "temple", 0.00, 4.8),
        ("Kanak Bhawan Royal Palace Temple", "palace", 0.00, 4.7),
        ("Sarayu River Ghats & Evening Aarti", "religious", 0.00, 4.8),
        ("Ram Ki Paedi Waterfront", "viewpoint", 0.00, 4.6),
    ],
    ("Prayagraj", "India"): [
        ("Triveni Sangam (Confluence of 3 Rivers)", "religious", 100.00, 4.9),
        ("Allahabad Fort & Akshaya Vat", "fort", 0.00, 4.6),
        ("Anand Bhavan (Nehru Ancestral Home Museum)", "museum", 50.00, 4.6),
        ("Khusro Bagh Mughal Mausoleums", "garden", 0.00, 4.5),
        ("All Saints Cathedral (Patthar Girja)", "architecture", 0.00, 4.5),
    ],
    ("Nainital", "India"): [
        ("Naini Lake Boating Promenade", "nature", 150.00, 4.7),
        ("Naina Devi Temple on Lake Bank", "temple", 0.00, 4.7),
        ("Snow View Point Ropeway", "viewpoint", 200.00, 4.6),
        ("Nainital Zoo (High Altitude Zoo)", "wildlife", 100.00, 4.5),
        ("Tiffin Top (Dorothy's Seat) Trek", "viewpoint", 0.00, 4.6),
    ],
    ("Mussoorie", "India"): [
        ("Kempty Falls Cascades", "waterfall", 50.00, 4.4),
        ("Gun Hill Cable Car Viewpoint", "viewpoint", 150.00, 4.5),
        ("Mall Road Mussoorie & Library Bazaar", "cultural", 0.00, 4.6),
        ("Camel's Back Road Scenic Walk", "nature", 0.00, 4.6),
        ("Company Garden & Waterfall", "garden", 25.00, 4.3),
    ],
    ("Almora", "India"): [
        ("Kasar Devi Hippie & Meditative Ridge", "religious", 0.00, 4.8),
        ("Bright End Corner Himalayan Sunset", "viewpoint", 0.00, 4.7),
        ("Katarmal Sun Temple (9th Century)", "heritage", 0.00, 4.8),
        ("Chitai Golu Devta Temple (Temple of Bells)", "temple", 0.00, 4.8),
        ("Binsar Wildlife Sanctuary Zero Point", "wildlife", 150.00, 4.9),
    ],
    ("Auli", "India"): [
        ("Auli Ski Resort & Chairlift", "adventure", 500.00, 4.9),
        ("Auli Artificial Lake & Nanda Devi View", "nature", 0.00, 4.9),
        ("Joshimath-Auli Cable Car (Longest in India)", "viewpoint", 1000.00, 5.0),
        ("Gurso Bugyal Meadow Trek", "adventure", 0.00, 4.8),
        ("Kwani Bugyal Alpine Camp", "nature", 0.00, 4.6),
    ],
    ("Jim Corbett", "India"): [
        ("Dhikala Forest Zone Tiger Safari", "wildlife", 800.00, 4.9),
        ("Bijrani Wildlife Safari Range", "wildlife", 600.00, 4.8),
        ("Corbett Waterfalls & Nature Trail", "waterfall", 50.00, 4.5),
        ("Garjiya Devi Temple on Kosi River", "temple", 0.00, 4.7),
        ("Corbett Museum Kaladhungi (Jim Corbett Home)", "museum", 50.00, 4.4),
    ],
    ("Kausani", "India"): [
        ("Anasakti Ashram (Gandhi Ashram) Viewpoint", "viewpoint", 0.00, 4.8),
        ("Kausani Tea Estate & Processing Tour", "garden", 0.00, 4.5),
        ("Rudradhari Waterfalls & Shiva Caves", "waterfall", 0.00, 4.6),
        ("Baijnath Ancient 12th Century Temples", "heritage", 0.00, 4.7),
        ("Sumitranandan Pant Gallery", "museum", 20.00, 4.2),
    ],
    ("Kedarnath", "India"): [
        ("Kedarnath Temple Jyotirlinga & Glacier", "temple", 0.00, 5.0),
        ("Bhairavnath Temple Mountain Peak", "viewpoint", 0.00, 4.8),
        ("Gandhi Sarovar (Chorabari Lake)", "nature", 0.00, 4.8),
        ("Vasuki Tal High Altitude Lake Trek", "adventure", 0.00, 4.9),
        ("Gaurikund Hot Springs & Trek Base", "religious", 0.00, 4.5),
    ],
    ("Badrinath", "India"): [
        ("Badrinath Temple (Char Dham)", "temple", 0.00, 5.0),
        ("Tapt Kund Natural Hot Sulphur Springs", "religious", 0.00, 4.7),
        ("Mana Village (Last Indian Village on Border)", "cultural", 0.00, 4.9),
        ("Vasudhara Falls 400-Ft Cascade Trek", "waterfall", 0.00, 4.8),
        ("Bheem Pul Natural Stone Bridge & Saraswati River", "nature", 0.00, 4.8),
    ],
    ("Spiti Valley", "India"): [
        ("Key Gompa (Ki Monastery on Cliff)", "religious", 0.00, 5.0),
        ("Chandratal (Moon Lake) High Altitude Glacial Lake", "nature", 0.00, 5.0),
        ("Dhankar Monastery & Fort on Perilous Cliff", "heritage", 0.00, 4.9),
        ("Hikkim Highest Post Office in the World", "monument", 0.00, 4.8),
        ("Komic Highest Village Connected by Motor Road", "cultural", 0.00, 4.8),
    ],
    ("Kasol", "India"): [
        ("Parvati River Walking Trail & Pine Woods", "nature", 0.00, 4.8),
        ("Manikaran Sahib Gurudwara & Hot Springs", "religious", 0.00, 4.8),
        ("Kheerganga Natural Hot Springs Trek", "adventure", 0.00, 4.9),
        ("Tosh Scenic Village & Glacier Viewpoint", "viewpoint", 0.00, 4.7),
        ("Chalal Village Forest Walk", "nature", 0.00, 4.6),
    ],
    ("Dalhousie", "India"): [
        ("Khajjiar Lake & Meadow (Mini Switzerland)", "nature", 0.00, 4.8),
        ("Dainkund Peak (Singing Hill) Trek", "viewpoint", 0.00, 4.8),
        ("Kalatop Wildlife Sanctuary & Pine Forest", "wildlife", 50.00, 4.7),
        ("Panchpula Waterfalls & Memorial", "waterfall", 0.00, 4.4),
        ("St. John's Church at Gandhi Chowk", "heritage", 0.00, 4.5),
    ],
    ("Chandigarh", "India"): [
        ("Nek Chand's Rock Garden (Recycled Art)", "garden", 30.00, 4.8),
        ("Sukhna Lake Promenade & Boating", "nature", 50.00, 4.7),
        ("Zakir Hussain Rose Garden", "garden", 0.00, 4.5),
        ("Capitol Complex (Le Corbusier UNESCO Site)", "architecture", 0.00, 4.7),
        ("Government Museum and Art Gallery", "museum", 20.00, 4.4),
    ],
    ("Patna", "India"): [
        ("Golghar Historic Granary & Ganga View", "historical", 20.00, 4.4),
        ("Takht Sri Patna Sahib (Birthplace of Guru Gobind Singh)", "religious", 0.00, 4.9),
        ("Bihar Museum World-Class Artifacts", "museum", 100.00, 4.8),
        ("Patna Planetarium (Indira Gandhi Science Complex)", "museum", 50.00, 4.3),
        ("Kumhrar Ancient Mauryan Ruins of Pataliputra", "historical", 20.00, 4.3),
    ],
    ("Bodh Gaya", "India"): [
        ("Mahabodhi Temple Complex & Sacred Bodhi Tree", "heritage", 0.00, 5.0),
        ("Great Buddha Statue (80-Foot)", "monument", 0.00, 4.8),
        ("Thai Monastery & Wat Thai Bodhgaya", "religious", 0.00, 4.7),
        ("Royal Bhutanese Monastery", "religious", 0.00, 4.6),
        ("Muchalinda Lake & Mucalinda Buddha", "nature", 0.00, 4.5),
    ],
    ("Nalanda", "India"): [
        ("Ruins of Nalanda Ancient Mahavihara University", "heritage", 40.00, 5.0),
        ("Nalanda Archaeological Museum", "museum", 20.00, 4.5),
        ("Xuanzang (Hiuen Tsang) Memorial Hall", "monument", 50.00, 4.6),
        ("Surajpur Baragaon Sun Temple", "temple", 0.00, 4.3),
        ("Kundalpur Digambar Jain Temple", "temple", 0.00, 4.4),
    ],
    ("Ranchi", "India"): [
        ("Hundru Waterfalls on Subarnarekha River", "waterfall", 20.00, 4.6),
        ("Dassam Falls & Natural Pool", "waterfall", 20.00, 4.6),
        ("Jonha (Gautam Dhara) Falls", "waterfall", 20.00, 4.5),
        ("Pahar Mandir (Ranchi Hill Shiva Temple)", "temple", 0.00, 4.5),
        ("Tagore Hill (Rabindranath Tagore Heritage)", "viewpoint", 0.00, 4.4),
    ],
    ("Jamshedpur", "India"): [
        ("Jubilee Park & Musical Laser Fountains", "park", 0.00, 4.7),
        ("Dalma Wildlife Sanctuary & Elephants", "wildlife", 50.00, 4.6),
        ("Dimna Lake & Boating Reservoir", "nature", 0.00, 4.5),
        ("Tata Steel Zoological Park", "wildlife", 30.00, 4.4),
        ("Bhuvaneshwari Temple Hilltop View", "viewpoint", 0.00, 4.5),
    ],
    ("Hazaribagh", "India"): [
        ("Hazaribagh National Park & Wildlife Sanctuary", "wildlife", 50.00, 4.5),
        ("Canary Hill Pine Forest Viewpoint", "viewpoint", 0.00, 4.6),
        ("Hazaribagh Urban Lake Complex", "nature", 0.00, 4.3),
        ("Sanskriti Museum & Indigenous Sohrai Art Gallery", "museum", 0.00, 4.7),
        ("Konar Dam & Reservoir", "nature", 0.00, 4.4),
    ],
    ("Raipur", "India"): [
        ("Swami Vivekananda Sarovar (Budha Talab)", "nature", 20.00, 4.5),
        ("Mahant Ghasidas Memorial Museum", "museum", 20.00, 4.4),
        ("Nandanvan Jungle Safari Naya Raipur", "wildlife", 150.00, 4.6),
        ("Purkhauti Muktangan Cultural Open-Air Museum", "cultural", 30.00, 4.7),
        ("Bambleshwari Temple Dongargarh Ropeway", "temple", 100.00, 4.7),
    ],
    ("Lepakshi", "India"): [
        ("Veerabhadra Temple Hanging Pillar Marvel", "heritage", 0.00, 5.0),
        ("Monolithic Lepakshi Nandi Bull", "monument", 0.00, 4.9),
        ("Nagalinga 7-Headed Serpent Monolith", "monument", 0.00, 4.8),
        ("Kalyana Mandapam Incomplete Wedding Pavilion", "architecture", 0.00, 4.7),
        ("Lata Mandapam Fresco Gallery", "cultural", 0.00, 4.6),
    ],
    ("Visakhapatnam", "India"): [
        ("INS Kursura Submarine Museum RK Beach", "museum", 70.00, 4.8),
        ("Kailasagiri Hilltop Park & Cable Car", "viewpoint", 100.00, 4.7),
        ("Rushikonda Beach & Water Sports", "beach", 0.00, 4.6),
        ("TU-142 Aircraft Museum", "museum", 70.00, 4.7),
        ("Yarada Scenic Beach & Dolphin's Nose", "nature", 0.00, 4.6),
    ],
    ("Araku Valley", "India"): [
        ("Borra Caves (Million-Year Stalactites)", "nature", 80.00, 4.8),
        ("Araku Coffee Plantation & Tribal Museum", "cultural", 40.00, 4.6),
        ("Chapaparai Water Cascades", "waterfall", 20.00, 4.4),
        ("Katiki Waterfalls Trek", "waterfall", 0.00, 4.7),
        ("Padmapuram Botanical Gardens & Treehuts", "garden", 30.00, 4.3),
    ],
    ("Tirupati", "India"): [
        ("Sri Venkateswara Swamy Temple Tirumala", "temple", 0.00, 5.0),
        ("Sri Padmavathi Ammavari Temple Tiruchanur", "temple", 0.00, 4.8),
        ("Silathoranam Natural Stone Rock Arch", "nature", 0.00, 4.7),
        ("Kapila Theertham Waterfalls & Temple", "waterfall", 0.00, 4.6),
        ("Sri Venkateswara National Park & Zoo", "wildlife", 50.00, 4.5),
    ],
    ("Vijayawada", "India"): [
        ("Kanaka Durga Hilltop Temple", "temple", 0.00, 4.9),
        ("Undavalli 7th-Century Rock-Cut Caves", "heritage", 25.00, 4.7),
        ("Bhavani Island Krishna River Tourism Hub", "nature", 100.00, 4.5),
        ("Prakasam Barrage Waterfront", "viewpoint", 0.00, 4.5),
        ("Bapu Museum (Victoria Jubilee Museum)", "museum", 50.00, 4.6),
    ],
    ("Warangal", "India"): [
        ("Thousand Pillar Temple (Kakatiya Marvel)", "temple", 0.00, 4.8),
        ("Ramappa Temple UNESCO Kakatiya Heritage", "heritage", 40.00, 4.9),
        ("Warangal Fort & Stone Gateway Arch (Kirti Torana)", "fort", 25.00, 4.7),
        ("Bhadrakali Temple & Lake Promenade", "temple", 0.00, 4.6),
        ("Pakhal Lake & Wildlife Sanctuary", "nature", 0.00, 4.5),
    ],
    ("Port Blair", "India"): [
        ("Cellular Jail National Memorial & Light Show", "monument", 50.00, 4.9),
        ("Ross Island (Netaji Subhash Chandra Bose Island)", "heritage", 100.00, 4.8),
        ("Corbyn's Cove Beach", "beach", 0.00, 4.5),
        ("Samudrika Naval Marine Museum", "museum", 50.00, 4.6),
        ("Chidiya Tapu Sunset Point & Bird Watching", "viewpoint", 0.00, 4.7),
    ],
    ("Havelock Island", "India"): [
        ("Radhanagar Beach (Asia's Best Beach)", "beach", 0.00, 5.0),
        ("Elephant Beach Coral Reef & Snorkeling", "adventure", 500.00, 4.9),
        ("Kalapathar Beach Turquoise Waters", "beach", 0.00, 4.7),
        ("Vijay Nagar Beach & Mangrove Kayaking", "nature", 300.00, 4.6),
        ("Nemo Reef Scuba Diving", "adventure", 3500.00, 4.9),
    ],
    ("Neil Island", "India"): [
        ("Natural Coral Rock Bridge (Howrah Bridge)", "nature", 0.00, 4.8),
        ("Bharatpur Beach Watersports & Coral Reef", "beach", 0.00, 4.7),
        ("Laxmanpur Beach Sunset Point", "beach", 0.00, 4.8),
        ("Sitapur Beach Sunrise Point", "beach", 0.00, 4.6),
        ("Neil Island Glass Bottom Boat Tour", "adventure", 600.00, 4.5),
    ],
    ("Kavaratti", "India"): [
        ("Kavaratti Lagoon Scuba Diving & Snorkeling", "adventure", 2500.00, 4.9),
        ("Marine Aquarium & Museum Kavaratti", "museum", 50.00, 4.6),
        ("Ujra Ancient 17th Century Mosque", "heritage", 0.00, 4.7),
        ("Kavaratti Lighthouse Panoramic View", "viewpoint", 20.00, 4.6),
        ("Dolphin Dive Centre Coral Excursion", "adventure", 2000.00, 4.8),
    ],
    ("Diu", "India"): [
        ("Diu Fortress on Arabian Sea", "fort", 0.00, 4.7),
        ("Naida Caves Natural Limestone Caverns", "nature", 0.00, 4.8),
        ("Nagoa Horseshoe Beach & Water Sports", "beach", 0.00, 4.6),
        ("St. Paul's Church Portuguese Architecture", "architecture", 0.00, 4.5),
        ("Gangeshwar Mahadev Sea Cave Shiva Lingas", "temple", 0.00, 4.6),
    ],
    ("Daman", "India"): [
        ("Moti Daman Portuguese Fortress & Ramparts", "fort", 0.00, 4.6),
        ("Nani Daman Fort (St. Jerome Fort)", "fort", 0.00, 4.5),
        ("Jampore Beach Casuarina Grove", "beach", 0.00, 4.4),
        ("Devka Beach & Amusement Promenade", "beach", 0.00, 4.2),
        ("Church of Bom Jesus Daman", "heritage", 0.00, 4.6),
    ],
    ("Silvassa", "India"): [
        ("Vanganga Garden & Boating Lake", "garden", 20.00, 4.4),
        ("Tribal Cultural Museum Silvassa", "museum", 0.00, 4.6),
        ("Dudhni Water Sports Complex (Madhuban Dam)", "adventure", 150.00, 4.5),
        ("Our Lady of Piety 19th Century Church", "heritage", 0.00, 4.4),
        ("Lion Safari Wildlife Park Silvassa", "wildlife", 50.00, 4.3),
    ],
}
