"""Attractions for 51 North and Central American destinations in RoamGenie (Phase D2)."""
from typing import Dict, List, Tuple

# Format: (name, category, entry_fee_inr, rating)
NORTH_AMERICA_ATTRACTIONS: Dict[Tuple[str, str], List[Tuple[str, str, float, float]]] = {
    # United States (26)
    ("New York City", "United States"): [
        ("Statue of Liberty & Ellis Island National Monument", "monument", 2200.00, 4.8),
        ("Central Park & Bethesda Terrace", "park", 0.00, 4.9),
        ("Empire State Building 86th Floor Observatory", "viewpoint", 3500.00, 4.7),
        ("The Metropolitan Museum of Art (The Met)", "museum", 2500.00, 4.9),
        ("Times Square & Broadway Theatre District", "cultural", 0.00, 4.7),
        ("Brooklyn Bridge Pedestrian Promenade", "viewpoint", 0.00, 4.8),
    ],
    ("Los Angeles", "United States"): [
        ("Hollywood Sign & Griffith Observatory", "viewpoint", 0.00, 4.8),
        ("Universal Studios Hollywood Studio Tour", "park", 9000.00, 4.8),
        ("Santa Monica Pier & Historic Carousel", "beach", 0.00, 4.7),
        ("The Getty Center Art Museum & Tram", "museum", 0.00, 4.9),
        ("Venice Beach Boardwalk & Muscle Beach", "beach", 0.00, 4.5),
    ],
    ("San Francisco", "United States"): [
        ("Golden Gate Bridge Walk & Lookout", "viewpoint", 0.00, 4.9),
        ("Alcatraz Island Historic Penitentiary Tour", "historical", 3500.00, 4.9),
        ("Fisherman's Wharf & Pier 39 Sea Lions", "cultural", 0.00, 4.6),
        ("Lombard Street Crooked Floral Section", "monument", 0.00, 4.5),
        ("San Francisco Cable Car System Ride", "adventure", 700.00, 4.8),
    ],
    ("Las Vegas", "United States"): [
        ("Las Vegas Strip & Fountains of Bellagio", "cultural", 0.00, 4.8),
        ("High Roller Observation Wheel (550ft)", "viewpoint", 2800.00, 4.6),
        ("Fremont Street Experience Viva Vision Light Show", "cultural", 0.00, 4.6),
        ("The Venetian Resort Indoor Gondola Rides", "cultural", 3200.00, 4.7),
        ("Red Rock Canyon National Conservation Area Excursion", "nature", 1200.00, 4.8),
    ],
    ("Chicago", "United States"): [
        ("Millennium Park & Cloud Gate (The Bean)", "monument", 0.00, 4.8),
        ("Art Institute of Chicago Masterpieces", "museum", 2600.00, 4.9),
        ("Skydeck Chicago at Willis Tower (The Ledge)", "viewpoint", 3000.00, 4.7),
        ("Chicago Architecture River Boat Tour", "architecture", 3500.00, 4.9),
        ("Navy Pier & Centennial Wheel", "park", 0.00, 4.5),
    ],
    ("Miami", "United States"): [
        ("South Beach Art Deco Historic District", "architecture", 0.00, 4.7),
        ("Wynwood Walls Open-Air Street Art Museum", "cultural", 1000.00, 4.7),
        ("Vizcaya Museum and Gardens Estate", "palace", 2000.00, 4.8),
        ("Everglades National Park Airboat Safari Excursion", "wildlife", 2800.00, 4.8),
        ("Little Havana Calle Ocho Cultural Walk", "cultural", 0.00, 4.6),
    ],
    ("Orlando", "United States"): [
        ("Magic Kingdom at Walt Disney World Resort", "park", 12500.00, 4.9),
        ("Universal's Islands of Adventure (Wizarding World)", "park", 11500.00, 4.9),
        ("Epcot World Showcase & Spaceship Earth", "park", 12000.00, 4.7),
        ("SeaWorld Orlando Theme Park", "park", 8500.00, 4.6),
        ("ICON Park & The Wheel at ICON Park", "viewpoint", 2200.00, 4.5),
    ],
    ("Washington D.C.", "United States"): [
        ("National Mall & Lincoln Memorial", "monument", 0.00, 4.9),
        ("Smithsonian National Air and Space Museum", "museum", 0.00, 4.9),
        ("United States Capitol & Visitor Center", "historical", 0.00, 4.8),
        ("Smithsonian National Museum of Natural History", "museum", 0.00, 4.8),
        ("Washington Monument Reflecting Pool", "monument", 0.00, 4.7),
    ],
    ("Boston", "United States"): [
        ("Freedom Trail 2.5-Mile Historic Walking Tour", "historical", 0.00, 4.8),
        ("Boston Common & Public Garden Swan Boats", "park", 350.00, 4.7),
        ("Museum of Fine Arts Boston (MFA)", "museum", 2200.00, 4.8),
        ("Faneuil Hall Marketplace & Quincy Market", "market", 0.00, 4.6),
        ("Fenway Park Historic Baseball Stadium Tour", "cultural", 2500.00, 4.8),
    ],
    ("Seattle", "United States"): [
        ("Space Needle 520ft Observation Deck", "viewpoint", 3200.00, 4.7),
        ("Pike Place Market & Original Starbucks", "market", 0.00, 4.8),
        ("Chihuly Garden and Glass Sculptures", "museum", 2800.00, 4.9),
        ("Museum of Pop Culture (MoPOP)", "museum", 2600.00, 4.6),
        ("Seattle Waterfront & Bainbridge Island Ferry", "nature", 750.00, 4.7),
    ],
    ("New Orleans", "United States"): [
        ("French Quarter & Bourbon Street Historic Hub", "cultural", 0.00, 4.7),
        ("Jackson Square & St. Louis Cathedral", "religious", 0.00, 4.8),
        ("Preservation Hall Traditional Jazz Concert", "cultural", 2000.00, 4.9),
        ("National WWII Museum (World-Class Exhibits)", "museum", 2800.00, 4.9),
        ("Louisiana Manchac Swamp Boat Tour", "wildlife", 2500.00, 4.8),
    ],
    ("Austin", "United States"): [
        ("Texas State Capitol & Grounds Tour", "historical", 0.00, 4.8),
        ("Barton Springs Natural Limestone Pool", "nature", 750.00, 4.7),
        ("South Congress Avenue (SoCo) Vintage Shops", "cultural", 0.00, 4.6),
        ("Lady Bird Lake Hike & Bike Trail & Kayaking", "nature", 1200.00, 4.8),
        ("Congress Avenue Bridge Bat Watching at Dusk", "wildlife", 0.00, 4.7),
    ],
    ("Honolulu", "United States"): [
        ("Waikiki Beach & Diamond Head Crater Panorama", "beach", 0.00, 4.8),
        ("Pearl Harbor National Memorial & USS Arizona", "historical", 0.00, 4.9),
        ("Diamond Head State Monument Summit Trail", "adventure", 450.00, 4.8),
        ("Hanauma Bay Nature Preserve Snorkeling", "nature", 2000.00, 4.8),
        ("Iolani Palace (Only Royal Palace in the US)", "palace", 2200.00, 4.7),
    ],
    ("San Diego", "United States"): [
        ("San Diego Zoo at Balboa Park", "wildlife", 6000.00, 4.9),
        ("Balboa Park Historic Spanish Village & Gardens", "garden", 0.00, 4.8),
        ("USS Midway Aircraft Carrier Museum", "museum", 2600.00, 4.9),
        ("La Jolla Cove Sea Lions & Coastal Cliffs", "nature", 0.00, 4.8),
        ("Coronado Beach & Historic Hotel del Coronado", "beach", 0.00, 4.7),
    ],
    ("Nashville", "United States"): [
        ("Grand Ole Opry Live Country Music House", "cultural", 4500.00, 4.9),
        ("Country Music Hall of Fame and Museum", "museum", 2400.00, 4.8),
        ("Broadway Honky Tonk Highway Live Music", "cultural", 0.00, 4.8),
        ("Ryman Auditorium (Mother Church of Country)", "heritage", 2200.00, 4.8),
        ("The Parthenon Full-Scale Replica in Centennial Park", "monument", 800.00, 4.6),
    ],
    ("Denver", "United States"): [
        ("Red Rocks Park and Amphitheatre Monoliths", "viewpoint", 0.00, 4.9),
        ("Denver Art Museum (Hamilton Building)", "museum", 1800.00, 4.7),
        ("Denver Botanic Gardens on York Street", "garden", 1200.00, 4.8),
        ("Rocky Mountain National Park Day Tour Excursion", "nature", 3500.00, 5.0),
        ("Larimer Square Victorian Gaslamp District", "cultural", 0.00, 4.5),
    ],
    ("Portland", "United States"): [
        ("Portland Japanese Garden in Washington Park", "garden", 1600.00, 4.9),
        ("Powell's City of Books (World's Largest Bookstore)", "cultural", 0.00, 4.8),
        ("International Rose Test Garden", "garden", 0.00, 4.8),
        ("Multnomah Falls Columbia River Gorge Excursion", "waterfall", 0.00, 4.9),
        ("Pittock Mansion Panoramic Skyline Estate", "heritage", 1100.00, 4.7),
    ],
    ("Atlanta", "United States"): [
        ("Georgia Aquarium (Whale Sharks Ocean Voyager)", "wildlife", 3800.00, 4.8),
        ("World of Coca-Cola Interactive Museum", "museum", 1600.00, 4.6),
        ("Martin Luther King Jr. National Historical Park", "historical", 0.00, 4.9),
        ("Atlanta Botanical Garden & Canopy Walk", "garden", 2200.00, 4.8),
        ("Piedmont Park & Atlanta BeltLine Trail", "park", 0.00, 4.7),
    ],
    ("Philadelphia", "United States"): [
        ("Independence Hall (UNESCO Birthplace of US)", "historical", 0.00, 4.9),
        ("Liberty Bell Center", "monument", 0.00, 4.7),
        ("Philadelphia Museum of Art & Rocky Steps", "museum", 2200.00, 4.8),
        ("Reading Terminal Market Food Hall", "market", 0.00, 4.8),
        ("Eastern State Penitentiary Historic Ruins", "historical", 1600.00, 4.7),
    ],
    ("Salt Lake City", "United States"): [
        ("Temple Square & Salt Lake Temple Assembly Hall", "religious", 0.00, 4.8),
        ("Utah State Capitol Building on Capitol Hill", "historical", 0.00, 4.7),
        ("Great Salt Lake & Antelope Island State Park", "nature", 1200.00, 4.8),
        ("Natural History Museum of Utah (Rio Tinto Center)", "museum", 1600.00, 4.8),
        ("Red Butte Garden and Arboretum", "garden", 1200.00, 4.7),
    ],
    ("San Antonio", "United States"): [
        ("The Alamo Historic 18th Century Mission (UNESCO)", "historical", 0.00, 4.8),
        ("San Antonio River Walk (Paseo del Río)", "cultural", 0.00, 4.8),
        ("San Antonio Missions National Historical Park", "heritage", 0.00, 4.8),
        ("Tower of the Americas Observation Deck", "viewpoint", 1400.00, 4.5),
        ("Historic Market Square (El Mercado)", "market", 0.00, 4.5),
    ],
    ("Savannah", "United States"): [
        ("Forsyth Park & Historic Spanish Moss Fountain", "park", 0.00, 4.8),
        ("Savannah Historic District 22 Cobblestone Squares", "heritage", 0.00, 4.8),
        ("Bonaventure Cemetery Sculptural Oaks", "historical", 0.00, 4.8),
        ("River Street Savannah Waterfront & Cotton Sail", "cultural", 0.00, 4.6),
        ("Cathedral Basilica of St. John the Baptist", "religious", 250.00, 4.9),
    ],
    ("Charleston", "United States"): [
        ("Rainbow Row Pastel Historic Georgian Houses", "architecture", 0.00, 4.7),
        ("The Battery & White Point Garden Harbor View", "viewpoint", 0.00, 4.8),
        ("Fort Sumter National Monument Island Ferry", "historical", 2500.00, 4.8),
        ("Magnolia Plantation & Romantic Gardens", "garden", 2400.00, 4.7),
        ("Charleston Historic City Market", "market", 0.00, 4.6),
    ],
    ("Santa Fe", "United States"): [
        ("Santa Fe Plaza Historic Adobe Downtown", "cultural", 0.00, 4.7),
        ("Palace of the Governors Native American Market", "historical", 1000.00, 4.6),
        ("Loretto Chapel Miraculous Spiral Staircase", "religious", 450.00, 4.7),
        ("Meow Wolf Santa Fe (House of Eternal Return)", "museum", 3200.00, 4.9),
        ("Canyon Road Art Galleries & Adobe Studios", "cultural", 0.00, 4.8),
    ],
    ("Sedona", "United States"): [
        ("Cathedral Rock Red Sandstone Trail", "adventure", 0.00, 5.0),
        ("Chapel of the Holy Cross Built into Rock", "religious", 0.00, 4.8),
        ("Bell Rock Red Rock Vortex Trail", "nature", 0.00, 4.8),
        ("Devil's Bridge Natural Stone Arch Hike", "viewpoint", 0.00, 4.9),
        ("Tlaquepaque Arts & Shopping Village", "cultural", 0.00, 4.6),
    ],
    ("Anchorage", "United States"): [
        ("Tony Knowles Coastal Trail Cook Inlet Walk", "nature", 0.00, 4.8),
        ("Alaska Native Heritage Center", "cultural", 2200.00, 4.7),
        ("Chugach State Park & Flattop Mountain Trail", "adventure", 0.00, 4.9),
        ("Anchorage Museum at Rasmuson Center", "museum", 1800.00, 4.7),
        ("Kenai Fjords National Park Glacier Cruise Excursion", "wildlife", 14000.00, 5.0),
    ],

    # Canada (11)
    ("Toronto", "Canada"): [
        ("CN Tower 553m Glass Floor & LookOut", "viewpoint", 3200.00, 4.7),
        ("Royal Ontario Museum (ROM Crystal)", "museum", 2000.00, 4.8),
        ("Ripley's Aquarium of Canada", "wildlife", 3000.00, 4.8),
        ("Distillery Historic District Victorian Brick Lane", "cultural", 0.00, 4.7),
        ("Toronto Islands Ferry & Skyline View", "nature", 650.00, 4.8),
    ],
    ("Vancouver", "Canada"): [
        ("Stanley Park Seawall & Totem Poles", "park", 0.00, 4.9),
        ("Capilano Suspension Bridge & Treetops Adventure", "adventure", 4500.00, 4.8),
        ("Granville Island Public Market & Artisan Guilds", "market", 0.00, 4.8),
        ("Gastown Steam Clock Historic District", "historical", 0.00, 4.5),
        ("Grouse Mountain Skyride & Grizzly Sanctuary", "viewpoint", 5000.00, 4.7),
    ],
    ("Montreal", "Canada"): [
        ("Notre-Dame Basilica of Montreal (AURA Light Show)", "religious", 1100.00, 4.9),
        ("Mount Royal (Mont-Royal) Park Kondiaronk Lookout", "viewpoint", 0.00, 4.8),
        ("Old Montreal (Vieux-Montréal) Cobblestone Quarters", "heritage", 0.00, 4.8),
        ("Montreal Botanical Garden & Insectarium", "garden", 1600.00, 4.8),
        ("Jean-Talon Traditional French Farmers' Market", "market", 0.00, 4.7),
    ],
    ("Quebec City", "Canada"): [
        ("Château Frontenac & Dufferin Terrace Boardwalk", "palace", 0.00, 4.9),
        ("Old Quebec (Vieux-Québec UNESCO Walled City)", "heritage", 0.00, 4.9),
        ("Quartier Petit Champlain European Street", "cultural", 0.00, 4.8),
        ("Montmorency Falls Suspension Bridge & Cable Car", "waterfall", 650.00, 4.7),
        ("La Citadelle de Québec & Museum", "fort", 1500.00, 4.7),
    ],
    ("Banff", "Canada"): [
        ("Lake Louise Turquoise Glacial Waters & Chateaux", "nature", 0.00, 5.0),
        ("Moraine Lake Valley of the Ten Peaks", "nature", 0.00, 5.0),
        ("Banff Gondola to Sulphur Mountain Summit", "viewpoint", 5500.00, 4.9),
        ("Banff Upper Hot Springs Thermal Pool", "nature", 1200.00, 4.6),
        ("Johnston Canyon Lower & Upper Waterfalls Hike", "waterfall", 0.00, 4.8),
    ],
    ("Calgary", "Canada"): [
        ("Calgary Tower 360 Glass Floor Lookout", "viewpoint", 1400.00, 4.5),
        ("Heritage Park Historical Village", "cultural", 2200.00, 4.8),
        ("Calgary Stampede Park (Rodeo Grounds)", "cultural", 1600.00, 4.7),
        ("Calgary Zoo & Prehistoric Park", "wildlife", 2400.00, 4.7),
        ("Peace Bridge over Bow River", "architecture", 0.00, 4.6),
    ],
    ("Ottawa", "Canada"): [
        ("Parliament Hill & Peace Tower", "historical", 0.00, 4.8),
        ("Rideau Canal UNESCO Skating & Boating", "nature", 0.00, 4.8),
        ("Canadian Museum of History (Grand Hall)", "museum", 1600.00, 4.9),
        ("National Gallery of Canada & Maman Spider", "museum", 1500.00, 4.8),
        ("ByWard Market Food and Artisan Stalls", "market", 0.00, 4.6),
    ],
    ("Victoria", "Canada"): [
        ("The Butchart Gardens World-Famous Floral Pavilions", "garden", 2800.00, 4.9),
        ("Royal BC Museum Indigenous History", "museum", 2000.00, 4.8),
        ("British Columbia Parliament Buildings & Harbor", "architecture", 0.00, 4.7),
        ("Craigdarroch Castle Victorian Mansion", "palace", 1500.00, 4.6),
        ("Fisherman's Wharf Houseboats & Seal Watching", "cultural", 0.00, 4.6),
    ],
    ("Whistler", "Canada"): [
        ("PEAK 2 PEAK Gondola (Record-Breaking Alpine Ride)", "adventure", 6500.00, 5.0),
        ("Whistler Blackcomb World-Class Ski Resort", "adventure", 12000.00, 4.9),
        ("Whistler Village Pedestrian Stroll & Cafes", "cultural", 0.00, 4.8),
        ("Lost Lake Forest Walking & Snowshoeing Trail", "nature", 0.00, 4.7),
        ("Squamish Lil'wat Cultural Indigenous Centre", "cultural", 1500.00, 4.8),
    ],
    ("Jasper", "Canada"): [
        ("Maligne Lake & Spirit Island Cruise", "nature", 5500.00, 5.0),
        ("Columbia Icefield Skywalk & Ice Explorer Glacier Ride", "adventure", 7500.00, 4.9),
        ("Athabasca Falls Powerful Canyon Chasm", "waterfall", 0.00, 4.8),
        ("Jasper SkyTram Whistlers Mountain Summit", "viewpoint", 4200.00, 4.8),
        ("Maligne Canyon Deep Limestone Gorge Trail", "nature", 0.00, 4.8),
    ],
    ("Halifax", "Canada"): [
        ("Halifax Citadel National Historic Site (Hill Fortress)", "fort", 1100.00, 4.8),
        ("Peggy's Cove Iconic Lighthouse & Granite Rocks Excursion", "viewpoint", 0.00, 4.9),
        ("Halifax Waterfront Boardwalk (4km Harbour Stroll)", "cultural", 0.00, 4.8),
        ("Maritime Museum of the Atlantic (Titanic Collection)", "museum", 800.00, 4.7),
        ("Halifax Public Gardens Victorian Oasis", "garden", 0.00, 4.8),
    ],

    # Mexico (9)
    ("Mexico City", "Mexico"): [
        ("Zocalo & Metropolitan Cathedral of Mexico City", "religious", 0.00, 4.8),
        ("National Museum of Anthropology (Aztec Sun Stone)", "museum", 400.00, 5.0),
        ("Chapultepec Castle Imperial Residence", "palace", 400.00, 4.9),
        ("Frida Kahlo Museum (Casa Azul Coyoacán)", "museum", 1200.00, 4.8),
        ("Teotihuacan Pyramids of the Sun and Moon Excursion", "heritage", 400.00, 5.0),
    ],
    ("Cancun", "Mexico"): [
        ("Cancun Underwater Museum of Art (MUSA Snorkeling)", "adventure", 3800.00, 4.8),
        ("Isla Mujeres Garrafon Reef Park Ferry", "beach", 1500.00, 4.8),
        ("Playa Delfines (El Mirador Cancun Sign Beach)", "beach", 0.00, 4.7),
        ("El Rey Maya Archaeological Zone Ruins", "historical", 350.00, 4.4),
        ("Xcaret Eco-Archaeological Nature Theme Park", "park", 8500.00, 4.9),
    ],
    ("Playa del Carmen", "Mexico"): [
        ("Fifth Avenue (Quinta Avenida) Pedestrian Strip", "cultural", 0.00, 4.7),
        ("Rio Secreto Underground Crystal Caves", "adventure", 5500.00, 5.0),
        ("Cenote Chaak Tun Sacred Limestone Sinkhole", "nature", 2200.00, 4.8),
        ("Xel-Há All-Inclusive Natural Aquatic Lagoon", "park", 7500.00, 4.9),
        ("Playacar White Sand Coral Beach", "beach", 0.00, 4.6),
    ],
    ("Oaxaca", "Mexico"): [
        ("Santo Domingo de Guzmán Baroque Church & Museum", "religious", 350.00, 4.9),
        ("Monte Albán UNESCO Zapotec Mountain Citadel", "heritage", 400.00, 5.0),
        ("Mercado 20 de Noviembre (Smoky Meat Alley)", "market", 0.00, 4.9),
        ("Hierve el Agua Petrified Rock Waterfalls Excursion", "nature", 250.00, 4.9),
        ("Tule Tree (World's Stoutest Tree Trunk)", "nature", 80.00, 4.5),
    ],
    ("Guadalajara", "Mexico"): [
        ("Hospicio Cabañas UNESCO (Orozco Murals)", "heritage", 350.00, 4.9),
        ("Guadalajara Cathedral Twin Neo-Gothic Spires", "religious", 0.00, 4.7),
        ("Tequila Historic Town & Agave Fields Train Tour", "cultural", 8500.00, 4.9),
        ("Tlaquepaque Ceramic & Mariachi Plaza", "cultural", 0.00, 4.8),
        ("Teatro Degollado Neoclassical Opera House", "architecture", 100.00, 4.7),
    ],
    ("Puerto Vallarta", "Mexico"): [
        ("Malecon Oceanfront Sculpture Boardwalk", "viewpoint", 0.00, 4.8),
        ("Church of Our Lady of Guadalupe Crown Tower", "religious", 0.00, 4.7),
        ("Los Arcos Marine Park Snorkeling Excursion", "adventure", 2500.00, 4.8),
        ("Zona Romantica & Playa Los Muertos Pier", "beach", 0.00, 4.7),
        ("Vallarta Botanical Gardens Tropical River Rainforest", "garden", 800.00, 4.9),
    ],
    ("San Miguel de Allende", "Mexico"): [
        ("Parroquia de San Miguel Arcángel Pink Stone Church", "religious", 0.00, 5.0),
        ("El Jardín Central Plaza & Live Guitarists", "cultural", 0.00, 4.8),
        ("El Charco del Ingenio Botanical Reserve", "garden", 250.00, 4.7),
        ("Fabrica La Aurora Art & Design Factory Complex", "cultural", 0.00, 4.8),
        ("Mirador de San Miguel Panoramic Lookout", "viewpoint", 0.00, 4.8),
    ],
    ("Tulum", "Mexico"): [
        ("Tulum Mayan Sea-Cliff Archaeological Ruins", "heritage", 400.00, 4.9),
        ("Gran Cenote Crystal Cave Snorkeling with Turtles", "nature", 1200.00, 4.8),
        ("Playa Paraiso Coconut Palm Coastline", "beach", 0.00, 4.8),
        ("Sian Ka'an Biosphere Reserve Eco Boat Safari", "wildlife", 6500.00, 5.0),
        ("Cenote Calavera (Temple of Doom Cliff Jump)", "adventure", 800.00, 4.6),
    ],
    ("Merida", "Mexico"): [
        ("Plaza Grande & San Ildefonso Cathedral (Oldest on Mainland)", "religious", 0.00, 4.8),
        ("Paseo de Montejo French Mansions Promenade", "architecture", 0.00, 4.7),
        ("Chichen Itza UNESCO Mayan Pyramid (El Castillo) Excursion", "heritage", 2400.00, 5.0),
        ("Uxmal UNESCO Mayan Archaeological Complex", "heritage", 2100.00, 4.9),
        ("Gran Museo del Mundo Maya", "museum", 600.00, 4.7),
    ],

    # Central America & Caribbean (5)
    ("San Jose", "Costa Rica"): [
        ("National Theatre of Costa Rica (Teatro Nacional)", "architecture", 450.00, 4.8),
        ("Pre-Columbian Gold Museum (Museo del Oro Precolombino)", "museum", 750.00, 4.7),
        ("Central Market (Mercado Central) Sodas & Spices", "market", 0.00, 4.5),
        ("Poas Volcano National Park Steaming Crater Excursion", "nature", 1200.00, 4.8),
        ("La Paz Waterfall Gardens & Wildlife Sanctuary", "wildlife", 3500.00, 4.9),
    ],
    ("Panama City", "Panama"): [
        ("Panama Canal Miraflores Locks Visitor Center", "historical", 1500.00, 4.8),
        ("Casco Viejo (Historic Colonial San Felipe Quarter)", "heritage", 0.00, 4.8),
        ("Biomuseo Biodiversity Museum (Frank Gehry)", "museum", 1400.00, 4.7),
        ("Amador Causeway Waterfront Walk & Skyline View", "viewpoint", 0.00, 4.7),
        ("Ancon Hill Rainforest Hike & Giant Flag Lookout", "nature", 0.00, 4.6),
    ],
    ("Antigua Guatemala", "Guatemala"): [
        ("Santa Catalina Arch (Arco de Santa Catalina)", "monument", 0.00, 4.9),
        ("Cerro de la Cruz Panoramic Volcano Lookout", "viewpoint", 0.00, 4.8),
        ("Iglesia de la Merced Baroque Yellow Facade", "religious", 0.00, 4.7),
        ("Acatenango Volcano Overnight Hiking & Fuego Views", "adventure", 4500.00, 5.0),
        ("Hobbitenango Eco Park & Giant Hand Viewpoint", "park", 400.00, 4.7),
    ],
    ("Havana", "Cuba"): [
        ("Old Havana (Habana Vieja) Plaza Vieja & Cathedrals", "heritage", 0.00, 4.9),
        ("El Malecón 8km Oceanfront Seawall", "viewpoint", 0.00, 4.8),
        ("Classic American Convertible Car Vintage Tour", "adventure", 3500.00, 4.9),
        ("National Capitol Building (El Capitolio)", "architecture", 800.00, 4.7),
        ("Morro Castle (Castillo de los Tres Reyes del Morro)", "fort", 500.00, 4.7),
    ],
    ("San Juan", "Puerto Rico"): [
        ("Castillo San Felipe del Morro 16th-Century Fortress", "fort", 850.00, 4.9),
        ("Castillo San Cristóbal Spanish Ramparts", "fort", 850.00, 4.8),
        ("Old San Juan Colorful Historic Streets & Umbrellas", "heritage", 0.00, 4.8),
        ("El Yunque National Rainforest & La Mina Falls Excursion", "nature", 1500.00, 4.9),
        ("Condado Beach & Oceanfront Promenade", "beach", 0.00, 4.6),
    ],
}
