import { useState } from "react";
import { previewPlan } from "../services/api";
const initial = { starting_location:"Chennai", destination:"Mysuru", start_date:"2026-08-10", end_date:"2026-08-12", travellers:2, total_budget:20000, preferences:["heritage"] };
export default function PlanPage() {
  const [form,setForm]=useState(initial); const [state,setState]=useState({status:"idle"});
  const change=({target})=>setForm({...form,[target.name]:target.type==="number"?Number(target.value):target.value});
  async function submit(event){event.preventDefault();setState({status:"loading"});try{setState({status:"success",data:await previewPlan(form)});}catch(error){setState({status:"error",message:error.message});}}
  return <main className="planner"><section><p className="eyebrow">Mock-backed vertical slice</p><h1>Plan a trip</h1><form onSubmit={submit}><label>Starting location<input required minLength="2" name="starting_location" value={form.starting_location} onChange={change}/></label><label>Destination<input required minLength="2" name="destination" value={form.destination} onChange={change}/></label><div className="row"><label>Start date<input required type="date" name="start_date" value={form.start_date} onChange={change}/></label><label>End date<input required type="date" min={form.start_date} name="end_date" value={form.end_date} onChange={change}/></label></div><div className="row"><label>Travellers<input required min="1" type="number" name="travellers" value={form.travellers} onChange={change}/></label><label>Budget (₹)<input required min="1" type="number" name="total_budget" value={form.total_budget} onChange={change}/></label></div><button disabled={state.status==="loading"}>{state.status==="loading"?"Creating…":"Preview plan"}</button></form>{state.status==="error"&&<p role="alert" className="error">{state.message}</p>}</section><aside className="result" aria-live="polite">{state.status==="idle"&&<p>Your itinerary preview will appear here.</p>}{state.status==="success"&&<><h2>{state.data.summary}</h2>{state.data.days.map(day=><article key={day.day_number}><b>Day {day.day_number}</b><span>{day.items[0].title}</span></article>)}<p><b>Estimated:</b> ₹{state.data.estimated_total}</p></>}</aside></main>;
}

